### ISSUE TITLE
[Question] construct nested model in a single query

### ISSUE THREAD

**Issue by iTakeshi** [scalikejdbc/scalikejdbc#1006]
Assume we have following 2 tables in a DB, and correspondent model classes
```
parents
  - parent_id  int
  - name       varchar(255)

children
  - child_id   int
  - parent_id  int
  - name       varchar(255)
```
```scala
case class ParentModel(parent_id: Int, name: String)
object ParentModel extends SQLSyntaxSupport[ParentModel] { ??? }
case class ChildModel(child_id: Int, parent_id: Int, name: String)
object ChildModel extends SQLSyntaxSupport[ChildModel] { ??? }
```

Here I want to retrieve all records in these tables into the following formatter class which groups all children into their parents:
```scala
case class ParentFormatter(name: String, children: List[ChildModel])
```

To avoid so-called "N+1" problem, the `children` table should be joined in a SQL query:
```sql
select * from parents
left outer join children on parents.parent_id = children.parent_id
```

I want to use QueryDSL feature and directly construct `ParentFormatter`
```scala
select.from(Parent as p)
.leftJoin(Child as c).on(p.parentId, c.parentId)
.toSQL
.map(ParentFormatter.apply _) // I KNOW this doesn't work because WrappedResultSet is processed in a record-by-record manner
.list
.apply()
```

Are there any sophisticated way to realize this kind of grouping?
Thanks in advance (and sorry if my question isn't clear enough).

**Comment by seratch** [comment]
one-to-x API seems to be the one you need. Can you try it out? http://scalikejdbc.org/documentation/one-to-x.html

**Comment by iTakeshi** [comment]
Uh, I should have known this. Thank you very much.

BTW, the first sentence of that page says `Users can write all the mapping operations by using #map or #foldLeft…` and I didn't know the mapping can be `foldLeft`. Is there any documents which explains how such reducer functions can be used as mappings?

**Comment by seratch** [comment]
We don't have any documents on it so far. Checking this test code may be helpful to understand how to use it. https://github.com/scalikejdbc/scalikejdbc/blob/3.3.4/scalikejdbc-interpolation/src/test/scala/scalikejdbc/SQLInterpolationSpec.scala#L180-L225

**Comment by iTakeshi** [comment]
Understood. Thank you!
