### ISSUE TITLE
java.sql.SQLException: No suitable driver found for MISSBLTSTDBS  in SAHI tool

### ISSUE THREAD

**Issue by shubham3736** [scalikejdbc/scalikejdbc#1013]
var $db = _getDB("com.microsoft.sqlserver.jdbc.SQLServerDriver", "MISSBLTSTDBS ", "SPARASKAR", "EQMKI1cQWFc=", true)
 $db.select("Select * from MyTable");

var $rows = $db.select("Select * from MyTable");
_alert($rows.length);
_alert($rows[0].toString());

**Comment by seratch** [comment]
@shubham3736 
I don't know well about MS SQL Server and the "SAHI tool".  Is "SAHI tool" this one? > https://sahipro.com/

The given information is limited but the error message `No suitable driver found for ...` means the JDBC driver `com.microsoft.sqlserver.jdbc.SQLServerDriver` has not been loaded yet in your environment. I'm afraid that it's not a ScalikeJDBC's issue.

**Comment by shubham3736** [comment]
Yes, we are working on Sahi Pro.
We are trying to connect database with our Sahi, while connection getting this error.

Can you please tell us more about ScalikeJDBC's issue like how to resolve and who gonna help me out.

Thanks,

**Comment by seratch** [comment]
Generally speaking, all the things you need to fix this would be:

* Add necessary JDBC drivers to classpath dependencies
* Load driver classes by calling `Class.forName(className)` or `DriverManager.registerDriver`

It's not scalikejdbc-specific.
