### ISSUE TITLE
add String methods instead of Symbol because Symbol literal deprecated since Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#1019]
- `validateAndConvertToNormalStatement.apply` https://github.com/scalikejdbc/scalikejdbc/blob/26e99e720ff6e926b859b2d9d9d60d4eae3c0121/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala#L58-L64
-  `SQL#binByName` https://github.com/scalikejdbc/scalikejdbc/blob/26e99e720ff6e926b859b2d9d9d60d4eae3c0121/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala#L272

any other? 🤔

**Comment by seratch** [comment]
I guess, thanks to @xuwei-k's efforts on this, we can close this issue now. Am I right? @xuwei-k

**Comment by seratch** [comment]
I think we can close this issue now. @xuwei-k Please let me know or reopen if I don't understand it correctly.
