### ISSUE TITLE
scalikejdbc-mapper-generator-core_2.11 3.3.4 not available

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#1025]

**Comment by seratch** [comment]
hmm, it seems that I made a mistake in the operations. Will release it.

**Comment by seratch** [comment]
<img width="611" alt="Screen Shot 2019-06-15 at 3 42 14 PM" src="https://user-images.githubusercontent.com/19658/59548065-3211e780-8f84-11e9-95e4-4d7ff9eab308.png">

**Comment by seratch** [comment]
https://oss.sonatype.org/content/groups/staging/org/scalikejdbc/scalikejdbc-mapper-generator-core_2.11/3.3.4/
