### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException

### ISSUE THREAD

**Issue by duhanmin** [scalikejdbc/scalikejdbc#1030]
```
db.default.driver = "com.mysql.jdbc.Driver"
db.default.url = "jdbc:mysql://*****?characterEncoding=utf-8&useSSL=false"
db.default.user = *****
db.default.password = *****
db.default.poolInitialSize=1
db.default.poolMaxSize=3
db.default.connectionTimeoutMillis=1000
db.default.poolConnectionTimeoutMillis=1000
db.default.poolValidationQuery="select 1 as one"
```

The last packet successfully received from the server was 173,503,396 milliseconds ago. The last packet sent successfully to the server was 173,503,402 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem. at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3743) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) at com.mysql.jdbc.ConnectionImpl.setReadOnlyInternal(ConnectionImpl.java:4984) at com.mysql.jdbc.ConnectionImpl.setReadOnly(ConnectionImpl.java:4977) at org.apache.commons.dbcp2.DelegatingConnection.setReadOnly(DelegatingConnection.java:550) at org.apache.commons.dbcp2.DelegatingConnection.setReadOnly(DelegatingConnection.java:550) at scalikejdbc.DBConnection$class.scalikejdbc$DBConnection$$setReadOnly(DBConnection.scala:93) at scalikejdbc.DBConnection$class.readOnlySession(DBConnection.scala:185) at scalikejdbc.NamedDB.readOnlySession(NamedDB.scala:17) at scalikejdbc.DBConnection$$anonfun$readOnly$1.apply(DBConnection.scala:201) at scalikejdbc.DBConnection$$anonfun$readOnly$1.apply(DBConnection.scala:201) at scalikejdbc.

**Comment by duhanmin** [comment]
but almost 1~2 days，the client throw exception

**Comment by seratch** [comment]
The behavior depends on how you configure MySQL JDBC driver and connection pool (If you're using the default one, it's commons-dbcp2 https://commons.apache.org/proper/commons-dbcp/ ).

**Comment by duhanmin** [comment]
What parameters do I need to configure to avoid this problem

**Comment by duhanmin** [comment]
> The behavior depends on how you configure MySQL JDBC driver and connection pool (If you're using the default one, it's commons-dbcp2 https://commons.apache.org/proper/commons-dbcp/ ).

What parameters do I need to configure to avoid this problem

**Comment by seratch** [comment]
I'm not able to debug your application 😅 but in general, giving `autoReconnect` a try as the error message may be helpful to eliminate the issue.
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html
