### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jxnu-liguobin** [scalikejdbc/scalikejdbc#1037]
Can't implicit be used in SQL """" """" ?

And in the absence of implicit conversion, the database type inconsistent insertion fails, but show expection the data is truncated, not the type error, which is too difficult to detect.

**Comment by seratch** [comment]
I do understand your points here but unfortunately, we don't have any ways to improve it with string interpolation. One thing I can suggest is to use Query DSL instead. With the DSLs, you won't have that problem in most cases. That's one of the major reasons I created the feature.

**Comment by jxnu-liguobin** [comment]
Okay, thank you for your reply. at present, it is not a big problem for me to belong to personal training project. It shows that the conversion can meet the demand.

**Comment by seratch** [comment]
Thanks. If you don't have further comments on this, could you close this issue?
