### ISSUE TITLE
Question of transaction

### ISSUE THREAD

**Issue by jxnu-liguobin** [scalikejdbc/scalikejdbc#1039]
My project is  coding .But I found some question.
Scalikejdbc has implemented transaction in services ？localTx can only  use  in dao？or  Can i use JPA's @transaction in services with scalikejdbc？  I think that  may need some  plugin like play ？

**Comment by seratch** [comment]
This library doesn't support transaction management using `@Transcational` annotation. 

>Scalikejdbc has implemented transaction in services ？localTx can only use in dao？

The common pattern is to accept a `DBSession` as an implicit parameter in methods.

```scala
class UserService {
  def find(id: Long)(implicit session: DBSession = DB.readOnlySession): Option[User] = {
    select.from // omitted
  }
  def register(name: String)(implicit session: DBSession = DB.autoCommitSession): Long = {
    insert.into // omitted
  }
}

val userService = new UserService()

// auto-commit
val id = userService.register("Alice")

DB.localTx { implicit session =>
  // in transaction
  val id = userService.register("Bob")
  userService.find(id) match {
    case Some(user) =>
    case _ =>
  }
}
```

**Comment by jxnu-liguobin** [comment]
Thank you for your reply.  I understand as follows:roughly speaking, sessions need to be passed in from outside when several methods use the same session, only in this way,we  can keep ACID。

**Comment by jxnu-liguobin** [comment]
Oh , if there are two update operations，autoCommitSession can't be used. I get error like:
`Failed preparing the statement (Reason: Connection is closed):` 

I think it's probably the first one that has been submitted and then closed the session.

what can I do。。

**Comment by seratch** [comment]
Can you share your minimal working example which reproduces your situation?

**Comment by jxnu-liguobin** [comment]
I think I may have found the problem. I'm using all Future operations in this
def update() {
localTx  {
    def close():Future[A] //service
     def update():Future[A]  //service
}
}


def update() {
localTx  {
    def close():A
     def update():A
}
}
It works well.
