### ISSUE TITLE
what's the db_url's structure?

### ISSUE THREAD

**Issue by Tasselmi** [scalikejdbc/scalikejdbc#1041]
hi,guys.
`ConnectionPool.singleton("jdbc:h2:mem:hello", "user", "pass")`
how I understand `jdbc:h2:mem:hello` ,  what this structure means?

`jdbc:h2:mem` is unchanged, and `hello` is the db name, right ?

**Comment by seratch** [comment]
Yes, your understanding is correct. see also: http://www.h2database.com/html/features.html#database_url

**Comment by seratch** [comment]
Please allow me to close this issue if I don't get a response from you in a few days.

**Comment by seratch** [comment]
Allow me to close this and feel free to reopen if you have things to discuss further.
