### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by jxnu-liguobin** [scalikejdbc/scalikejdbc#1045]
Excuse me, I want to know why use Scala.Collection.immutable.List in query list, but not seq? Or I haven't found it yet.and Whether there is a SQLToSeq Impl?

**Comment by xuwei-k** [comment]
You can convert to arbitrary collection class by the `collection` methods. e.g.
 
- https://github.com/scalikejdbc/scalikejdbc/blob/2d711dfb23df81a2745450d8c97e734a6e82a915/scalikejdbc-core/src/test/scala/scalikejdbc/RelationalSQLSpec.scala#L467
- https://github.com/scalikejdbc/scalikejdbc/blob/2d711dfb23df81a2745450d8c97e734a6e82a915/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala#L469-L474
- https://github.com/scalikejdbc/scalikejdbc/blob/2d711dfb23df81a2745450d8c97e734a6e82a915/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala#L897

**Comment by jxnu-liguobin** [comment]
oh thanks。
