### ISSUE TITLE
LoanPattern swallows exceptions

### ISSUE THREAD

**Issue by roeoender** [scalikejdbc/scalikejdbc#1049]
Problem relates to scalikejdbc LoanPattern.scala all versions including HEAD, but directly I tested it on 2.5.2.

I had a nasty problem that was hard to debug, because LoanPattern trait ignores any exceptions that are raised during call to "resource.close()" - it is wrapped in "ignoring(classOf[Throwable])" which swallows all exceptions.
I suggest it should at least log exception instead of ignoring it. Swallowing exceptions is bad practice and code smell which causes hard to debug problems - which was my case (took me 3 days of debugging).

Longer justification:
In my case this caused total hang of Oracle connections in application servers (Glassfish 3/ Wildfly 11) because it caused "ORA-01000: maximum open cursors exceeded", but mysteriously the same code run fine in dev environment. By debugging on server I was convinced that scalikejdbc didn't close jdbc PreparedStatement and analogous pure JDBC reimplementation of the same code run correctly.
Then I found about this "ignoring(classOf[Throwable]) apply { resource.close() }" - patched LoanPattern code to log the exception instead - and voila - close() called by the LoanPattern on StatementExecutor raised NoClassDefFoundError for joda time - this had simple solution - I simply had to add joda time jar to manifest.mf to satisfy application server's class loaders.

**Comment by seratch** [comment]
Sorry for my belated response. I agree with you. It should be improved. Are you add warn logging in the case.

**Comment by seratch** [comment]
Improved by #1053 

Thanks for your feedback!
