### ISSUE TITLE
DatabasePublisher not publishing

### ISSUE THREAD

**Issue by cuppyCup** [scalikejdbc/scalikejdbc#1050]
I am using IntelliJ's IDEA and see a message (screen shot below) that I should report a bug.

<img width="655" alt="Screen Shot 2019-09-27 at 10 25 22 AM" src="https://user-images.githubusercontent.com/7875594/65777012-30be9200-e111-11e9-9f98-1887dd192795.png">

This is from the file `SQL.scala` in scalikejdbc-core_2.13-3.3.5-sources.jar .  The stack trace is 

    map:382, SQL (scalikejdbc)
    findByFirstName:83, Person$ (com.bah.devops.common.entities)
    $anonfun$new$22:287, PersonTest (com.bah.devops.common.entities)
    apply:-1, 142103421 (com.bah.devops.common.entities.PersonTest$$Lambda$201)
    $anonfun$apply$1:132, TestSuite$TestFunAndConfigMap (org.scalatest.fixture)
    apply:-1, 1368128912 (org.scalatest.fixture.TestSuite$TestFunAndConfigMap$$Lambda$303)
    outcomeOf:85, OutcomeOf (org.scalatest)
    outcomeOf$:83, OutcomeOf (org.scalatest)
    outcomeOf:104, OutcomeOf$ (org.scalatest)
    apply:132, TestSuite$TestFunAndConfigMap (org.scalatest.fixture)
    apply:80, TestSuite$OneArgTest$$anon$1 (org.scalatest.fixture)
    withFixture:196, TestSuite (org.scalatest)
    withFixture$:195, TestSuite (org.scalatest)
    withFixture:226, FlatSpec (org.scalatest.fixture)
    $anonfun$withFixture$1:63, AutoRollback (scalikejdbc.scalatest)
    apply:-1, 903716563 (scalikejdbc.scalatest.AutoRollback$$Lambda$248)
    using:18, LoanPattern (scalikejdbc)
    using$:16, LoanPattern (scalikejdbc)
    using:21, PersonTest (com.bah.devops.common.entities)
    withFixture:57, AutoRollback (scalikejdbc.scalatest)
    withFixture$:56, AutoRollback (scalikejdbc.scalatest)
    withFixture:21, PersonTest (com.bah.devops.common.entities)
    invokeWithFixture$1:2127, FlatSpecLike (org.scalatest.fixture)
    $anonfun$runTest$1:2138, FlatSpecLike (org.scalatest.fixture)
    apply:-1, 1232703108 (org.scalatest.fixture.FlatSpecLike$$Lambda$236)
    runTestImpl:286, SuperEngine (org.scalatest)
    runTest:2138, FlatSpecLike (org.scalatest.fixture)
    runTest$:2119, FlatSpecLike (org.scalatest.fixture)
    runTest:226, FlatSpec (org.scalatest.fixture)
    $anonfun$runTests$1:2181, FlatSpecLike (org.scalatest.fixture)
    apply:-1, 62915435 (org.scalatest.fixture.FlatSpecLike$$Lambda$217)
    $anonfun$runTestsInBranch$1:393, SuperEngine (org.scalatest)
    apply:-1, 1425433685 (org.scalatest.SuperEngine$$Lambda$218)
    foreach:312, List (scala.collection.immutable)
    traverseSubNodes$1:381, SuperEngine (org.scalatest)
    runTestsInBranch:370, SuperEngine (org.scalatest)
    $anonfun$runTestsInBranch$1:407, SuperEngine (org.scalatest)
    apply:-1, 1425433685 (org.scalatest.SuperEngine$$Lambda$218)
    foreach:312, List (scala.collection.immutable)
    traverseSubNodes$1:381, SuperEngine (org.scalatest)
    runTestsInBranch:376, SuperEngine (org.scalatest)
    runTestsImpl:458, SuperEngine (org.scalatest)
    runTests:2181, FlatSpecLike (org.scalatest.fixture)
    runTests$:2180, FlatSpecLike (org.scalatest.fixture)
    runTests:226, FlatSpec (org.scalatest.fixture)
    run:1124, Suite (org.scalatest)
    run$:1106, Suite (org.scalatest)
    org$scalatest$fixture$FlatSpecLike$$super$run:226, FlatSpec (org.scalatest.fixture)
    $anonfun$run$1:2202, FlatSpecLike (org.scalatest.fixture)
    apply:-1, 1387671967 (org.scalatest.fixture.FlatSpecLike$$Lambda$210)
    runImpl:518, SuperEngine (org.scalatest)
    run:2202, FlatSpecLike (org.scalatest.fixture)
    run$:2201, FlatSpecLike (org.scalatest.fixture)
    run:226, FlatSpec (org.scalatest.fixture)
    run:99, JUnitRunner (org.scalatestplus.junit)
    run:137, JUnitCore (org.junit.runner)
    startRunnerWithArgs:68, JUnit4IdeaTestRunner (com.intellij.junit4)
    startRunnerWithArgs:47, IdeaTestRunner$Repeater (com.intellij.rt.execution.junit)
    prepareStreamsAndStart:242, JUnitStarter (com.intellij.rt.execution.junit)
    main:70, JUnitStarter (com.intellij.rt.execution.junit)

I am using these dependencies

       <dependency>
            <groupId>org.scalikejdbc</groupId>
            <artifactId>scalikejdbc-core_2.13</artifactId>
            <version>3.3.5</version>
        </dependency>
        <dependency>
            <groupId>org.scalikejdbc</groupId>
            <artifactId>scalikejdbc_2.13</artifactId>
            <version>3.3.5</version>
        </dependency>
        <dependency>
            <groupId>org.scalikejdbc</groupId>
            <artifactId>scalikejdbc-config_2.13</artifactId>
            <version>3.3.5</version>
        </dependency>
        <dependency>
            <groupId>org.scalikejdbc</groupId>
            <artifactId>scalikejdbc-streams_2.13</artifactId>
            <version>3.3.5</version>
        </dependency>
        <dependency>
            <groupId>org.scalikejdbc</groupId>
            <artifactId>scalikejdbc-test_2.13</artifactId>
            <version>3.3.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.8</version>
            <scope>test</scope>
        </dependency>

When I execute my test 

    it should "add person s and then find-by-firstname" in { implicit session: DBSession =>
      val person1: Person = Person.create(firstname1, lastname1, ssn1, email1, dob1).get
      val person3: Person = Person.create(firstname1, lastname3, ssn3, email3, dob3).get

      //    Person.findAll().foreach(println)

      val publisher1: DatabasePublisher[Person] = Person.findByFirstName(firstname1)

      Source.fromPublisher(publisher1).runForeach(println)

      val results1Future: Future[Seq[Person]] =
        Source.fromPublisher(publisher1).take(2).runWith(Sink.seq)

      val results1: Seq[Person] =
        Await.result(results1Future, Duration(5, TimeUnit.SECONDS))

      results1 should contain(person1)
      results1 should contain(person3)
    }

(when the commented out line is executed I see the correct values being printed).  I see these log messages

    2019-09-27 10:05:50,019 INFO  a.e.s.Slf4jLogger@[kka.actor.default-dispatcher-3] - Slf4jLogger started
    2019-09-27 10:05:50,798 INFO  s.s.DatabasePublisher@[kka.actor.default-dispatcher-3] - Database stream requested by subscriber: akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$$anon$1@27b94873 is ready
    2019-09-27 10:05:50,798 INFO  s.s.DatabasePublisher@[kka.actor.default-dispatcher-7] - Database stream requested by subscriber: akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$$anon$1@1935ae0e is ready
    2019-09-27 10:05:50,823 INFO  s.s.DatabaseSubscription@[kka.actor.default-dispatcher-4] - All data for subscriber: akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$$anon$1@1935ae0e has been sent
    2019-09-27 10:05:50,823 INFO  s.s.DatabaseSubscription@[kka.actor.default-dispatcher-6] - All data for subscriber: akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$$anon$1@27b94873 has been sent
    2019-09-27 10:05:50,826 INFO  s.s.DatabaseSubscription@[kka.actor.default-dispatcher-4] - Finished cleaning up database resources occupied for subscriber: akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$$anon$1@1935ae0e
    2019-09-27 10:05:50,826 INFO  s.s.DatabaseSubscription@[kka.actor.default-dispatcher-6] - Finished cleaning up database resources occupied for subscriber: akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$$anon$1@27b94873
    [ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.782 s <<< FAILURE! - in com.bah.devops.common.entities.PersonTest
    [ERROR] Person should add person s and then find-by-firstname(com.bah.devops.common.entities.PersonTest)  Time elapsed: 0.133 s  <<< ERROR!
    org.scalatest.exceptions.TestFailedException: Vector() did not contain element Person(14,FN1,LN1,000-00-0001,1@email.test.com,2019-01-02)
    	at com.bah.devops.common.entities.PersonTest.$anonfun$new$22(PersonTest.scala:298)
    	at com.bah.devops.common.entities.PersonTest.using(PersonTest.scala:21)
    	at com.bah.devops.common.entities.PersonTest.withFixture(PersonTest.scala:21)

**Comment by yoskhdia** [comment]
Could you show me the implementation code of `Person.findByFirstName` ?

**Comment by cuppyCup** [comment]
def findByFirstName(firstname: String)
                       (implicit session: DBSession = autoSession,
                        executionContext: ExecutionContext): DatabasePublisher[Person] = DB  readOnlyStream {
                withSQL {
                      select.from(Person as p).where.eq(p.firstname, firstname)
                }
               .map(Person(p))
               .iterator()
    }

**Comment by yoskhdia** [comment]
The direct cause for DatabasePublisher not returning results is because the DBSession is separate and not in the same transaction scope.

DatabasePublisher is compliant with the ReactiveStreams specification and has its own DBSession management.
In the code presented, committing the result of Persion.create will cause DatabasePublisher to return the result.

In addition, I think that the stack trace at the beginning is a test being executed, but the message is not displayed in the execution result log.
This message is specified by the SQL apply, but it seems that it is operating normally by changing to another Extractor by the map method.

- https://github.com/scalikejdbc/scalikejdbc/blob/dcf4774dea3752f15ec414bc20d2017ef2807ac8/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala#L48-L49
- https://github.com/scalikejdbc/scalikejdbc/blob/dcf4774dea3752f15ec414bc20d2017ef2807ac8/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala#L875-L877

**Comment by seratch** [comment]
@cuppyCup This is a bit old issue but did @yoskhdia's answer help you out? Let me close this issue after waiting for your response for a few weeks.
