### ISSUE TITLE
Write traffic from multiple services to a clustered SQL server is unfairly distributed

### ISSUE THREAD

**Issue by jung-kim** [scalikejdbc/scalikejdbc#1059]
scalikejdbc@3.2.1
scala@2.12.5

Hi, 

We consistently maintain 48 counts of a simple services that it's sole purpose in life is to use scalikejdbc to write to a SQL server end point.  That end point is actually a route 53 end point that is pointing to 5 different SQL databases.  (It's the memsql aggregators, but it shouldn't matter)

Problem is that 48 services' SQL write traffics should be spread across evenly to 5 different SQL servers but it seems that it is unfairly congregated to few servers, unpredictably.

<img width="1243" alt="Screen Shot 2019-11-22 at 16 29 20" src="https://user-images.githubusercontent.com/5281068/69469584-74ff9480-0d46-11ea-9c50-3d628b3c713f.png">

Our usage (roughly as it's a company code):
```scala
  val settings = ConnectionPoolSettings(
    initialSize = 30,
    maxSize = 120,
    connectionTimeoutMillis = 3.seconds.toMillis,
    validationQuery = "select 1")

  ConnectionPool.add(
    "A_NAME",
    s"$ROUTE_53_ENDPOINT?$SOME_OPTIONS",
    "UN",
    "PW",
    settings
  )

while(true) {
  val data = (pull from a source)
  val conn = ConnectionPool.borrow("A_NAME")
  val stmt = conn.prepareStatement("SQL_HEADER")
  stmt.setQueryTimeout(1.seconds)
  
  try {
  stmt.setInt(data)
  ...
  stmt.addBatch()
  } catch {
    ....
  } 
  stmt.release()
  conn.close()
}
```

I've suspected DNS cache so I've tried [these methods](https://stackoverflow.com/questions/1256556/how-to-make-java-honor-the-dns-caching-timeout).  
- `java.security.Security.setProperty("networkaddress.cache.ttl", "<value>");` in code
- `-Dnetworkaddress.cache.ttl=0` at spawn

But neither of them worked.  

It is possible that our usage case is unique but is there a config or settings that I'm missing?  
Or is it that I'm completely misusing the library?

**Comment by seratch** [comment]
I don't think ScalikeJDBC is a cause of your problem.

It looks like an issue of database server-side, including DNS and internal load balancing. Also, each database node may need more capacity to handle peak write traffics for safety.

If it were to be a client-side issue, the behavior depends on the implementation of your JDBC driver and connection pool library. If you try others on the client-side, you can switch its connection pool to another like HikariCP (FYI: ScalikeJDBC uses commons-dbcp2). I don't think you have other options for JDBC driver.

**Comment by jung-kim** [comment]
Ah... what is the reasoning for suspecting the server side?

Assuming `ConnectionPool.borrow("A_NAME")` returns a new connection and DNS caching is disabled, it should evenly distribute traffic across multiple instances but it doesn't.

If the question is that DNS or the loadbalancer misbehaving, I don't think that is accurate as given same setup scalikejdbc is the only library that exhibit this behavior

**Comment by seratch** [comment]
First of all, I don't think ScalikeJDBC is not the cause of your issue as `ConnctionPool.borrow(...)` in the default implementation does only calling commons-dbcp2's method like this:
https://github.com/scalikejdbc/scalikejdbc/blob/3.4.0/scalikejdbc-core/src/main/scala/scalikejdbc/Commons2ConnectionPool.scala

Let's break down the problem. Can you do the same test without ScalikeJDBC? That means running the same experiment with only our JDBC driver and commons-dbcp2 (or other connection pool library like HikariCP).

If you see the problem only when having ScalikeJDBC in the code, we can say ScalikeJDBC has something to improve. Otherwise, digging deeper on this issue may be out of scope.

**Comment by jung-kim** [comment]
Hmm, I was under the impression that `ConnctionPool.borrow(...)` is a library specific one rather than a common method.

You are absolutely right, I will need to dive in and try to see if we can narrow down the culprit but this is tricky as this is a very high throughput application and need to expose new methods carefully.  (~480k upserts per second)

**Comment by jung-kim** [comment]
Due to the default nature of LIFO for `org.apache.commons.pool2.impl.GenericObjectPool.borrow()`, and `connection.close()` in here doesn't actually closes JDBC connection, rather mark connection as usable by another thread, we have arrived at the conclusion that we cannot use `Commons2ConnectionPool`.  

That being said, I think below document can be clearer by saying "instance always closes its connection object and return it to connection object pools all the while JDBC connection is alive".

> By default, scalikejdbc.DB or scalikejdbc.NamedDB instance always closes its connection (= releases and returns it to connection pools).  (http://scalikejdbc.org/documentation/connection-pool.html)

---

On hind sight, it is absolutely my fault for expecting underlying JDBC connections to be close from DB when connection pool is used.  If this was true concept of connection pool is no different from creating intermittent connections on demand.
