### ISSUE TITLE
Does scalikejdbc support QueryDSL in Sub-query Select clause?

### ISSUE THREAD

**Issue by anlac-home** [scalikejdbc/scalikejdbc#1060]
Hi,
I use Scala, scalikejdbc and Mysql for my project.
Does scalikejdbc support sql like this:
`select user.*, (select user_history.content from user_history where user.id = user_history.user_id order by user_history.id desc limit 1) as uh_content from user where (....) order by user.id desc limit 2 offset 0;`
I read [http://scalikejdbc.org/documentation/query-dsl.html](url) - Sub-query, I try doing like this but doesn't successful.
Anyone can help me?
Thanks so much.

**Comment by seratch** [comment]
No, it's not possible to write such queries only with Query DSL at this moment. You can go with `append` to have anything in a query like this:
```scala
select(u.result.*, sqls"{your subquery} as uh_content").from(User as u).where...
```

**Comment by anlac-home** [comment]
Thanks you so much @seratch .
