### ISSUE TITLE
Exception with redshift driver 1.2.15+ ([Amazon][jdbc][11760] Cannot call setReadOnly)

### ISSUE THREAD

**Issue by YannMoisan** [scalikejdbc/scalikejdbc#1061]
Hello,

We are using scalikejdbc with the official Redshift driver

This code works with version 1.2.14.1022 but not with 1.2.15.1025, because the following exception is thrown :

```
java.SQL.Exception  [Amazon][jdbc][11760] Cannot call setReadOnly while Connection is in a transaction.
```

```
import java.sql.DriverManager
import java.util.Properties

object RedshiftTest extends App {
  val x: Class[_] = Class.forName("com.amazon.redshift.jdbc42.Driver")
  val properties  = new Properties
  val _1          = properties.setProperty("user", "buying_engine")
  val _2 = properties.setProperty(
    "password",
    "xxx"
  )
  val conn = DriverManager.getConnection(
    "jdbc:redshift://bi.cdnawe1okeyj.eu-west-1.redshift.amazonaws.com:5439/datamarts",
    properties
  )

  conn.setAutoCommit(false)
  conn.setReadOnly(false)
}
```

This code mimics what happens here : https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-core/src/main/scala/scalikejdbc/Tx.scala#L38

Do you think it's possible to switch calls to `setAutoCommit` and `setReadOnly` in the `begin` method ?

**Comment by seratch** [comment]
How about enabling `jtaDataSourceCompatible` in advance? The new behavior seems to look like JTA.

```scala
GlobalSettings.jtaDataSourceCompatible = true
```

**Comment by YannMoisan** [comment]
Thanks a lot. It works while activating this flag !

**Comment by seratch** [comment]
Good to know! Allow me to close this issue now.
