### ISSUE TITLE
Stored Procedure with sql interpolation

### ISSUE THREAD

**Issue by larstoc** [scalikejdbc/scalikejdbc#1062]
I have the following stored procedure in psql mean to truncate the database (as I could not find support for that in scalikeJDBC):

```
CREATE OR REPLACE FUNCTION truncate_tables() RETURNS void AS $$
DECLARE
    statements CURSOR FOR
        SELECT tablename FROM pg_tables
        WHERE schemaname = 'public';
BEGIN
    FOR stmt IN statements LOOP
        EXECUTE 'TRUNCATE TABLE ' || quote_ident(stmt.tablename) || ' CASCADE;';
    END LOOP;
END;
$$ LANGUAGE plpgsql;
```

But I can't seem to find a way to use this with sql interpolation. I have tried different variations of:

```
  def truncateDatabase(implicit session: DBSession): Try[Unit] = {
    val sql = sqls"perform truncate_database()".update.apply()
  }
```

But I can't seem to find a way. Is this supported at all? Or Am I just blind? Thankful for all help!

**Comment by seratch** [comment]
Unfortunately, `CallableStatement` is unsupported (see also: https://github.com/scalikejdbc/scalikejdbc/issues/438 https://github.com/scalikejdbc/scalikejdbc/issues/380)

The only thing I can suggest at the moment is to use the JDBC APIs directory.
https://jdbc.postgresql.org/documentation/94/callproc.html

**Comment by seratch** [comment]
I'd like to use #438 for tracking the progress for the CallbaleStatement feature request. Let me close this issue.
