### ISSUE TITLE
[GoogleBigQuery JDBC Driver]The current database does not support transactions

### ISSUE THREAD

**Issue by debasishhalder** [scalikejdbc/scalikejdbc#1063]
I'm getting below exception when trying to get connection through google service account using google bigquery progress driver. 

`2019-12-11T10:43:33,327 ERROR SecureExceptionHandlerImpl,http-apr-8080-exec-7:116 - Cannot get a connection, pool error Could not create a validated object, cause: [TibcoSoftware][GoogleBigQuery JDBC Driver]The current database does not support transactions.`

**Comment by seratch** [comment]
Can you try to directly use your JDBC driver first? If you don't see any problems in the case and still have issues only when connecting via ScalikeJDBC, we may be able to address your issue in some ways.

**Comment by seratch** [comment]
Let us close this issue due to inactivity. Feel free to create another issue or reopen this as necessary.
