### ISSUE TITLE
reverse engineering tool - column name with multiple underscores

### ISSUE THREAD

**Issue by sjoshi-nova** [scalikejdbc/scalikejdbc#1074]
_Scala 2.13
ScalikeJDBC 3.4.0
Database: MS SQL Server
Error: scalikejdbc.InvalidColumnNameException: Invalid column name. (name: af.safe_mode23, registered names:..._

A Column name with multiple underscores like SAFE_MODE2_3 gets translated to safeMode23 in the generated files. It only puts back the first underscore for query. 
The problem is fixed by renaming all instances of the string safeMode23 with safeMode2_3.

**Comment by seratch** [comment]
Fixed by #1114
