### ISSUE TITLE
scalikejdbc.SQLSyntaxSupportFeature.SQLSyntaxSupport#columns Support implicit ConnectionPool

### ISSUE THREAD

**Issue by aiyanbo** [scalikejdbc/scalikejdbc#1076]
I use a multi-database in my project. I did not init default pool when calling scalikejdbc.SQLSyntaxSupportFeature.SQLSyntaxSupport#columns function. But init other pool.

```
    def columns: collection.Seq[String] = {
      if (columnNames.isEmpty) {
        SQLSyntaxSupportFeature.SQLSyntaxSupportLoadedColumns.getOrElseUpdate((connectionPoolName, tableNameWithSchema), {
          NamedDB(connectionPoolName, settings).getColumnNames(tableNameWithSchema, tableTypes).map(_.toLowerCase(en)) match {
            case Nil => throw new IllegalStateException(
              "No column found for " + tableName + ". If you use NamedDB, you must override connectionPoolName.")
            case cs => cs
          }
        })
      } else columnNames
    }
```
It will be change to 

```
    def columns(implicit cp: ConnectionPool): collection.Seq[String] = {
      if (columnNames.isEmpty) {
        SQLSyntaxSupportFeature.SQLSyntaxSupportLoadedColumns.getOrElseUpdate((connectionPoolName, tableNameWithSchema), {
          DB(cp.borrow(), settings).getColumnNames(tableNameWithSchema, tableTypes).map(_.toLowerCase(en)) match {
            case Nil => throw new IllegalStateException(
              "No column found for " + tableName + ". If you use NamedDB, you must override connectionPoolName.")
            case cs => cs
          }
        })
      } else columnNames
    }
```
NamedDB --> DB(ConnectionPool.borrow)

**Comment by seratch** [comment]
The default DB is also a NamedDB with the default name. If your code doesn’t work for some reasons, I recommend verifying your configuration.

**Comment by aiyanbo** [comment]
> The default DB is also a NamedDB with the default name. If your code doesn’t work for some reasons, I recommend verifying your configuration.

I'm not using default DB with the default pool name. This is my steps:
1. Put a named data source into ConnectionPool by the method: `ConnectionPool.add(name, ds)`
2. Create DB session from `DB(ConnectionPool.get(name).borrow)`
3. Using `SQLSyntaxSupport.column` get table's column information (I't will throw default pool not init exception)

I mean is: When calling the method `SQLSyntaxSupport.column`, not use default pool, I't can be using `SQLSyntaxSupport.column(implicit cp: ConnectionPool)`

Solution:
1. Override `connectionPoolName` in `SQLSyntaxSupport` object. Like this:
```
object ATable extends SQLSyntaxSupport[A] {

  override def tableName: String = "a"

  override def connectionPoolName: Any = "a"

}
```
But I want not to do this. Because of the `connectionPoolName` may be changed by an injector.

**Comment by seratch** [comment]
For this, overriding `connectionPoolName` is the only way to properly configure the objects that inherit `SQLSyntaxSupport`. Consider creating instances runtime or defining multiple objects in accordance with your connection pools.

**Comment by seratch** [comment]
As I've already provided an answer here, let me close this issue now. If you have any further comments/questions here, please feel free to write in.
