### ISSUE TITLE
SQL string interpolation before execution

### ISSUE THREAD

**Issue by khagaydv01** [scalikejdbc/scalikejdbc#1077]
Hello!
I am trying to do the following:

     // newer: String
     // older: String
     // query: Long,
     // diff: String,
    // diff: String

    val preStatement =
        "INSERT INTO diff (newer ,older ,query ,diff ,diff) " +
          s"VALUES ($newer,$older, $query, $diff, $diff)"

      val statement = sql"$preStatement"
      statement.stripMargin.execute().apply()
     
     but, I get 
     org.postgresql.util.PSQLException: ERROR: syntax error at or near "$1"

    However, the following query works
     /*      val statement = sql"""
    INSERT INTO diff (
    newer,
    older,
    query,
    diff,
    diff
    ) VALUES (
    $newer,
    $older,
    $query,
    $diff,
    $diff
    )"""*/

**Comment by seratch** [comment]
Use `SQLSyntax.createUnsafely` for it. As its name shows, it's risky to embed external parameters.
