### ISSUE TITLE
Does scalikejdbc support QueryDSL alias column name?

### ISSUE THREAD

**Issue by anlac-home** [scalikejdbc/scalikejdbc#1078]
Hi, I am using scalikejdbc with MySql.
Does scalikejdbc support sql like this:
```sql  SELECT COUNT(user.id) as quantity, SUM(user.salary) as salary FROM user WHERE ... ```
I using .append() to solve it:
```scala
withSQL {
      select(
        sqls"${count(user.id)} quantity",
        sqls"${sum(user.salary)} salary")
        .from(user as u)
        .where() ...
    }
``` 
I got correct result. But I really want to beautify with QueryDSL. Does scalikejdbc support QueryDSL like this: 
```scala
withSQL {
      select(count(user.id) as quantity, sum(user.salary) as salary)
        .from(user as u)
        .where() ...
    }
``` 
Thanks so much?

**Comment by seratch** [comment]
Hello, thanks for writing in! Unfortunately, your workaround is the only way to do that so far.

**Comment by anlac-home** [comment]
Thanks @seratch .
