### ISSUE TITLE
DB localTx not rolling back upon encountering an exception

### ISSUE THREAD

**Issue by uneewk** [scalikejdbc/scalikejdbc#1081]
I have this code block:
```
...
DB localTx {
  addDataset(dataset)   // Add the dataset
  polygonRepository.addPolygons(polygons) // Add corresponding polygons
}

```
In my case the second function fails and throws an exception. My expectation is that the result of the first function _addDataset(dataset)_ is rolled back. However this is not happening i.e. the result is committed. Am I misunderstanding the use of DB localTx? How should I code it if my desire is for all or nothing in this block?

**Comment by seratch** [comment]
To join a transaction, the methods need to use the same `DBSession`. A common way to propagate is to use an implicit parameter as below.

```scala
DB localTx { implicit sesson =>
  addDataset(dataset)   // Add the dataset
  polygonRepository.addPolygons(polygons) // Add corresponding polygons
}
def addDataset(dataset: Dataset)(implicit session: DBSession): Unit { ... }
```

**Comment by uneewk** [comment]
Hmm still not having success.

```Scala
private def addDataset(dataset: Dataset)(implicit s: DBSession): Int = { ... }

def addDatasetWithPolygons(dataset: Dataset, polygons: Seq[Polygon]): String = {
    if (polygons.isEmpty) {
      DB localTx { implicit session => addDataset(dataset) }
    } else {
      DB localTx { implicit session =>
        addDataset(dataset)
        polygonRepository.addPolygons(polygons)(session)
      }
    }
    dataset.id
}

```
Could it be because _addPolygons(polygons)_ is in a different class which has session defined implicitly? There I have the following:

```Scala
class PolygonRepository(...) {
   private implicit val session: AutoSession.type = AutoSession
   ...
   def addPolygons(polygons: Seq[Polygon])(implicit s: DBSession = session): Int = {
    ...
  }
}
```

**Comment by seratch** [comment]
Ah yeah, you should remove it.

**Comment by uneewk** [comment]
Still failed but I figured out part of my problem. First the driver I am using has AutoCommit turned on by default. I had to turn this off. The I run into and issue when I call `DB localTx()` I get a `Cannot start a new transaction` error and that's because by default in ScalikeJDBC `jtaDataSourceCompatible` is set to false. I'd like to enable this.

**Comment by uneewk** [comment]
All squared away and working. Thanks for your help.
