### ISSUE TITLE
Support other NoSQLDB 

### ISSUE THREAD

**Issue by choupijiang** [scalikejdbc/scalikejdbc#1083]
wish support more database such as mongoDB,Clickhouse ...

**Comment by seratch** [comment]
Sorry for my slow response here. Unfortunately, I don't have any plans to supports other databases. 

One thing I can say related to this is that if databases you use have their JDBC drivers and they don't work with ScalikeJDBC, we may be able to support some use cases. For instance, although this library "officially" doesn't support the Oracle database, it has some particular logic specific to the database.
