### ISSUE TITLE
Replacing connection pool many times in a short time period

### ISSUE THREAD

**Issue by apiwoni** [scalikejdbc/scalikejdbc#1084]
When ConnectionPool.add() is invoked multiple times for the same named pool and before ConnectionPool.isInitialized returns true then connections created can exceed maximum pool size, that is maximum pool size x pool instances created for the same named pool.

Under heavy initial load with maximum configured pool size of 30 connections this bug lead to creation of 240 connections.
I'm using HikariDataSource for ConnectionPool.add(), so actual HikariPool is created when ConnectionPool invokes HikariDataSource.getConnection. The problem is with scalikejdbc.ConnectionPool#add method that synchronizes on pool and blocks for 100 ms without any good explanation.
To reproduce this issue I made multiple requests to ConnectionPool.add("poolName", new DataSourceConnectionPool(new HikariDataSource)) spaced 100 ms apart to allow first request exit from blocking ConnectionPool.add, invoke NamedDB("poolName") to realize connection, and allow next call to replace realized pool, exit add method, and request new connection from new pool and so on.

I do not even want to mention scalikejdbc.ConnectionPool#abandonOldPool called fromscalikejdbc.ConnectionPool#add which throws UnsupportedOperationException when ConnectionPool.numActive and ConnectionPool.close is invoked. Totally useless but luckily scalikejdbc.ConnectionPool#abandonOldPool  executes on small dedicated thread pool.

Basically, I don't see a way to shutdown pool because how scalikejdbc.ConnectionPool#abandonOldPool is written.

```scala
  def add(name: Any, dataSource: AuthenticatedDataSourceConnectionPool) = {
    // NOTE: cannot pass ExecutionContext from outside due to overload issue
    // (multiple overloaded alternatives of method add define default arguments.)
    val oldPoolOpt: Option[ConnectionPool] = pools.get(name)
    // register new pool or replace existing pool
    pools.synchronized {
      pools.update(name, dataSource)
      // wait a little because rarely NPE occurs when immediately accessed.
      Thread.sleep(100L)
    }
    // asynchronously close the old pool if exists
    oldPoolOpt.foreach(pool => abandonOldPool(name, pool))
  }
```

Scenario for adding new data source under same connection pool name:
1. first call to ConnectionPool.add() is at Thread.sleep(100)
2. N callers are blocked at pools.synchronized with oldPoolOpt being pool from first call
3.  first caller exits
4. all subsequent callers enter every 100 ms
5. when all subsequent callers exit pools.synchronized abandonPoolName(firstCallPool)

What happened to N-2 created pools, excluding first and last? Gone without any means to shut them down unless caller has a reference to original DataSource to call close(). So even if I override DataSourceConnectionPool.close(), which currently throws UnsupportedOperationException, N-2 pools with connections are dangling there!

Potential solution may be to synchronize get and update, re-evaluate 100 ms blocking call (likely because of differences in DataSource/pool implementations),  fix abondonOldPool and implement ConnectionPool.close() as opposed to throwing UnsupportedOperationException.

**Comment by apiwoni** [comment]
Quick observation here on inconsistency, ConnectionPools.add(name: Any, url: String, user: String, password: String, settings: CPSettings = ConnectionPoolSettings()) does have pools.get and pools.update inside of pools.synchronized unlike DataSourceConnectionPool based signatures.

**Comment by seratch** [comment]
Hello, thank you for taking the time to write in here and I'm sorry for my late response.

I'm not sure what the scenario you need to call `ConnectionPool#add` many times in a short time period looks like yet, but, with the given circumstances, the current implementation works as you described.

Needless to say to you, the purpose of the code is to achieve all of the following at the same time.
* never block the `ConnectionPool#add` method call
* allow new connection acquisition to use the new connection pool immediately
* safely wait for the completion of ongoing connections in the old connection pool

Some may call it a connection leaking issue but I was not able to come up with any other idea for it at the time.

Do you have something better in mind? I'm happy to improve the implementation as long as we don't break backward compatibility. If you have a completely different idea, having another ConnectionPool classes is an option.

**Comment by seratch** [comment]
As I replied above, the situation seems to be specific to aiwoni's use case and my understanding is that the connection pool refreshing logic works as we expect. Let me close this issue but please feel free to write in if you have something further to discuss regarding this.
