### ISSUE TITLE
Does scalikejdbc support querry paging and get total in one time?

### ISSUE THREAD

**Issue by KingHO2359** [scalikejdbc/scalikejdbc#1085]
Hi,
I use Scala, scalikejdbc and Mysql for my project.
I have a query with paging like that:
~~~sql
select.from(User as u).where(condition).limit(valueLimit).offset(valueOffset)
 ~~~
and I get total with query:
~~~sql
select(sqls.count).from(User as u).where(condition)
 ~~~
My condition is complex, so I want to merge 2 query for duplicate code problem and performance (table User is too large).
Anyone can give me some ideas?
Thanks so much.

**Comment by seratch** [comment]
Hello, I'm not what the complexity your app has is yet but probably you want to dynamically build the `condition` in accordance with user inputs or external parameters, right? If so, take a look at `sqls toAndConditionOpt` and `sqls toOrConditionOpt`. All you need to do is just making a list of `Option[SQLSyntax]`.

https://github.com/scalikejdbc/scalikejdbc/blob/3.4.1/scalikejdbc-interpolation/src/test/scala/scalikejdbc/QueryInterfaceSpec.scala#L249-L251

It's not realistic to merge the row fetching query and counting query as they have different types of outputs (object/result set vs long).

**Comment by seratch** [comment]
> supporting query paging and get total in one time?

Ah, sorry. I missed the title. No, it doesn't.

**Comment by KingHO2359** [comment]
Thank you so very much.
Have a nice day :)
