### ISSUE TITLE
Issue migrating scalatest 3.0.8 => 3.1.1 with scalikejdbc 3.4.1

### ISSUE THREAD

**Issue by bluesheeptoken** [scalikejdbc/scalikejdbc#1086]
I am currently migrating `scalatest` from 3.0.8 to 3.1.1 with `scalikejdbc` 3.4.1.

For autorollbacking, I import the trait `AutoRollback`

```scala
import scalikejdbc.scalatest._

import org.scalatest.flatspec.FixtureAnyFlatSpec
import org.scalatest.matchers.should.Matchers

class FooTest extends FixtureAnyFlatSpec with AutoRollback with Matchers {}
```

This currently gives the following error: 
> package.FooTest *** ABORTED *** (1 second, 308 milliseconds)
java.lang.NoSuchMethodError: scalikejdbc.scalatest.AutoRollback.withFixture$(Lscalikejdbc/scalatest/AutoRollback;Lorg/scalatest/FixtureTestSuite$OneArgTest;)Lorg/scalatest/Outcome;

Which seems weird because `scalikejdbc` 3.4.1 seems compatible with `scalatest` 3.1.1

Any hint for where the error might come from ?

**Comment by seratch** [comment]
This seems to be due to the binary incompatibility between scalatest 3.0.x and 3.1.x. You cannot use scalikejdbc 3.4.x with scalatest 3.1x. The next minor version - scalikejdbc 3.5.x will be compatible with scalatest 3.1.x. We haven't decided when to release scalikejdbc 3.5.0 yet.

**Comment by bluesheeptoken** [comment]
Thank you for the fast and complete answer @seratch !
