### ISSUE TITLE
localtx is not throwing exception and not reverting.

### ISSUE THREAD

**Issue by swapna-pg** [scalikejdbc/scalikejdbc#1092]
I am using ScalikeJDBC 3.4.0 and exasolDB and I have the following code:
```
DB localTx { implicit session => 
sql"insert into table emp(1, "emp1")".execute.apply() 
sql"insert into table emp(2, "emp2")".execute.apply() 
sql"insert into table emp(1, "emp1")".execute.apply() 
}
```
Currenlty the PK violation exception is swallowed and logged as a warning. And first two rows are inserted into DB.
Is there way to catch this exception and revert the transaction.

**Comment by swapna-pg** [comment]
Using batch statements instead of localTx is working:
```
DB localTx { implicit session => 
      val statement = session.connection.createStatement()
      statement.addBatch("insert into table emp(1, 'emp1')")
      statement.addBatch("insert into table emp(2, 'emp2')")
      statement.addBatch("insert into table emp(1, 'emp1')")
      statement.executeBatch() 
}
```

**Comment by seratch** [comment]
Do you mean this one? https://github.com/exasol/docker-db

Unfortunately, we don't support their JDBC driver. If you have some suggestions to properly support the JDBC driver and help us by doing QA tests, we may be able to take some actions.

For instance, this project doesn't run any tests with Oracle DB, and Heroku environment. But this library has some code specific to those as we got requests and supports from the community.

**Comment by seratch** [comment]
Do you have anything further to discuss here? Let me close this issue after waiting for your response for a few weeks.

**Comment by swapna-pg** [comment]
@seratch I could help with the QA tests.

**Comment by seratch** [comment]
Thank you very much for offering that! However, I myself do not have the bandwidth to work on this. If someone can make efforts on this, I'm happy to be a pull request reviewer.

**Comment by seratch** [comment]
As the owner of this project, I'm not prioritizing this feature request. Let me close this issue now.

If someone really need the support for the database, please consider folking this project or feel free to reuse some code under the Apache License.
