### ISSUE TITLE
Getting error An I/O error occurred while sending to the backend when running very long queries

### ISSUE THREAD

**Issue by alexklibisz** [scalikejdbc/scalikejdbc#1100]
Hi, I'm using scalikejdbc 3.4.2 with postgres and the following config:
```
db {
  default {
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
    driver = "org.postgresql.Driver"
    url = ${?DB_URL}
    poolInitialSize = 1
    poolMaxSize = 4
    poolConnectionTimeoutMillis = 250
    poolValidationQuery = "select 1 as one"
    poolFactoryName = "commons-dbcp2"
  }
}
```

In some cases my app runs queries containing a long `IN` clause, e.g. `select foo from bar where id in (1,22,33,44.....10000)`.
The table in question contains tens of millions of items, so the ids are typically longer and not in sorted order, but that's the general shape of the query.
I've noticed that after the clause reaches ~4000 items, I start seeing this error:

```
An I/O error occurred while sending to the backend.
```

When I run the same query using `psql -f the_same_query.sql`, it works fine. 
The only indication I see in the database logs is `LOG:  incomplete message from client`

So it seems like there is something going on at the scalikejdbc/jdbc level, hopefully just a configuration that I need to set correctly. I've looked through the docs and other issues but don't see anything helpful so far. I appreciate any tips you might have.

**Comment by alexklibisz** [comment]
I think this might actually be related: https://stackoverflow.com/questions/41204543/java-postgresql-error-on-large-query-an-i-o-error-occurred-while-sending-to-the
Will try and post back.

**Comment by seratch** [comment]
Thanks for reporting this. Yes, this sounds like an issue around the JDBC driver. Probably, there is nothing we can do on our end for helping you out.

**Comment by alexklibisz** [comment]
Hey, sorry I forgot to follow up :facepalm: 

The linked SO answer ended up helping. Specifically:
> The maximum number of parameters the JDBC driver can pass to the backend is 32767.

So if you have an IN clause with thousands of entries, each entry ends up converted to a parameter, and you get this IO error. It's not a particularly useful error message. 
We ended up writing a simple helper method and using it where we were generating a query with a potentially long IN clause:

```
def inLongList(col: String, nums: Seq[Int]): SQLSyntax = {
    val numsStr = s"( ${nums.mkString(",")} )"
    sqls"${createUnsafely(col)} in ${createUnsafely(numsStr)}"
}
```

Using `createUnsafely(numsStr)` makes the entire IN clause a single JDBC parameter instead of `nums.length` parameters, and then everything works fine.
Hopefully this helps someone in the future!
