### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by capacman** [scalikejdbc/scalikejdbc#1105]
Hi,
In "#Working with IO monads" section of transaction doc it says:
 ```scala
def finishTx(result: MyIO[A], tx: Tx): MyIO[A] = {
    result.attempt.flatMap {
      case Right(_) => MyIO(tx.commit()).flatMap(_ => result)
      case Left(_) => MyIO(tx.rollback()).flatMap(_ => result)
    }
  }
```

but when i implement with ZIO it causes result to run twice,one for attempt and then we are returning result again from flatmap. I implemented it like this(in zio it is different for your MyIO example it should be like this) and now it is working:

```scala
def finishTx(result: MyIO[A], tx: Tx): MyIO[A] = {
    result.attempt.flatMap {
      case Right(a) => MyIO(tx.commit()).flatMap(_ => MyIO(a))
      case Left(e) => MyIO(tx.rollback()).flatMap(_ => MyIO(throw e))
    }
  }
```

**Comment by seratch** [comment]
Thanks for reporting this. I haven't checked this yet but the actual working example exists in the tests. https://github.com/scalikejdbc/scalikejdbc/blob/86cbb140a7e6f495d22e0b4e315f0df7103f9101/scalikejdbc-core/src/test/scala/scalikejdbc/iomonads/MyIO.scala#L38-L43

If anyone is interested in checking this issue, it'd be appreciated.
