### ISSUE TITLE
Are connections lazily established ?

### ISSUE THREAD

**Issue by jahan01** [scalikejdbc/scalikejdbc#1107]
Hello, Just started to play around with this awesome library today. I have some questions. Are the real connection to DB is lazily established? If yes, is there a way see (in the logs) when actual connection is established ?

Also is there a way to see which connection from the pool was used to run a query ?

**Comment by seratch** [comment]
All connections are managed by a connection pool. The behavior depends on a connection pool's implementation and your configurations. 

If you use initial size 1 along with max size 10, only one connection is established in the beginning. The timing to establish the other nine connections depends on how you use the connection pool. Also, the timing to abandon idle connections will be determined on the connection pool side.

Check the documentation of the connection pool you use. The default one is commons-dbcp2: https://commons.apache.org/proper/commons-dbcp/
