### ISSUE TITLE
Access additional public methods from JDBC drivers

### ISSUE THREAD

**Issue by jahan01** [scalikejdbc/scalikejdbc#1108]
Some drivers provide more public methods than specified by the JDBC interface. It would be nice to have a way to access these methods.

For example [hive driver](https://github.com/apache/hive/blob/04167704772828b37ed749e2a098d6d8a6838bf2/jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java#L700) provides `getQueryLog`, `getQueryId` and `getYarnATSGuid` public methods on `java.sql.Statement` implementation which provides some additional metadata about executed query, which is very useful. And I am certain that there are few other drivers which should be exposing additional public methods than specified by JDBC interface

Currently only way that I figured to call these methods is by using connection object directly to prepare the statement of your own. But this loses all the niceties provided by scalike like logging, tags etc.
```scala
using(ConnectionPool.borrow()) { conn =>
  val stmt = conn.createStatement()
  val ds = stmt.asInstanceOf[DelegatingStatement]
  val hs = ds.getInnermostDelegate.asInstanceOf[HiveStatement]

  val recordCnt = stmt.executeUpdate(sql.statement)
  
  println(hs.getQueryLog)
  println(hs.getQueryId)
  println(hs.getYarnATSGuid)
  stmt.close()
}
```

One way I was trying get it working was like below but failed because `DBConnectionAttributesWiredPreparedStatement` is a private class:

 ```scala
DB autoCommit { implicit session =>
  val executor = session.toStatementExecutor(sql.statement, sql.parameters)
  val resultSet = executor.executeQuery()
  
  println(executor.underlying.getClass()) // DBConnectionAttributesWiredPreparedStatement
  val actualPreparedStmt = executor.underlying // type of java.sql.PreparedStatement

  // below cast throws an exception as DBConnectionAttributesWiredPreparedStatement is a private class
  val preparedStmt = executor.underlying.asInstanceOf[DBConnectionAttributesWiredPreparedStatement] 

  // if above cast has worked, it would be possible to have cast into DelegatingPreparedStatement or HivePreparedStatement
  val ds = preparedStmt.asInstanceOf[DelegatingPreparedStatement]
  val hs = ds.getInnermostDelegate.asInstanceOf[HivePreparedStatement]
  println(hs.getQueryLog)
  
  executor.underlying.close()
}
```
Hiding the information about implementation class(`DBConnectionAttributesWiredPreparedStatement`) doesn't seem to be right.

I don't know what would be the best approach but would like to have some flexibility to access these members.

**Comment by seratch** [comment]
I don't get your point here yet. Does not the following code work?

```scala
val stmt = executor.underlying // type of java.sql.PreparedStatement
val ds = stmt.asInstanceOf[DelegatingPreparedStatement]
val hs = ds.getInnermostDelegate.asInstanceOf[HivePreparedStatement]
```

If this works, I don't understand the reason why you see the necessity to access `DBConnectionAttributesWiredPreparedStatement` class.

**Comment by jahan01** [comment]
> ```scala
> val ds = stmt.asInstanceOf[DelegatingPreparedStatement]
> ```

This doesnt work. It fails with 
```
Exception in thread "main" java.lang.ClassCastException: class scalikejdbc.DBConnectionAttributesWiredPreparedStatement cannot be cast to class org.apache.commons.dbcp2.DelegatingPreparedStatement (scalikejdbc.DBConnectionAttributesWiredPreparedStatement and org.apache.commons.dbcp2.DelegatingPreparedStatement are in unnamed module of loader 'app')
```

So before casting to `DelegatingPreparedStatement` it will have to cast to `DBConnectionAttributesWiredPreparedStatement` which is actual class of `executor.underlying`.

**Comment by seratch** [comment]
Thanks. Now I understand what the issue you're facing is. It's pretty easy to make the class public, and I'm fine with it.

However, down-casting is not a recommended practice in general. I feel this may not be the right direction for your apps. Instead of down-casting, implementing an optimal Scala solution for Hive JDBC driver sounds like a far better solution to me. If you're interested in your own solution for it, feel free to reuse any of this library for it.

If you really want to down-cast scalikejdbc objects, I can work on a new patch release when I have time.

**Comment by jahan01** [comment]
If making `DBConnectionAttributesWiredPreparedStatement` public is not much of an issue, then I would prefer it.

My scala skills are not that great but if it as simple as removing private keyword, I can file a PR and test it.

**Comment by seratch** [comment]
Let me close this issue due to inactivity (and after checking this issue, I don't think we should proactively take action for this). But please feel free to write in if someone has anything further.

**Comment by jahan01** [comment]
@seratch My main requirement is to access additional methods offered by some drivers which is not part of standard JDBC `Statement` / `PreparedStatement` interface and not the ability to downcast. If you could suggest any other way to achieve this without down casting, that would be very very helpful.
