### ISSUE TITLE
Support hikariCP ConnectionPool

### ISSUE THREAD

**Issue by zJiaJun** [scalikejdbc/scalikejdbc#1109]
wish support hikariCP connectionPool, it's faster than boneCP

**Comment by seratch** [comment]
You can use it just by having a few lines of code.

```scala
val dataSource: DataSource = {
  val ds = new HikariDataSource()
  ds.setDataSourceClassName(dataSourceClassName)
  ds.addDataSourceProperty("url", url)
  ds.addDataSourceProperty("user", user)
  ds.addDataSourceProperty("password", password)
  ds
}
ConnectionPool.singleton(new DataSourceConnectionPool(dataSource))
```
http://scalikejdbc.org/documentation/connection-pool.html

**Comment by zJiaJun** [comment]
it's ok.
i read [ConnectionPoolFactoryRepository](scalikejdbc-core/src/main/scala/scalikejdbc/ConnectionPoolFactoryRepository.scala), 
suggest added source code.

**Comment by seratch** [comment]
No, we are not planning to add HikariCP there as the connection pool's configurations are a bit different from the libraries listed there.

With `DataSourceConnectionPool`, you can set your preferred configurations. Just use `DataSourceConnectionPool` directly.

**Comment by seratch** [comment]
As I mentioned in the previous comment, we won't take action for this. Let me close this issue.
