### ISSUE TITLE
What's difference between AutoSession and ActiveSession

### ISSUE THREAD

**Issue by zJiaJun** [scalikejdbc/scalikejdbc#1110]
I read [AutoSession](http://scalikejdbc.org/documentation/auto-session.html).
AutoSession, ReadOnlyAutoSession, ActiveSession
What's the difference?

**Comment by seratch** [comment]
AutoSession opens a read-only session for select queries while an auto-commit session for update/execute operations. As ActiveSession is an internal state, you won't use it directly.

**Comment by zJiaJun** [comment]
i got it.tks
