### ISSUE TITLE
can scalikejdbc integrate with clickhouse？

### ISSUE THREAD

**Issue by Tasselmi** [scalikejdbc/scalikejdbc#1111]
or is there any use case to learn？ thx very much.

**Comment by seratch** [comment]
If the JDBC driver is implemented in a right way, ScalikeJDBC should work along with it but we do not guarantee that. This library officially supports only MySQL, PostgresSQL, H2, and HSQLDB.

**Comment by seratch** [comment]
As we does not have any further actions to take here, let me close this issue now.
