### ISSUE TITLE
Can't run queries in transaction in parallel

### ISSUE THREAD

**Issue by mrdziuban** [scalikejdbc/scalikejdbc#1113]
I'm using v3.5.0 of scalikejdbc and v2.7.0 of the [mariadb java client](https://github.com/mariadb-corporation/mariadb-connector-j) (both the latest versions).

When using `withinTx`, queries executed in `Future`s using the given `sess` do not run in parallel as expected. Rather than each `Future` completing in the same amount of time as the individual query, it completes in the amount of time it takes to run all of the queries. For example, if I run two queries that take 2 and 3 seconds, neither `Future` completes until 5 seconds has passed.

Here's some code to reproduce the issue:

```scala
import scala.concurrent.{Await, Future}
import scala.concurrent.duration.Duration
import scala.concurrent.ExecutionContext.Implicits.global
import scalikejdbc._

ConnectionPool.singleton("jdbc:mariadb://localhost/<DB_NAME>", "<USER>", "<PASSWORD>", new ConnectionPoolSettings)
val db = DB(ConnectionPool.borrow())
db.begin()

val sleep2s = "select 1 from dual where sleep(2)"
val sleep3s = "select 1 from dual where sleep(3)"

def runQuery(msg: String, query: String)(implicit sess: DBSession) = Future {
  println(s"$msg (start: ${java.time.Instant.now})")
  SQL(query).toMap().single().apply()
  println(s"$msg (end: ${java.time.Instant.now})")
}

def runQueries(implicit sess: DBSession) =
  Await.result(Future.sequence(Seq(runQuery("sleep 2s", sleep2s), runQuery("sleep 3s", sleep3s))), Duration.Inf)

db.withinTx(sess => runQueries(sess))
/*
sleep 3s (start: 2020-10-28T19:26:45.407Z)
sleep 2s (start: 2020-10-28T19:26:45.407Z)
sleep 2s (end: 2020-10-28T19:26:50.551Z)
sleep 3s (end: 2020-10-28T19:26:50.551Z)
*/
```

However, if I use `AutoSession` then the queries run in parallel and the `Future`s complete when I expect:

```scala
runQueries(AutoSession)
/*
sleep 3s (start: 2020-10-28T19:26:51.641Z)
sleep 2s (start: 2020-10-28T19:26:51.641Z)
sleep 2s (end: 2020-10-28T19:26:53.708Z)
sleep 3s (end: 2020-10-28T19:26:54.716Z)
*/
```

Is this expected? If not, are there any workarounds I can try?

**Comment by mrdziuban** [comment]
After more debugging and research, I believe this is a limitation of the mysql/mariadb drivers. [This stackoverflow answer](https://stackoverflow.com/a/32931377/2163024) seems to confirm, as well as [this response from a MySQL team member](https://lists.mysql.com/java/7053). Feel free to close this issue if you agree.

**Comment by seratch** [comment]
Thanks for sharing this! Yes, for running a transactional operation across multiple Futures, simply sharing a DB instance does not work. Let me close this now.
