### ISSUE TITLE
Difference between connectionTimeoutMillis and poolConnectionTimeoutMillis

### ISSUE THREAD

**Issue by alexklibisz** [scalikejdbc/scalikejdbc#1139]
Hi, I'm wondering what's the difference between connectionTimeoutMillis and poolConnectionTimeoutMillis?  Similarly, what's the difference for all of the other settings that just differ by the `pool` prefix?

For context, I'm using postgres with the commons-dbcp2 connection pool.

Also, it's possible that there's a typo or bad merge in the [config docs](http://scalikejdbc.org/documentation/configuration.html):

```
# Connection Pool settings
db.default.poolInitialSize=10
db.default.poolMaxSize=20
db.default.connectionTimeoutMillis=1000

# Connection Pool settings
db.default.poolInitialSize=5
db.default.poolMaxSize=7
db.default.poolConnectionTimeoutMillis=1000
db.default.poolValidationQuery="select 1 as one"
db.default.poolFactoryName="commons-dbcp2"
```

should probably just be

```
# Connection Pool settings
db.default.poolInitialSize=5
db.default.poolMaxSize=7
db.default.poolConnectionTimeoutMillis=1000
db.default.poolValidationQuery="select 1 as one"
db.default.poolFactoryName="commons-dbcp2"
```

**Comment by seratch** [comment]
Thanks for flagging this! The connectionTimeoutMillis is a deprecated key, which still works in the same way. We can safely delete it from the documents.

**Comment by alexklibisz** [comment]
Thanks. And just to make sure, am I understanding correctly that the poolConnectionTimeoutMillis is the amount of time that the connection pool will wait to acquire a connection?

**Comment by seratch** [comment]
Yes, you're right. With the default settings, ScalikeJDBC relies on commons-dbcp2. The value is set to this configuration: https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#setMaxWaitMillis-long-

see also: https://github.com/scalikejdbc/scalikejdbc/blob/3.5.0/scalikejdbc-core/src/main/scala/scalikejdbc/Commons2ConnectionPool.scala#L34

**Comment by seratch** [comment]
@alexklibisz Thanks for updating the document 🙇 The change will be deployed soon. Let me close this issue now.
