### ISSUE TITLE
 How can sort query by aggregate function?

### ISSUE THREAD

**Issue by afanasevek** [scalikejdbc/scalikejdbc#1153]
Hello. I need some help with ScalikeJDBC, thats why this question for its users.
my project have next tables: Posts, Users, Votes. Post one-to-many Votes, Post many-to-one users. I want to get All posts with comments and user and order by comments count. First problem was uncorrect limit, but I fixed this by sub-queries. But how can I sort posts by count queries ?
I know how to do it in SQL. How can i order by count(v.voteId) in DSL ? .orderBy(x(count(v.voteId))) not working
In this gist you can find my DSL function and SQL script:
https://gist.github.com/afanasevek/82fb6b0f09d7f74565b55adf9879d582

**Comment by seratch** [comment]
Hi @afanasevek, one possible way to write the query is to utilize `sqls""` for some parts of your DSL query. This one may be a good example demonstrating that: https://github.com/scalikejdbc/scalikejdbc/blob/3.5.0/scalikejdbc-interpolation/src/test/scala/scalikejdbc/QueryInterfaceSpec.scala#L310-L314

**Comment by seratch** [comment]
As I've provided an answer here, let me close this. If you have something further to ask/discuss on this, please feel free to write in!
