### ISSUE TITLE
Possible SQL injection vulnerability

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#116]
SQLSyntax.apply(String) is unsafe. This API should not be public.

``` scala
val input = "'Chris' or id is not null"
val name = SQLSyntax(input)
val foundUser = sql"select ${u.result.*} from ${User.as(u)} where ${u.name} = ${name}"
  .map(User(u.resultName)).single.apply()
```

The above code will run the following SQL.

``` sql
select u.id as i_on_u, u.name as n_on_u, u.company_id as ci_on_u from users u 
  where u.name = 'Chris' or id is not null
```

The following case is safe. Users should use only sql"" or sqls"".

``` scala
val input = "'Chris' or id is not null"
val name = sqls"${input}"
val foundUser = sql"select ${u.result.*} from ${User.as(u)} where ${u.name} = ${name}"
  .map(User(u.resultName)).single.apply()
```

**Comment by vvviiimmm** [comment]
Maybe I'm missing something but following code doesn't work for me

```scala
val tableName = "table2"
val sqlsTableName = sqls"${tableName}"`
val interpolatedSql = sql"select * from ${sqlsTableName}"
println(interpolatedSql.statement) // prints `select * from ?`
interpolatedSql.map(r => println(r)).single().apply() // Error: near "?": syntax error
```

Version 2.3.5. Any help would be greatly appreciated, spent a lot of time trying to get any interpolation working.

**Comment by seratch** [comment]
`val sqlsTableName = SQLSyntax.createUnsafely(tableName)` should work for you. As its name tells you, undoubtedly this API is unsafe.

**Comment by vvviiimmm** [comment]
@seratch Thanks a lot for your fast reply. Apparently, this is actually what I should do, because I can't know the details about a database I'll work with. Mapping to classes doesn't make sense in this case.
