### ISSUE TITLE
One to many get Nothing

### ISSUE THREAD

**Issue by whitelowrie** [scalikejdbc/scalikejdbc#1212]
New I use the scalikejdbc DSL to query one to may but it can not work:
![image](https://user-images.githubusercontent.com/13913085/117933277-f9c3e100-b333-11eb-94da-01c26a001dda.png)
It show be 
```scala
one[T](WrappedResultset => T)
```
I use version 3.4.2,  So How can I do?

**Comment by seratch** [comment]
`one[YourEntityClassType](...)` should work for you!

**Comment by seratch** [comment]
Let us close this issue due to inactivity but feel free to write in if you have anything further to ask/clarify here!

**Comment by KingHO2359** [comment]
I am using:

- scala 2.13.8
- play 2.8.15
- "org.scalikejdbc" %% "scalikejdbc"                    % "3.5.0",
- "org.scalikejdbc" %% "scalikejdbc-config"             % "3.5.0",
- "org.scalikejdbc" %% "scalikejdbc-play-dbapi-adapter" % "2.8.0-scalikejdbc-3.5",
- "org.scalikejdbc" %% "scalikejdbc-syntax-support-macro" % "3.5.0"

and using the sample code, but I also have this error:

![image](https://user-images.githubusercontent.com/36753313/162877903-d8988885-e275-4666-bde5-2dd0b7badc69.png)

![image](https://user-images.githubusercontent.com/36753313/162876798-e9abbc8b-17cc-4e43-8680-f78e9fae126f.png)

please give me some advice, thanks so much

**Comment by KingHO2359** [comment]
I am using scalikejdbc 3.5 and play 2.8. I have also this problem. Please give me some advise.
Thanks so much.
```
"org.scalikejdbc" %% "scalikejdbc"                    % "3.5.0",
"org.scalikejdbc" %% "scalikejdbc-config"             % "3.5.0",
"org.scalikejdbc" %% "scalikejdbc-play-dbapi-adapter" % "2.8.0-scalikejdbc-3.5",
"org.scalikejdbc" %% "scalikejdbc-syntax-support-macro" % "3.5.0"
```
![image](https://user-images.githubusercontent.com/36753313/165240431-bce07672-3463-4ed0-b5e1-c79ec44dcc4a.png)

This code below is in scalikejdbc document: http://scalikejdbc.org/documentation/one-to-x.html

**Comment by KingHO2359** [comment]
> `one[YourEntityClassType](...)` should work for you!

Although I tried this way, it's not work.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/36753313/165242477-b611cfc4-ad4d-4ac7-93d6-f2d6c1987af6.png">
