### ISSUE TITLE
Access postgres extensions on JDBC statement

### ISSUE THREAD

**Issue by jahan01** [scalikejdbc/scalikejdbc#1276]
I have a use case where in I need to access few of [extension methods](https://github.com/pgjdbc/pgjdbc/blob/151b287732a551c380dcaa34f9c0549aeeb26208/pgjdbc/src/main/java/org/postgresql/PGStatement.java#L14) on Statement by postgres drivers like `getLastOID`

This is closely related to #1108 

I can access these methods by directly using connection objects from the pool and creating a statement myself but this loses all the niceties provided by scalikejdbc like extractors, tags, logging etc.,

My question is scalikejdbc designed to work for these cases? What is the recommended approach for accessing these methods without losing all the wonderful features provided by the library ?

**Comment by seratch** [comment]
Hi @jahan01 , thanks for writing in! However, unfortunately, this project does not have any plans to better support your use case at least in the short term. Consider alternatives or your own fork/solutions.
