### ISSUE TITLE
QueryDSL doesn't correctly union SELECT...ORDER BY/LIMIT statements for PostgreSQL

### ISSUE THREAD

**Issue by du-stripe** [scalikejdbc/scalikejdbc#1391]
When using `UNION`, with `ORDER BY` or `LIMIT` within a subexpression's `SELECT` statement, PostgreSQL requires the `SELECT` statement be enclosed in parentheses: https://stackoverflow.com/a/24024639 However, the following QueryDSL code causes a syntax error against Postgres because it doesn't generate those parentheses:

```scala
val i = Item.syntax("i")
selectFrom(Item.as(i)).orderBy(i.id).unionAll(
  selectFrom(Item.as(i)).orderBy(i.id)
).list().apply()
```

My current workaround is to use `.toSQLSyntax` on each subexpression and combine them manually with `sqls"($a) union all ($b)"`

**Comment by seratch** [comment]
Thanks for sharing this! At this moment, your workaround is the only way to achieve your goal. 

For the future, it may be worth considering to add the `withRoundBracket ` SDL for complete statements: https://github.com/scalikejdbc/scalikejdbc/blob/4.0.0/scalikejdbc-interpolation/src/test/scala/scalikejdbc/QueryInterfaceSpec.scala#L436-L447
