### ISSUE TITLE
Question: Possible to use auto-rollback on production code that creates transactions themselves?

### ISSUE THREAD

**Issue by hedefalk** [scalikejdbc/scalikejdbc#1506]
Hi, this is a question not an issue, but it seemed to me the googlegroup was pretty dead. Sorry if this is the wrong place to ask, but here it goes:

I'm trying to use AutoRollback (http://scalikejdbc.org/documentation/testing.html) or something similar from ScalaTest on production code that I can't really change too much. Or I _can_ change it, but we have autogenerated contracts coming from openapi definitions that we need to implement. Like so:

`def someEndpoint(input: SomeInput): Output`

The production implementation then looks something like:

```scala
  override def someEndpoint(input: SomeInput): =
      DB.readOnly { implicit session =>
          val data = reportStore.create(reportUpdate.name) // session used here
          Output(data)        
          }
      }
  }
```
I want to be able to do rollbacks on a suite of calls to these methods, end-to-end tests on a scenario. But there are usages of DB.readOnly, DB.autoCommit and DB.localTx within these implentations. For me these methods creates new sessions, like here:

```scala
  def readOnly[A](execution: DBSession => A)(implicit
    context: CPContext = NoCPContext,
    settings: SettingsProvider = SettingsProvider.default
  ): A = {
    val cp = connectionPool(context)
    using(cp.borrow()) { conn =>
      DB(conn, cp.connectionAttributes, settings)
        .autoClose(false)
        .readOnly(execution)
    }
  }

```
At that point I have no CPContext or SettingsProvider in scope so it uses defaults and creates new sessions. Since the signatures to implement are autogenerated I can't really add extra param lists with the session I want it to use from the test suite.

At this point I'm considering that the tests beforeEach instead should inject the session or mock AutoSesssion or something like that, but it feels I might be missing a much cleaner or simpler approach…?

Any pointers highly appreciated!

**Comment by seratch** [comment]
Hi @hedefalk, sorry for slow response here. As long as you use `DB.readOnly { }` in your code, the session managed by `AutoRollback` is unable to manage the transaction for the code. If you would like the method to join a transactional session, the right way is to use implicit `DBSession` parameter in your method signature. If this explanation does not make sense to you, I would suggest trying the code generated by http://scalikejdbc.org/documentation/reverse-engineering.html out.

I hope this helps.

**Comment by seratch** [comment]
Let me know if you need more help here. I will close this issue after waiting for your response for a few more days.
