### ISSUE TITLE
Query/Result caching

### ISSUE THREAD

**Issue by nikoplusx** [scalikejdbc/scalikejdbc#1525]
Does scalalikejdbc support query/result caching? I've tried to search through the docs but haven't found anything. I also tried to skim through the `TypesafeConfigReader` but did not find a cache setting there either.

Thanks a lot.

**Comment by seratch** [comment]
Hi @nikoplusx, thanks for writing in! There is no built-in query cache/result support at this moment. I would suggest using a different cache library such as https://github.com/cb372/scalacache to reduce method calls.

**Comment by seratch** [comment]
Thanks for the reaction! Let me close this issue.
