### ISSUE TITLE
Commit connection inside localTx?

### ISSUE THREAD

**Issue by Sparker0i** [scalikejdbc/scalikejdbc#1740]
I am looking to have the functionality of `setAutoCommit(false)` while running my insert and delete queries. So looking at #792 I have created a function like this with localTx:

```
def executeBatches( batches: List[(String, Seq[Seq[Any]])] ): Either[Throwable, String] = {
  DB.localTx{implicit dbs =>
    dbs.connection.setAutoCommit(false)
    executeBatchesFromCSV(dbs, batches, Right("Initializing")) match {
      case Left(value) =>
        println("Rolling back to Savepoint")
        dbs.connection.rollback()
        Left(value)
      case Right(value) =>
        dbs.connection.commit()
        Right(value)
    }
  }
}
```

The `batches` argument was generated programatically with the first param being my insert/delete string query and the second argument being the batchParams against which to execute this.

Then inside `executeBatchesFromCSV`, I'm looping over this `batches` list one by one and executing the below code:

```
def runScript(dbs: DBSession, batch: (String, Seq[Seq[Any]]) ): Either[Throwable, String] = {
  implicit val session: DBSession = dbs
  println(s"Query:\n${batch._1}")
  println(s"Params:\n${batch._2}")
  Try(SQL(batch._1).batch(batch._2: _*).apply()) match {
    case Failure(exception) => Left(exception)
    case Success(_) => Right("Success")
  }
}
```

Whenever there is an error, it does go into the `Left(value)` branch inside `executeBatches` and calls the `rollback()` and program exits fine. 
However, when executing all the `batches` was successful, it does go inside the `Right(value)` branch of `executeBatches` but the commit does not seem to be happening despite explicitly mentioning a `commit()` against the `Connection` object.

Is there any other way to have `setAutoCommit(false)` working against a `Connection` object through this library?

**Comment by seratch** [comment]
Hi @Sparker0i, I still don't understand your goal here but when you use localTx for multiple SQL executions, rolling all back even for a single failure is an expected valid behavior. If you would like to run a transaction for each query, consider having localTx for each. This means that you may have to give up using the JDBC batch API if it does not work in the way that you expect.

**Comment by Sparker0i** [comment]
On Further analysis, I realized that my insert batches were running first, then the delete batches, thus effectively making it appear that there were no changes. Probably because I'm writing detailed FP code for the first time.
Closing this. Thanks for the help.
