### ISSUE TITLE
How do I support "TOP" on SQL Server using the QueryDSL?

### ISSUE THREAD

**Issue by fancellu** [scalikejdbc/scalikejdbc#1878]
Limit is not supported in SQL Server, I'd like to put a "TOP N" after the select. 

e.g.

"SELECT TOP 3 * from table"

I can append things to the end e.g.  ```select.from(blah).append(sqls" with(nolock)")```

But how would I inject something after the "select" and before the "* from"  ?

A select.append() would be nice, or equivalent

Thanks

**Comment by seratch** [comment]
Hi @fancellu, thanks for writing in! You can pass any `sqls""` to `select()` method and then extract the values with the same names in ResultSet. So, `select(sqls"top 3 *").from(blah).where(...)` should work for you. Since I don't use SQL Server, I may not be able to help you further with details.

**Comment by fancellu** [comment]
But what if I want to use the QueryDSL? e.g. Say I want to do a "TOP N" for the below query?
http://scalikejdbc.org/documentation/operations.html#list-results

Thanks

**Comment by seratch** [comment]
The "top n" part has to be a sqls object but you can still use QueryDSL for the rest of query object. Since the "top n" syntax is not a syntax supported by other RDBMSs (specifically MySQL, PostgreSQL, H2, HSQLDB, that we officially support), we won't add the syntax to the DSL at least in the short term.

**Comment by fancellu** [comment]
So how would I add "TOP N" to the below code?

```scala
val name: List[String] = DB readOnly { implicit session =>
  withSQL { select(e.result.name).from(Emp as e) }.map(_.string(e.name)).list.apply()
}
```

I'm v new to Scalike. Thanks

**Comment by seratch** [comment]
sqls"top 3 ${e.result.name}" instead of e.result.name should work for you. When you need all the columns, you can use `e.result.*` for it

**Comment by fancellu** [comment]
Brilliant. I didn't realize I could embed it to easily.

**Comment by seratch** [comment]
If the above does not work with the SQL Server's syntax parse, please try other patterns such as `e.name`, which does not give an alias to the column. Refer to http://scalikejdbc.org/documentation/query-dsl.html for more details. I hope you'll figure out the best solution for your use case.

**Comment by fancellu** [comment]
I'll tell you when I get back to work, will be good to know what works for SQL Server. Microsoft just has to be non standard.

**Comment by fancellu** [comment]
Yes, works fine with 
```
      val i = In.syntax("i")
      val in: List[In] = withSQL {
        select(sqls"top 3 ${i.result.*}").from(In as i).append(sqls" with (NOLOCK)")
      }.map(In(i.resultName)).list.apply()
```

I also needed to have ```useSnakeCaseColumnName=false``` for my SQLSyntaxSupport companion

**Comment by seratch** [comment]
Thanks for sharing the update! Glad to hear that it worked for you 👍 As I mentioned above, we are not planning to add the syntax to DSL at least in the short term. So, let me close this issue now. Thanks again for writing in!
