### ISSUE TITLE
Interpolate SQL - combine generic DB name and static table name

### ISSUE THREAD

**Issue by kell18** [scalikejdbc/scalikejdbc#2017]
Hello,

Is there a way to interpolate this to a valid SQL?

```scala
val tableName = something match { 
  case x => sqls"$dbName.TableNameStr"
  case y => sqls"$dbName.OtherTableNameStr"
}
SELECT * FROM $tableName LIMIT 100
```
Currently it fails for me with:

```
Failed preparing the statement (Reason: Invalid argument value: java.io.NotSerializableException):

  ()
```

I think because `$dbName` is escaped with `'` but I don't need that in this case.

Thank you!

**Comment by seratch** [comment]
You can directly embed any content when using the `SQLSyntax.createUnsafely(string)` utility. However, please be aware that your `dbName` parameter should never be a random input from sources such as external HTTP requests, public methods, or any other input that can potentially contain harmful string values.
