### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#2063]
latest release (4.0.0) is 2 years ago 🥺 https://github.com/scalikejdbc/scalikejdbc/releases/tag/4.0.0

**Comment by seratch** [comment]
As always, thank you so much for your time and efforts devoted to this project. IIUC, there haven't been any major feature updates for this library while you've diligently been maintaining the project settings and dependency upgrades.  With that being said, should users require a new release, I can find time to cut a new minor version sometime soon.

**Comment by seratch** [comment]
Released: https://repo1.maven.org/maven2/org/scalikejdbc/scalikejdbc-core_3/4.1.0/
