### ISSUE TITLE
Issue with Parsing '--' Inside Strings as Comments in SQL Queries

### ISSUE THREAD

**Issue by dnalm** [scalikejdbc/scalikejdbc#2088]
I've encountered an issue in ScalikeJDBC where strings containing '--' are incorrectly identified as the start of a comment. This misinterpretation leads to the erroneous parsing of SQL queries.

Upon reviewing the source code, I noticed that the function for removing line comments employs a regular expression. This approach might not be robust enough to handle complex SQL queries. Here is the relevant [snippet():](https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-core/src/main/scala/scalikejdbc/SQLTemplateParser.scala)
```scala
def removeLineComments(): String =
  str.split("\n").map(_.replaceFirst("--.+$", "")).mkString(" ")
``` 
The issue can be reproduced with the following code snippet:
```scala
DBs.setupAll()
DB localTx { implicit session =>
  SQL("""
    |update work_tbl
    |set work_name='--mmnn', work_code='300'
    |where id='1'
    |""".stripMargin).update.apply()
}
```
In this case, the SQL command executed becomes incorrectly truncated as follows:
```sql
update work_tbl set work_name=' where id='1
```

Thank you.

**Comment by seratch** [comment]
Hi @dnalm, thanks for writing in. 

This project still keeps the SQL + string argument method, but I no longer recommend using SQL + plain string statement because it's not a secure way. It was implemented before the string interpoation feature in Scala was added a long time ago. The currently recommended way is to use `sql"...."` and embed any parameters as below. In this way, the issue you reported here does not arise.

```scala
DBs.setupAll()
DB localTx { implicit session =>
  sql"""update work_tbl
    |set work_name=${"--mmnn"}, work_code=${300}
    |where id=${1}
    |""".stripMargin.update.apply()
}
```

or 
```scala
DB localTx { implicit session =>
  val workName = "--mmnn"
  val workCode = 300
  val id = 1
  sql"""update work_tbl
    |set work_name=$workName, work_code=$workCode
    |where id=$id
    |""".stripMargin.update.apply()
}
```

If you have a certain reason to use the legacy insecure way, use `?` placeholder and binding parameters like you can with underlying JDBC prepared statement objects.

I hope this helps.

**Comment by dnalm** [comment]
@seratch 
Thank you very much for your response. Using placeholders and binding parameters as you suggested indeed works well.

I have a follow-up question: 
In some situation, I might need to execute complete SQL statements sourced from elsewhere, where I cannot anticipate the specific content of the SQL beforehand. In such cases, how should I handle these SQL statements containing unpredictable content to ensure they are executed correctly without causing parsing errors?

**Comment by seratch** [comment]
I really don't recommend this approach for general use cases, but if your app never accepts external inputs, which can cause SQL injection incidents, the following code can be an option (again, I don't recommend it):

```scala
import scalikejdbc._

val unsafeInput = """update work_tbl
    |set work_name=$workName, work_code=$workCode
    |where id=$id
    |""".stripMargin

DB.localTx { implicit s =>
  val unsafeStatement = SQLSyntax.createUnsafely(unsafeInput)
  sql"${unsafeStatement}".update.apply()
}
```

Everything should be clear now. Would you mind closing this issue?

**Comment by dnalm** [comment]
Thank you very much.
