### ISSUE TITLE
scalikejdbc-mapper-generator  generates extra fields

### ISSUE THREAD

**Issue by laglangyue** [scalikejdbc/scalikejdbc#2126]
```sql
CREATE TABLE users (
    user_id INT AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

use  ` sbt "scalikejdbcGen users" `

```scala
case class Users(
  user: Option[String] = None,
  currentConnections: Long,
  totalConnections: Long,
  maxSessionControlledMemory: Long,
  maxSessionTotalMemory: Long,
  userId: Int,
  username: String,
  password: String,
  fullName: String,
  email: String,
  phoneNumber: Option[String] = None,
  address: Option[String] = None,
  createdAt: Option[ZonedDateTime] = None,
  updatedAt: Option[ZonedDateTime] = None) {

  def save()(implicit session: DBSession = Users.autoSession): Users = Users.save(this)(session)

  def destroy()(implicit session: DBSession = Users.autoSession): Int = Users.destroy(this)(session)

}
```
there are some extra fields

![image](https://github.com/scalikejdbc/scalikejdbc/assets/35491928/2b88000f-34a5-4151-8b22-75408a11c335)

**Comment by laglangyue** [comment]
all of them will be found in repo
https://github.com/laglangyue/scala-springboot-awesome.git

**Comment by laglangyue** [comment]
surely again for table doesn't have the column
![image](https://github.com/scalikejdbc/scalikejdbc/assets/35491928/f94c775f-777e-4739-87d4-ca5fe8ca349d)

**Comment by seratch** [comment]
It seems that the columns from performance schema are merged into the column list: https://dev.mysql.com/doc/mysql-perfschema-excerpt/8.0/en/performance-schema-users-table.html for some reason (perhaps, due to the JDBC driver's unsual behavior).

Having your database name prefix to "users" table argument such as "mydb.users" may help. If it does not work out, adjusting the metadata fetching logic to MySQL JDBC drivers may be necessary to resolve it. We've made MySQL specific changes like https://github.com/scalikejdbc/scalikejdbc/pull/926 in the past.

**Comment by laglangyue** [comment]
> It seems that the columns from performance schema are merged into the column list: https://dev.mysql.com/doc/mysql-perfschema-excerpt/8.0/en/performance-schema-users-table.html for some reason (perhaps, due to the JDBC driver's unsual behavior).
> 
> Having your database name prefix to "users" table argument such as "mydb.users" may help. If it does not work out, adjusting the metadata fetching logic to MySQL JDBC drivers may be necessary to resolve it. We've made MySQL specific changes like #926 in the past.

thanks, I get it .
the url and `jdbc.schema`  specifiy the database. It seems not work, I will test the jdbc api.
```shell
jdbc.url=jdbc:mysql://172.17.0.2:3306/test
jdbc.username=root
jdbc.password=slalikejdbc
jdbc.schema=test
```

**Comment by laglangyue** [comment]
I use the driver(8.0.33)
min code like `ScalikejdbcPlugin`
```scal
    val columns = metaData.getColumns(null, "test", "users", "%")
```
 the TABLE_SCHEM is null, because mysql does not has schema.
```text
(TABLE_CAT,TABLE_SCHEM,TABLE_NAME,COLUMN_NAME)

performance_schema  null  users  USER
performance_schema  null  users  CURRENT_CONNECTIONS
performance_schema  null  users  TOTAL_CONNECTIONS
performance_schema  null  users  MAX_SESSION_CONTROLLED_MEMORY
performance_schema  null  users  MAX_SESSION_TOTAL_MEMORY
test  null  users  user_id
test  null  users  username
test  null  users  password
test  null  users  full_name
test  null  users  email
test  null  users  phone_number
test  null  users  address
test  null  users  created_at
test  null  users  updated_at

```

**Comment by laglangyue** [comment]
when I use can get the table correctly
```scala
 val columns = metaData.getColumns("test", "test", "users", "%")
```

**Comment by laglangyue** [comment]
![image](https://github.com/scalikejdbc/scalikejdbc/assets/35491928/cab643ba-5c1f-4304-a51c-c23037fb4921)

This catalog has always been null, so I suggest adding an optional parameter , `jdbc.database` or `jdbc.catalog`.
what do you think？
@seratch

**Comment by seratch** [comment]
Indeed, these methods do not work properly for MySQL drivers. I haven't checked if this works yet, but doing the same with this line of code may help: https://github.com/scalikejdbc/scalikejdbc/blob/4.1.0/scalikejdbc-mapper-generator-core/src/main/scala/scalikejdbc/mapper/Model.scala#L48

May I ask you to improve the code to use jdbc.schema as catalog only for MySQL?

**Comment by laglangyue** [comment]
> Indeed, these methods do not work properly for MySQL drivers. I haven't checked if this works yet, but doing the same with this line of code may help: https://github.com/scalikejdbc/scalikejdbc/blob/4.1.0/scalikejdbc-mapper-generator-core/src/main/scala/scalikejdbc/mapper/Model.scala#L48
> 
> May I ask you to improve the code to use jdbc.schema as catalog only for MySQL?

willing to do this. But I did a different PR because the catalog should not be directly null and can be configured by the user.
There are too many databases that use the MySQL protocol, and they will tamper with the jdbc implementation by using ·catalog.schema.table· to uniquely locate the table, and  catalog usually is  the database such as H2/mysql

**Comment by laglangyue** [comment]
Since I did not see your comment before completing this PR, I will temporarily submit it. I will reconsider  to use `jdbc.schema` as catalog only for MySQL?

**Comment by seratch** [comment]
We’ve never received feature request to enable passing catalog data. I prefer a simple internal change to resolve the MySQL specific issue this time. If other folks need solutions for other mostly-MySQL-compatible JDBC drivers in the future, we may add a new parameter for it then.

**Comment by laglangyue** [comment]
@seratch I had close preview PR, and resubmit one.
https://github.com/scalikejdbc/scalikejdbc/pull/2128
