### ISSUE TITLE
Missing tags in one-to-X queries

### ISSUE THREAD

**Issue by kardapoltsev** [scalikejdbc/scalikejdbc#2155]
Hello! I'm trying to use tagging for my queries but can not do it for one-to-X queries. I think `tags` are missed here 

```scala
  override def toOption: OneToManies3SQLToOption[A, B1, B2, B3, E, Z] = {
    new OneToManies3SQLToOption[A, B1, B2, B3, E, Z](statement, rawParameters)(one)(to1, to2, to3)(zExtractor)(true)
  }
```

I think it could be fixed in `GenerateOneToManies.scala`:
```scala
  override def toOption: OneToManies${n}SQLToOption[A, $bs, E, Z] = {
    val q = new OneToManies${n}SQLToOption[A, $bs, E, Z](statement, rawParameters)(one)($to)(zExtractor)(true)
    q.queryTimeout(queryTimeout)
    q.fetchSize(fetchSize)
    q.tags(tags*)
    q
  }
```

I can provide a PR if this one looks like a good fix for you.

**Comment by seratch** [comment]
Hi, thanks for reporting this! Could you send a pull request to resolve it if you have the bandwidth for it?

**Comment by kardapoltsev** [comment]
Yes, sure. I also have one more issue with tags, investigating it now... I'll create another PR if I'll be able to find where the bug is. I'm still not sure is it on my side or not.
