### ISSUE TITLE
SQLInterpolation problem with passing table name

### ISSUE THREAD

**Issue by corelon** [scalikejdbc/scalikejdbc#320]
Hi I have a query which I want to reuse for several tables.

I am using the following code:

``` scala
val result = DB readOnly { implicit session =>
  sql"select count(1) from ${table}".map(_.long(1)).single.apply()
}
```

The above fails as the table when interpolated it is quoted so an example would be

``` sql
select count(1) from 'table'
```

which in Postgresql (at least) throws an exception).

Is there a way to make it work without the quotes?

**Comment by dinoboy197** [comment]
I agree that this should be listed in the documentation. I was just bitten by this problem myself and had it been documented, I wouldn't have to had searched through all of the github issues to see that other people have had the same issue as well.

**Comment by Synesso** [comment]
Where string interpolation is used on the table name it's almost certainly not the intended behaviour. Could there be a warning?

**Comment by jongwook** [comment]
Using `SQLSyntax.createUnsafely` for table name looks like it will have a potential SQL injection vulnerability.

**Comment by alswl** [comment]
`val table = SQLSyntax.createUnsafely(tableName)` it seems did not works with `bindByName`, error message is:

```
15:16:51.232 [pool-1-thread-3] ERROR s.ActiveSession - Failed preparing the statement (Reason: The conversion from UNKNOWN to UNKNOWN is unsupported.):
```
