### ISSUE TITLE
Adding a "tag" to queryCompletionListener and queryFailureListener

### ISSUE THREAD

**Issue by BardurArantsson** [scalikejdbc/scalikejdbc#321]
In attempting to use GlobalSettings.query{Completion,Failure}Listener to generate metrics, I've encountered a need to be able to "label" queries created via

       SQL("my sql goes here")

such that the completion/failure listener functions can receive that label. There are various reasons for this, but mostly it's that metrics tools usually don't seem to support completely arbitrary metric names very well (such as just using the SQL text itself) and thus we need an explicit label for each usage of SQL(...).

I'm thinking the label would perhaps just be an Any, but String would do absolutely fine for my purposes. Usage-wise I'm thinking of something like the following

     SQL("my sql goes here", label = "foo")
        .xxx()
        .yyy()

(Obviously this would be a regular overload to preserve compatibility.)

Another option for usage would be

    SQL("my sql goes here")
       .label("foo")
       .xxx()
       .yyy()

which I suppose might be more self-explanatory.

The two listener function signatures in GlobalSettings would be expanded to include a corresponding parameter. (Or perhaps we should add two entirely new functions to preserve backward compatibility?)

Before I start actually working on a patch, I'd like to ask if you would be likely to accept a patch to do something like what I've outlined above? (Assuming the patch itself is of good enough quality, of course).

**Comment by BardurArantsson** [comment]
Unfortunately it doesn't quite work. All query statements, i.e. `SELECT`, work fine, but all `UPDATE` or `INSERT` statements don't get the proper tags. As far as I can tell this is because the latter type of statements get their list of tags from the DBSession instead of from the tags added to the SQL instance.

**Comment by BardurArantsson** [comment]
Oh, just to be absolutely clear. I'm tagging all my statements exactly the same way:

   SQL("""blabla""").tags("foo","bar").....

the only difference is whether a query or update method gets called at the end.

**Comment by seratch** [comment]
Thanks. That should be fixed in the next version (2.2.2).

**Comment by seratch** [comment]
Fixed again. Would you try snapshot version again?

```scala
// sbt 0.13.7
scalaVersion := "2.11.5"
resolvers += "Sonatype Snapshots" at "http://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.scalikejdbc" %% "scalikejdbc" % "2.2.2-SNAPSHOT"
```

**Comment by BardurArantsson** [comment]
For some reason had to use

    Resolver.sonatypeRepo("snapshtos")

in "resolvers" rather than the direct URL, but once I had that all the tags worked! Thanks!

**Comment by seratch** [comment]
Thank you for your very quick reply. It's good to hear that. I'll merge #349 PR later and version 2.2.2 will be out within a few weeks.

**Comment by BardurArantsson** [comment]
Great, thanks!
