### ISSUE TITLE
Using Oracle with updateAndReturnGeneratedKey.apply()

### ISSUE THREAD

**Issue by cridmann** [scalikejdbc/scalikejdbc#332]
Hello,

I am trying to do something like:

```
case class Achieved(
  achievedId: Long,
  achievementCode: Option[String] = None,
  custId: Option[Long], 
)


    val id = withSQL {
      insert.into(Achieved).namedValues(column.achievementCode -> achievementCode, column.custId -> custId)
    }.updateAndReturnGeneratedKey().apply()

```

I am getting the following error:

```
Execution exception[[SQLException: Invalid column type: getLong not implemented for class oracle.jdbc.driver.T4CRowidAccessor]]
```

This may be an issue with Oracle's driver and how your API interacts with it?  Can you foresee a way around this?

Thanks!

-Chris

**Comment by cridmann** [comment]
Let me know what you think of this commit: https://github.com/cridmann/scalikejdbc/commit/6c66d124bf799a7382fc7fbc3e904f9cbe148db4

It resolves my Oracle issue, but breaks your test case:

[info] - should be able to updateAndReturnGeneratedKey with key *** FAILED ***
[info]   java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: id
[info]   at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
[info]   at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
[info]   at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
[info]   at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
[info]   at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:532)
[info]   at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:415)
[info]   at scalikejdbc.DBSession$class.createStatementExecutor(DBSession.scala:83)
[info]   at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:382)
[info]   at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:506)
[info]   at scalikejdbc.DBSession$class.updateAndReturnSpecifiedGeneratedKey(DBSession.scala:442)
[info]   ...
[info]   Cause: org.hsqldb.HsqlException: user lacks privilege or object not found: id
[info]   at org.hsqldb.error.Error.error(Unknown Source)
[info]   at org.hsqldb.error.Error.error(Unknown Source)
[info]   at org.hsqldb.Table.getColumnIndex(Unknown Source)
[info]   at org.hsqldb.Table.getColumnIndexes(Unknown Source)
[info]   at org.hsqldb.StatementDML.setGeneratedColumnInfo(Unknown Source)
[info]   at org.hsqldb.StatementManager.compile(Unknown Source)
[info]   at org.hsqldb.Session.execute(Unknown Source)
[info]   at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
[info]   at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
[info]   at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:532)


Maybe the only way to fix this without changing the API is to check which driver the user is using, and then perform the necessary logic?  Have you guys done this in the past?

**Comment by seratch** [comment]
>Maybe the only way to fix this without changing the API is to check which driver the user is using, and then perform the necessary logic? Have you guys done this in the past?

I have tried a little before but I found that it's not easy to detect which driver current connection uses at least when dealing with current scalikejdbc implementation. If all the existing JDBC drivers implemented `Connection#getClientInfo/#setClientInfo` as expected, we could use that. But the reality is different.

Although this is just an idea, we can consider new feature to specify driverName in `ConnectionPoolSettings` (and scalikejdbc propagate it to `DBSession` internally).

- add `driverName: String = null` to `scalikejdbc.ConnectionPoolSettings`
- add `driverName: Option[String] = None` to `scalikejdbc.DBSession`
- propagate the `connectionPoolSettings#driverName` to `scalikejdbc.DBSession`
- add `driverNamesToChooseColumnNameForAutoGeneratedKeyRetrieval: Seq[String] = Seq("oracle.jdbc.driver.OracleDriver")` to `scalikdjcb.GlobalSettings`

**Comment by cridmann** [comment]
Okay this makes sense at a high level.  Looking at the code, it isn't clear to me what your preferred method of "propagate the `connectionPoolSettings#driverName` to `scalikejdbc.DBSession`" would be.

I made a commit here https://github.com/cridmann/scalikejdbc/commit/56bf4b5725d77d20c872d305fea5b2390a63e113 

Which added the `ConnectionPoolSettings` to `DBConnection`, but I'm not sure if it properly supports all features (e.g. `ThreadLocalDB`).  The compiler is also saying there may be binary incompatibilities.

Before I went any further I wanted to get your perspective

**Comment by seratch** [comment]
Thanks a lot. I'm not sure how this change should be done on some points. I'd like to re-think about new API design by working on your commits.

**Comment by seratch** [comment]
One thing. We think keeping source-code backward compatibility is the most important thing. So changing arguments of #updateWithFilters is not acceptable.

**Comment by seratch** [comment]
@cridmann I just created a pull request #348 to fix this issue and published 2.2.2-SNAPSHOT against Scala 2.11 on sonatype snapshot repository. (scalikejdbc_2.11-2.2.2-SNAPSHOT). Please try it out when you have time.

**Comment by cridmann** [comment]
Thank you!  Yes good point on the updateWithFilters...I didn't notice it was a user facing API at the time.  
Looking at your commit, it seems like it will work.

I tried importing it in my build (scala 2.11.4):

   resolver = `"Sonatype Snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"`

   ` "org.scalikejdbc"      %% "scalikejdbc"                     % "2.2.2-SNAPSHOT",`

And it seems like it's not resolving:
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalikejdbc#scalikejdbc_2.11;2.2.2-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

  I'll try again tomorrow

**Comment by seratch** [comment]
> http://oss.sonatype.org/content/repositories/snapshots/

Specify "https://oss.sonatype.org/content/repositories/snapshots" instead.

**Comment by cridmann** [comment]
That fixed the resolving issue.

It looks like you forgot this step to load the `driverName` from the config in `TypesafeConfigReader.scala`

I grabbed your PR, and added:
```
    ConnectionPoolSettings(
      initialSize = configMap.get("poolInitialSize").map(_.toInt).getOrElse(default.initialSize),
      maxSize = configMap.get("poolMaxSize").map(_.toInt).getOrElse(default.maxSize),
      connectionTimeoutMillis = readTimeoutMillis().getOrElse(default.connectionTimeoutMillis),
      validationQuery = configMap.get("poolValidationQuery").getOrElse(default.validationQuery),
      connectionPoolFactoryName = configMap.get("poolFactoryName").getOrElse(default.connectionPoolFactoryName),
      driverName = configMap.get("driver").getOrElse(null)
    )
```
to `readConnectionPoolSettings`, and it worked for my use case.  Once you do that, I think this can be merged into trunk to close the issue

**Comment by seratch** [comment]
Good catch, thank you. I just fixed that too.

**Comment by cridmann** [comment]
Hello,

I'm also trying to figure out how to set the `ConnectionPoolSettings.driverName` from an external data source.

I see you never explicitly set the `ConnectionPoolSettings.driverName` when constructing a `DataSourceConnectionPool`: 

```
class DataSourceConnectionPool(override val dataSource: DataSource)
    extends ConnectionPool("<external-data-source>", "<external-data-source>", "<external-data-source>") {

  override def borrow(): Connection = dataSource.getConnection()
}
```

Here is how I'm constructing my pool:
```
val ds = new InitialContext(myEnv)
        .lookup("java:/comp/env/jdbc").asInstanceOf[Context]
        .lookup("DS").asInstanceOf[DataSource]

ConnectionPool.singleton(new DataSourceConnectionPool(ds)) 
```

Here's an example of what the datasource config looks like:

```
        <Resource
            name="DS"
            auth="Container"
            factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
            type="javax.sql.DataSource"
            driverClassName="oracle.jdbc.driver.OracleDriver"
            maxActive="100"
            maxIdle="30"
            maxWait="10000"
            testOnBorrow="true"
            testOnReturn="true"
            testWhileIdle="true"
            validationQuery="select 1 from dual"
            validationInterval="30000"
            url="redacted"
            username="redacted"
            password="redacted"
        />
```


Any ideas?

**Comment by seratch** [comment]
@cridmann Unsupported yet. But [this pull request](https://github.com/scalikejdbc/scalikejdbc/pull/369) will allow you to specify driverName like this:

```scala
val settings = DataSourceConnectionPoolSettings(driverName = "oracle.jdbc.driver.OracleDriver")
ConnectionPool.singleton(new DataSourceConnectionPool(dataSource, settings))
```

**Comment by cridmann** [comment]
That PR looks good to me!  Any idea when the next release will be?  Thanks for the quick turnaround.

**Comment by seratch** [comment]
The next release will be out soon (maybe within a few days).

**Comment by errd** [comment]
Hi there! Is there any workaround for this issue?

**Comment by seratch** [comment]
@errd Set ConnectionPoolSettings.drvierName as described above.
