### ISSUE TITLE
updateAndReturnGeneratedKey for MS SQL Server

### ISSUE THREAD

**Issue by metatron-the-chronicler** [scalikejdbc/scalikejdbc#338]
Given the following table definition:

```
create table Log(
id uniqueidentifier primary key default newid(),
name varchar(50) not null,
recordcount int not null,
inserted datetime not null default getdate())
```

and the following scala function:

```
def create(q: Log)(implicit session: DBSession = autoSession): Option[Log] = {
    val id = withSQL {
    insert.into(Log).namedValues(
        column.name -> q.name,
    column.recordcount -> q.recordcount
    )
   }.updateAndReturnGeneratedKey.apply()
    withSQL {
      select.from(Log as c).where.eq(c.id, id)
}.map(Log(c)).single.apply()
}
}
```

The following select statement is generated:

```
   select c.id as i1_on_c, c.name as n_on_c, c.recordcount as r_on_c, c.inserted as i2_on_c from BCCLog c where c.id = 0
```

I noticed that the class SQLUpadateWithGeneratedKey has a return type of Long.  Unless there is some sort of conversion I don't see how this will work with guids.  Is there currently a way to get the generated guid after inserting?

I am working with an MS SQL database, on windows 7. Scalikejdbc 2.2.1.

**Comment by seratch** [comment]
As we are not planning to MS SQL Server, let me close this issue now.
