### ISSUE TITLE
quoting JDBC driver name in project/scalikejdbc.properties

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#344]
ref: https://groups.google.com/forum/#!topic/scalikejdbc-users-group/11WmmQINpCc

**Comment by xuwei-k** [comment]
I still don't understand the problem. could you explain it in more detail?
should we support both 
```
jdbc.driver="the.driver.classname"
```

and

```
jdbc.driver=the.driver.classname
```

?

**Comment by seratch** [comment]
Right. As you said, mapper-generator should work even if config values in scalikejdbc.properties are quoted.
