### ISSUE TITLE
H2 and INSERT column names

### ISSUE THREAD

**Issue by Crafter6432** [scalikejdbc/scalikejdbc#350]
Hello,
I first tried scalikejdbc with mysql so I got no issues at all, but then I tried I got some when not using interpolation:

`org.h2.jdbc.JdbcSQLException: Field "REPORTS" not found
Column "REPORTS" not found; SQL statement:
insert into reports (reports.category, reports.issuer, reports.description, reports.open, reports.timestamp) values ( ?, ?, ?, ?, ?) [42122-184]`

`withSQL {
  insert.into(Report).columns(columnsWithoutId: _*).values(category, issuer, description, open, timestamp)
}.updateAndReturnGeneratedKey().apply()`

The correct SQL command for H2 should look like: `insert into reports (category, issuer, description, open, timestamp) values ( ?, ?, ?, ?, ?)`

**Comment by seratch** [comment]
Use `SQLSyntaxSupport#column` instead.

http://scalikejdbc.org/documentation/query-dsl.html#insert

https://github.com/scalikejdbc/scalikejdbc/blob/2.2.1/scalikejdbc-interpolation/src/main/scala/scalikejdbc/SQLSyntaxSupportFeature.scala#L195

**Comment by Crafter6432** [comment]
I use these columns but as I already mentioned scalikejdbc generates wrong SQL for H2

**Comment by seratch** [comment]
This is a common misunderstanding for beginners. This is a little bit confusing but I'm afraid that your `columnsWithoutId` should be built as follows:

```scala
// object Report extends SQLSyntaxSupport[Report] ...
val r = Report.syntax("report")
val columnsWithoutId = Seq(r.category, r.issuer, r.description, r.open, r.timestamp)
```

You should avoid using `QuerySQLSyntaxProvider`. Use `ColumnSQLSyntaxProvider` instead.

```scala
val r = Report.column
val columnsWithoutId = Seq(r.category, r.issuer, r.description, r.open, r.timestamp)
```

This is what I said above.

**Comment by Crafter6432** [comment]
You're right, it works now :)
