### ISSUE TITLE
loggingSQLErrors should be configurable

### ISSUE THREAD

**Issue by haywood** [scalikejdbc/scalikejdbc#360]
From what I can see, this setting is currently hard-coded to true in [GlobalSettings.scala](https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-core/src/main/scala/scalikejdbc/GlobalSettings.scala#L36). End user's should be able to turn this off, since the error messages may often be spurious. An application may encounter a recoverable SQL error that does not need to be logged.

**Comment by haywood** [comment]
I have just realized that this variable can simply be set to false in code `scalikejdbc.GlobalSettings.loggingSQLErrors = false`. I found this way of overriding the setting very surprising. I was expecting to be able to override it through configuration with `scalikejdbc.global.loggingSQLErrors=false`, similarly to how overriding loggingSQLAndTime settings is described [here](http://scalikejdbc.org/documentation/configuration.html).

**Comment by seratch** [comment]
>I was expecting to be able to override it through configuration with scalikejdbc.global.loggingSQLErrors=false, similarly to how overriding loggingSQLAndTime settings is described here.

It's possible. As described at the end of [this section](http://scalikejdbc.org/documentation/configuration.html#scalikejdbc-config), you can configure that in your application.conf when you use scalikejdbc-config.

```
scalikejdbc.global.loggingSQLAndTime.enabled=true
```

**Comment by armisael** [comment]
Sorry to bother, but from [that section](http://scalikejdbc.org/documentation/configuration.html#scalikejdbc-config) it is not clear that any configuration other than `loggingSQLAndTime` can be changed (in fact, it states "The following settings are available", and the list there refers only to `loggingSQLAndTime`).

Moreover, setting `scalikejdbc.global.loggingSQLErrors=false` doesn't seem to be working. Is there a way to disable such logs? We use [sentry](https://sentry.io/) to track errors, there is one place where we fire some queries and catch exceptions, but we receive those logs anyways, and this is quite frustrating.

Thank you!

**Comment by seratch** [comment]
Ah, at the moment, scalikejdbc-config doesn't support loggingSQLErrors yet. We'd like to support it in the future releases.
