### ISSUE TITLE
dbconsole has errors on Ubuntu

### ISSUE THREAD

**Issue by luciamkh** [scalikejdbc/scalikejdbc#367]
When I execute dbconsole on Ubuntu 12.04, I get the following error:
`$ dbconsole`
`/home/lhuntting/bin/scalikejdbc-cli/dbconsole: 3: /home/lhuntting/bin/scalikejdbc-cli/dbconsole: Syntax error: "(" unexpected`
This is because the shebang line for dbconsole is `#!/bin/sh`.
But on Ubuntu, /bin/sh is a symlink to /bin/dash, not /bin/bash. When I update the shebang line to `#!/bin/bash`, it works as expected. The script should (probably) be updated to use `#!/bin/bash` so that it is compatible on more systems.

**Comment by seratch** [comment]
Thanks. Fixed.
