### ISSUE TITLE
More than one maintainers that can publish sonatype artifacts

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#374]
Currently I am the only maintainer who can release scalikejdbc libs. I'd like to add other developers that can publish artifacts for the `org.scalikejdbc` organization like this:

https://issues.sonatype.org/browse/OSSRH-13198

https://github.com/scalikejdbc/scalikejdbc/blob/develop/team-rules.md#release

**Comment by seratch** [comment]
Tell me your sonatype annount name if you're interested in releasing ScalikeJDBC libs.

**Comment by gakuzzzz** [comment]
Would you add me? my sonatype account is `gakuzzzz`

**Comment by seratch** [comment]
Anyone else?

**Comment by seratch** [comment]
https://issues.sonatype.org/browse/OSSRH-14350

**Comment by seratch** [comment]
Fixed. @gakuzzzz You can publish scalikejdbc libs now.

**Comment by gakuzzzz** [comment]
Thanks, I'll do my best

**Comment by seratch** [comment]
@gakuzzzz Thank you so much. I'll continue working on this project as possible as I can.
If there will be something wrong with me in the future (of course, I don't hope so), please help me.
