### ISSUE TITLE
callable statements API: Need to be able to call stored functions

### ISSUE THREAD

**Issue by naskoboy** [scalikejdbc/scalikejdbc#380]
Hi seratch,

I have been big fan of Querulous and was very excited when I came across your scalikejdbc.
I think I can use it in my projects. However I need somehow to call oracle stored functions having this signature
`MyFunc(d1: datetime, d2: datetime) returns VARCHAR2`

I tried following but it didn't work since I am not allowed to do DMLs in selected function:

``` scala
sql"select test_etl_days($d1, $d2) value FROM dual".map(.string("value")).map(.string(1)).single().apply().get
```

Pls advise how I can do this with scalikejdbc ?
Or (if it's not much trouble for you) to have it implemented as new feature.

Thanks a lot.

**Comment by naskoboy** [comment]
Following code did the trick but I had to resort to raw JDBC constructs.
Would be nice to have more idiomatic way to do this in scalikejdbc.
thanks

      val conn = session.connection
      val stmt = conn.prepareCall("{call ? := test_etl_days (?, ?)}")
      stmt.setDate(2, new Date(d1.toDate.getTime))
      stmt.setDate(3, new Date(d2.toDate.getTime))
      stmt.registerOutParameter(1, java.sql.Types.VARCHAR)
      stmt.execute()
      val res = stmt.getString(1)
      print(res)

**Comment by seratch** [comment]
If there was a cool support of CallableStatement, it will be fine. But basically we won't place the highest priority on it because I'm not a heavy user of stored procedure. If you're interested in sharing API design ideas, implementation or test cases with us, we might be able to move forward.

**Comment by spiu** [comment]
+1, We'd be interested in this too

**Comment by seratch** [comment]
I'd like to use #438 for tracking the progress for the CallbaleStatement feature request. Let me close this issue.
