### ISSUE TITLE
GeneralizedTypeConstraintsForWithExtractor - 2.2.4 not binary compatible with 2.2.2?

### ISSUE THREAD

**Issue by cridmann** [scalikejdbc/scalikejdbc#391]
Hello,

I'm using scalikejdbc in 2 ways - using it as a transitive dependency for https://github.com/dnvriend/akka-persistence-jdbc (which is on scalikejdbc-v2.2.2), and also a more traditional way with Play on scalikejdbc-v2.2.4.  For the more traditional way, I need to be on 2.2.4 due to a recent fix on properly configuring oracle in an external datasource.

When I exclude scalikejdbc as a transitive dependency when including akka-persistence-jdbc:

` "com.github.dnvriend" %% "akka-persistence-jdbc" % "1.1.0" exclude("org.scalikejdbc", "scalikejdbc"),`

I get the following error when starting up akka-persistence-jdbc:
```
java.lang.NoSuchMethodError: scalikejdbc.SQLToList.apply(Lscalikejdbc/DBSession;Lscalikejdbc/ConnectionPoolContext;Lscalikejdbc/GeneralizedTypeConstraintsForWithExtractor$$eq$colon$eq;)Lscala/collection/immutable/List;
	at akka.persistence.jdbc.snapshot.GenericStatements$class.selectSnapshotsFor(Statements.scala:52) ~[akka-persistence-jdbc_2.11-1.1.0.jar:1.1.0]
	at akka.persistence.jdbc.snapshot.OracleSyncSnapshotStore.selectSnapshotsFor(SnapshotStores.scala:16) ~[akka-persistence-jdbc_2.11-1.1.0.jar:1.1.0]
	at akka.persistence.jdbc.snapshot.JdbcSyncSnapshotStore$$anonfun$loadAsync$1.apply(JdbcSyncSnapshotStore.scala:21) ~[akka-persistence-jdbc_2.11-1.1.0.jar:1.1.0]
	at akka.persistence.jdbc.snapshot.JdbcSyncSnapshotStore$$anonfun$loadAsync$1.apply(JdbcSyncSnapshotStore.scala:21) ~[akka-persistence-jdbc_2.11-1.1.0.jar:1.1.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.5.jar:na]
```

From the source code in the plugin, this maps to:
```
  def selectSnapshotsFor(persistenceId: String, criteria: SnapshotSelectionCriteria): List[SelectedSnapshot] =
    SQL(s"SELECT * FROM $schema$table WHERE persistence_id = ? AND sequence_nr <= ? ORDER BY sequence_nr DESC")
      .bind(persistenceId, criteria.maxSequenceNr)
      .map { rs =>
      SelectedSnapshot(SnapshotMetadata(rs.string("persistence_id"), rs.long("sequence_nr"), rs.long("created")),
        Snapshot.fromBytes(Base64.decodeBinary(rs.string("snapshot"))).data)
    }
      .list()
      .apply()
      .filterNot(snap => snap.metadata.timestamp > criteria.maxTimestamp)
```

Are these versions intended to not be compatible?  If so, I suppose I'll open up a ticket with the akka-persistence-jdbc plugin to have them update their version.  If I do that, would their source code have to change?

Thanks!
-Chris

**Comment by seratch** [comment]
>Are these versions intended to not be compatible? If so, I suppose I'll open up a ticket with the akka-persistence-jdbc plugin to have them update their version. If I do that, would their source code have to change?

Some binary incompatibilities are introduced especially in 2.2.4. Source code compatibility are kept (at least we believe so). Sorry for bothering you and akka-persistence-jdbc maintainers, please re-build with 2.2.4.

**Comment by cridmann** [comment]
Okay I will let them know - thanks!
