### ISSUE TITLE
Stack Trace with SQL Server queries

### ISSUE THREAD

**Issue by inash** [scalikejdbc/scalikejdbc#393]
Hi. I'm getting a silent stack trace when debug logging is enabled although the I get the query result as expected. I'm using it in a spray application. Below are the environment details:

Version: 2.2.4
JDBC Driver: SQL Server JDBC 4.0
Scala Version: 2.11.2

    [Stack Trace]
      ...
      scalikejdbc.StatementExecutor.scalikejdbc$StatementExecutor$$stackTraceInformation(StatementExecutor.scala:229)
      scalikejdbc.StatementExecutor$LoggingSQLAndTiming$class.messageInMultiLines$1(StatementExecutor.scala:261)
      scalikejdbc.StatementExecutor$LoggingSQLAndTiming$$anonfun$apply$5.apply(StatementExecutor.scala:282)
      scalikejdbc.StatementExecutor$LoggingSQLAndTiming$$anonfun$apply$5.apply(StatementExecutor.scala:282)
      scalikejdbc.Log.debug(Log.scala:45)
      scalikejdbc.Log.withLevel(Log.scala:35)
      scalikejdbc.StatementExecutor$LoggingSQLAndTiming$class.apply(StatementExecutor.scala:282)
      scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLIfFailed$$super$apply(StatementExecutor.scala:321)
      scalikejdbc.StatementExecutor$LoggingSQLIfFailed$class.apply(StatementExecutor.scala:298)
      scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:321)
      scalikejdbc.StatementExecutor.executeQuery(StatementExecutor.scala:337)
      scalikejdbc.DBSession$$anonfun$traversable$1.apply(DBSession.scala:311)
      scalikejdbc.DBSession$$anonfun$traversable$1.apply(DBSession.scala:311)
      scalikejdbc.LoanPattern$class.using(LoanPattern.scala:33)
      scalikejdbc.ActiveSession.scalikejdbc$DBSession$$super$using(DBSession.scala:562)
      scalikejdbc.DBSession$class.using(DBSession.scala:44)
      scalikejdbc.ActiveSession.using(DBSession.scala:562)
      scalikejdbc.DBSession$class.traversable(DBSession.scala:310)
      scalikejdbc.ActiveSession.traversable(DBSession.scala:562)
      scalikejdbc.DBSession$class.collection(DBSession.scala:266)
      scalikejdbc.ActiveSession.collection(DBSession.scala:562)
      scalikejdbc.DBSession$class.list(DBSession.scala:252)
      scalikejdbc.ActiveSession.list(DBSession.scala:562)
      scalikejdbc.SQLToList$class.result(SQL.scala:654)
      scalikejdbc.SQLToListImpl.result(SQL.scala:666)
      scalikejdbc.SQLToListImpl.result(SQL.scala:666)
      scalikejdbc.SQLToResult$$anonfun$9.apply(SQL.scala:551)
      scalikejdbc.SQLToResult$$anonfun$9.apply(SQL.scala:551)
      scalikejdbc.SQLToResult$class.apply(SQL.scala:557)
      scalikejdbc.SQLToListImpl.apply(SQL.scala:666)
      com.bml.actor.data.OtpDataActor$$anonfun$receive$1$$anonfun$1.apply(OtpDataActor.scala:26)
      com.bml.actor.data.OtpDataActor$$anonfun$receive$1$$anonfun$1.apply(OtpDataActor.scala:21)
      scalikejdbc.DBConnection$class.readOnly(DBConnection.scala:206)
      scalikejdbc.DB.readOnly(DB.scala:75)
      scalikejdbc.DB$$anonfun$readOnly$1.apply(DB.scala:188)
      scalikejdbc.DB$$anonfun$readOnly$1.apply(DB.scala:187)
      scalikejdbc.LoanPattern$class.using(LoanPattern.scala:33)
      scalikejdbc.DB$.using(DB.scala:153)
      scalikejdbc.DB$.readOnly(DB.scala:187)
      com.bml.actor.data.OtpDataActor$$anonfun$receive$1.applyOrElse(OtpDataActor.scala:21)
      scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
      akka.event.LoggingReceive.apply(LoggingReceive.scala:62)
      akka.event.LoggingReceive.apply(LoggingReceive.scala:50)
      scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
      akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50)
      akka.actor.Actor$class.aroundReceive(Actor.scala:465)
      com.bml.actor.data.OtpDataActor.aroundReceive(OtpDataActor.scala:15)
      akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
      akka.actor.ActorCell.invoke(ActorCell.scala:487)
      akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
      akka.dispatch.Mailbox.run(Mailbox.scala:220)
      akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
      scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
      scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
      scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
      scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
      ...

**Comment by seratch** [comment]
This debug logging itself is normal behavior. http://scalikejdbc.org/documentation/query-inspector.html
Do you mean the stack trace in your case is not useful enough?
Actually the stack trace looks unexpected for me.

**Comment by inash** [comment]
I didn't know that. If that's the case there is no issue here. I assumed the stack trace was related with an exception of some sort. Thanks.
