### ISSUE TITLE
bind collection(List, Set, etc.) as parameter in "IN" filter

### ISSUE THREAD

**Issue by naskoboy** [scalikejdbc/scalikejdbc#416]
Hi seratch,

I need to do something like this:

    sql"SELECT something FROM MyTable WHERE id IN (?)".bind(someList)
someList is relatively small (few dozens of things) so "IN" makes perfect sense.
I get "Invalid column type" error right now.
What would be the best way to do it in scalikejdbc ?
Would be great if scalikejdbc injects/unfolds properly the list for me.
Help appreciated.

**Comment by naskoboy** [comment]
Checked bindParameters method. It suggests that I should use `java.sql.Array` type.
Unfortunately this code

    sql"SELECT something FROM MyTable WHERE id IN (?)".bind(session.connection.createArrayOf("VARCHAR", Array("aaa")))

in Oracle throws `java.sql.SQLException: Unsupported feature
	at oracle.jdbc.driver.PhysicalConnection.createArrayOf(PhysicalConnection.java:9283)`

**Comment by naskoboy** [comment]
I see ... I need to implement my own ParameterBinder.
All set.
Thanks

**Comment by naskoboy** [comment]
Few more observations people may find useful:
1) Oracle JDBC does not support JDBC `createArrayOf` so you have to use Oracle's proprietary 'createARRAY'
2) In Oracle all table types are named and have to be created as a type in advance.

`create type varchar2_table is table of varchar2(100)`
and then ...
```
  def binder = if (elements.isInstanceOf[Set[String]])
    new ParameterBinder[Set[String]] {
      override val value = Set[String]()
      override def apply(stmt: PreparedStatement, idx: Int): Unit = {
        val ops = stmt.asInstanceOf[OraclePreparedStatement]
        val oconn = ops.getConnection.asInstanceOf[OracleConnection]
        val arr = oconn.createARRAY("COGNOS.VARCHAR2_TABLE", elements.asInstanceOf[Set[String]].toArray)
        ops.setARRAY(idx, arr)
      }
  }
  else throw new RuntimeException("Unsuported parameterBinder in discreteDelta.")
...
sql("SELECT * FROM MyTable WHERE someField IN (SELECT * FROM TABLE(?))").bind(binder _).execute().apply()(session)
```
3) "value" field in ParameterBinder trait doesn't make sense ... so it's being deprecated
4) When calling createARRAY, type-name parameter must be in UpperCase.

I wasted almost 1 day on these issues, hope this helps others.
At any rate - scalikejdbc is a wonderful library
Good luck.

**Comment by seratch** [comment]
Thanks for sharing.
