### ISSUE TITLE
mysql delete from syntax error with table alias

### ISSUE THREAD

**Issue by intracer** [scalikejdbc/scalikejdbc#422]
scalikejdbcVersion is  "2.2.6"

Driver is Mysql

```scala
Class.forName("com.mysql.jdbc.Driver")
val url = "jdbc:mysql://$host/$db"
```

Code

```scala
def deleteImage(pageId: Long)(implicit session: DBSession = autoSession): Unit = withSQL {
  delete.from(ImageJdbc as c).where.eq(c.pageId, pageId)
}.update().apply()
```

Sql generated and error statement

```
ERROR s.StatementExecutor$$anon$1 - SQL execution failed (Reason: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'c  where  c.page_id = 40067891' at line 1):

   delete from images c where c.page_id = 40067891
```

See http://stackoverflow.com/questions/6518964/error-using-table-alias for syntax variants

You can avoid this error by writing this way

```scala
delete.from(ImageJdbc).where.eq(ImageJdbc.column.pageId, pageId)
```

**Comment by seratch** [comment]
Yeah, this can be a pitfall for new comers. But `delete.from(ImageJdbc).where.eq(ImageJdbc.column.pageId, pageId)` works for you. I've not figured out your issue yet. Any other problems?

**Comment by intracer** [comment]
It could compile to DELETE a FROM tablename a WHERE a.fieldname ... instead of compiling to non-working SQL. The code that works feels as a  workaround.

**Comment by seratch** [comment]
Some RDBMS (e.g. H2 database) accepts both of them.  I'm not planning this QueryDSL's API right now.

**Comment by seratch** [comment]
We don't have no more action for this issue at least right now. Let me close this issue if you don't have more points to discuss here.
