### ISSUE TITLE
StatementExecutor.bindParams uses current time zone

### ISSUE THREAD

**Issue by xiaodongw** [scalikejdbc/scalikejdbc#424]
StatementExecutor.bindParams uses current time zone, which is error prone, if you read the database on another machine with different timezone, you will get the wrong time.

It should be better to provide a default timezone, so any time written to database will be read/written as this timezone.

**Comment by seratch** [comment]
IMO, just being careful not to drop timezone from datetime values is not so difficult.
But if you have a good idea to help library users in use cases that you're worried, make a pull request toward library implementation or documentation on our website.
