### ISSUE TITLE
Cached result column names

### ISSUE THREAD

**Issue by propi** [scalikejdbc/scalikejdbc#439]
```BasicResultNameSQLSyntaxProvider``` provides caching for the ```field``` method. Why is not ```column``` method cached as well? If I call a non cached method within this class many times during listing of rows, the whole process is very slow.

**Comment by seratch** [comment]
#columns and #colum(String) are cached. See SQLSyntaxSupportFeature.SQLSyntaxSupportLoadedColumns. https://github.com/scalikejdbc/scalikejdbc/blob/2.2.8/scalikejdbc-interpolation/src/main/scala/scalikejdbc/SQLSyntaxSupportFeature.scala#L124-L134

**Comment by propi** [comment]
Yes of course this method is cached, but i mean the ```column``` method in ```BasicResultNameSQLSyntaxProvider```. It contains this piece of code: ```columns.find(_.value.equalsIgnoreCase(name)).map ...``` - I think that here is the problem, because this operation might not have a constant time. So I tested both methods: ```column``` and ```field``` for listing more than 6000 records. The ```field``` method took about 200ms, but the ```column``` method more than 1200ms.

**Comment by seratch** [comment]
I see. Indeed, that should be improved.
