### ISSUE TITLE
Provide more data in Metadata classes

### ISSUE THREAD

**Issue by lauris** [scalikejdbc/scalikejdbc#441]
I was checking Index class from Metadata and found some data missing. Doesn't JDBC provide more info about indexes?

For example, Index provides only three fields: name, columnNames and isUnique.
```case class Index(name: String, columnNames: List[String], isUnique: Boolean)```

Things that seem to be missing and would be handy:
Seq_in_index
Collation
Cardinality
Sub_part
Packed
Null
Index_type
Comment
Index_comment

Do you think it would be possible to add missing fields to Index?

**Comment by lauris** [comment]
After a quick search, I found that Indexes are created [here](https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-core/src/main/scala/scalikejdbc/DBConnection.scala#L451-L468). It seems that it would be trivial to add missing information, e.g.,

```scala
Index(name = indexName,
    columnNames = List(rs.string("COLUMN_NAME")),
    isUnique = !rs.boolean("NON_UNIQUE"),
    cardinality = rs.getInt("CARDINALITY"),
    // more fields here...
)
```

**Comment by seratch** [comment]
Supporting other attributes that are available for both of PostgreSQL and MySQL would be reasonable. Are you interested in working on this? At this time, I'm a bit busy with my day job and improving other OSS projects. If you help us, that'll be much appreciated.

**Comment by lauris** [comment]
Yes, I will have a look and try to submit a PR soon.

**Comment by seratch** [comment]
@lauris I just added more attributes to index information at #491. If you have any comments, please let me know.
