### ISSUE TITLE
Support setting standard transaction isolation levels through API

### ISSUE THREAD

**Issue by dinoboy197** [scalikejdbc/scalikejdbc#442]
It would be great if, when calling `localTx` or other methods to start a transaction, I could specify one of the standard transaction isolation levels to use rather than the database default.

Ex:

```
NamedDB('readwrite, 'repeatable-read).localTx( { implicit session =>
        // set transaction isolation set to repeatable read
})

NamedDB('readwrite, 'serializable).localTx( { implicit session =>
        // set transaction isolation set to serializable
})
```

**Comment by BardurArantsson** [comment]
@seratch Was this, or something like it ever implemented?

(I may be interested in giving it a go since we may need it at $MY_COMPANY.)

**Comment by BardurArantsson** [comment]
@seratch Ping?

**Comment by seratch** [comment]
Sorry for my late response. In my opinion, the proposed API which has isolation level name as a Symbol value may not the best. 

Doing as below looks reasonable.

```scala
import scalikejdbc._
import scalikejdbc.IsolationLevel.RepeatableReads

DB.isolationLevel(RepeatableReads).localTx { implicit session =>

}

NamedDB('somedb).isolationLevel(RepeatableReads).localTx { implicit session =>

}
```

**Comment by BardurArantsson** [comment]
Yeah, I was thinking the same -- avoiding Symbol, that is.

I think I may have a pull request for this soonish. (It's been a while since looking at the code, so I'll have to re-familiarize myself with it.)

**Comment by timzaak** [comment]
the way to change isolation level is `DB(ConnectionPool.borrow()).isolationLevel(IsolationLevel.Serializable).localTx(...)`
