### ISSUE TITLE
Add support of java.time.Instant parameters

### ISSUE THREAD

**Issue by daring2** [scalikejdbc/scalikejdbc#451]
In the current implementation (version 2.2.9) if I pass java.time.Instant object as parameter to SQL statement I get MatchError from StatementExecutor#bindParams method.

I think it would be useful if java.time.Instant and maybe joda Instant are supported in parameters. 

I can create a pull request if needed.

**Comment by seratch** [comment]
Supporting Instant too looks fine to me. Would you please make a pull request on this?

**Comment by daring2** [comment]
pull request #452
