### ISSUE TITLE
Improvements for binary compatibility in 2.3 series

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#453]
2.3.x development cycle started.

https://github.com/scalikejdbc/scalikejdbc/pull/450#issuecomment-147744826

I think there are some technique for improve binary-compatibility keepability.

- should we change some `trait` to `(sealed) abstract class`?
- more restrict access some methods and classes? (e.g. `public` => `private[scalikejdbc]`, `private` => `private[this]`)

any opinions?

**Comment by seratch** [comment]
Sound great.

Hiding existing public members from users may bring source code incompatibility for existing code base. However, if the hidden things are not so important or useful in most cases, I think doing so is acceptable enough.

**Comment by seratch** [comment]
2.3.0 has been released and MiMa settings is properly working thanks to Kenji's work https://github.com/scalikejdbc/scalikejdbc/pull/458.
