### ISSUE TITLE
Can not understand how to disable logging

### ISSUE THREAD

**Issue by roma86** [scalikejdbc/scalikejdbc#459]
Thank you for scalikejdbc and scalikejdbc-config

from docs and readme: 

> The following settings are available.
> scalikejdbc.global.loggingSQLAndTime.enabled=true
> scalikejdbc.global.loggingSQLAndTime.logLevel=info
> ...

My sbt config

```scala
    val scalikejdbcV = "2.2.9"
    "postgresql" % "postgresql" % "9.1-901-1.jdbc4",
    "org.scalikejdbc" %% "scalikejdbc" % scalikejdbcV,
    "org.scalikejdbc" %% "scalikejdbc-config" % scalikejdbcV
```

and configuration file
> spray/src/main/resources/application.conf

```scala
db {
  db_dev {
    driver = org.postgresql.Driver
    url = "jdbc:postgresql://localhost:5432/scala"
    user = User
    password = User

    poolInitialSize=10
    poolMaxSize=20
    poolConnectionTimeoutMillis=1000
    poolValidationQuery="select 1 as one"
    poolFactoryName="commons-dbcp"
  }

  db_test {
    driver = org.postgresql.Driver
    url = "jdbc:postgresql://localhost:5432/scala_test"
    user = User
    password = User

    poolInitialSize=10
    poolMaxSize=20
    poolConnectionTimeoutMillis=1000
    poolValidationQuery="select 1 as one"
    poolFactoryName="commons-dbcp"
  }
}

scalikejdbc.global.loggingSQLAndTime.enabled=false
```
And last line has no effect.

I was try move this settings into `db` block or `db_test` - no matter.

In console output i still have logging like so

> DEBUG s.StatementExecutor$$anon$1 - SQL execution completed
> [SQL Execution]
> SELECT * FROM countries WHERE id = 2; (0 ms)
> 
> [Stack Trace]
> . . .
> com.application.db.dao.CountryDao$$anonfun$getById$1.apply(CountryDao.scala:66)
> com.application.db.dao.CountryDao$$anonfun$getById$1.apply(CountryDao.scala:56)
> . . .

What i am doing wrong?

Is it possible disable `[Stack Trace]` section and live [SQL Execution] only?

**Comment by tkawachi** [comment]
I'm not sure why it doesn't work in your case, though, in general:

> I was try move this settings into db block or db_test - no matter.

`scalikejdbc.global.loggingSQLAndTime.enabled` should be placed at the top level.

> scalikejdbc.global.loggingSQLAndTime.singleLineMode=false
http://scalikejdbc.org/documentation/configuration.html

This is the configuration to show only one line per sql execution.

**Comment by tkawachi** [comment]
It might give a hint by checking whether Typesafe config library reads the `application.conf` properly. because scalikejdbc-cofig internally uses Typesafe config.

The following line will print the configuration if it reads the `application.conf` properly.

```
println(com.typesafe.config.ConfigFactory.load().getConfig("scalikejdbc"))
```

**Comment by roma86** [comment]
@tkawachi, thank you for answer.

i added new config line to Typesafe config file:
```scala
scalikejdbc.global.loggingSQLAndTime.enabled=false
scalikejdbc.global.loggingSQLAndTime.singleLineMode=true
```
and logging output 

```scala
println("----------- ----------- ----------- ")
println(com.typesafe.config.ConfigFactory.load().getConfig("scalikejdbc"))
println("----------- ----------- ----------- ")
```

Result is:

> spray_api ----------- ----------- -----------
> spray_api Config(SimpleConfigObject({"global":{"loggingSQLAndTime":{"enabled":false,"singleLineMode":true}}}))
> spray_api ----------- ----------- -----------
> spray_api [INFO] [11/17/2015 09:03:34.359] [on-spray-can-akka.actor.default-dispatcher-3] [akka://on-spray-can/user/IO-HTTP/listener-0] Bound to localhost/127.0.0.1:8001
> spray_api 09:03:44.925 [on-spray-can-akka.actor.default-dispatcher-3] DEBUG scalikejdbc.ConnectionPool$ - Borrowed a new connection from ConnectionPool(url:jdbc:postgresql://localhost:5432/scala, user:User)
spray_api 09:03:45.506 [on-spray-can-akka.actor.default-dispatcher-3] DEBUG s.StatementExecutor$$anon$1 - SQL execution completed
> spray_api
> spray_api   [SQL Execution]
> spray_api    SELECT * FROM countries; (1 ms)
> spray_api
> spray_api   [Stack Trace]
> spray_api     ...
> spray_api     com.application.db.dao.CountryDao$$anonfun$all$1.apply(CountryDao.scala:98)
> ... And so on

For me it looks like config reads correctly, but not working for some reason.

**Comment by tkawachi** [comment]
Are you using `DBs.setupAll()` ? `DBs.setup()` doesn't load configurations under `scalikejdbc.global.`.

https://github.com/scalikejdbc/scalikejdbc/blob/cd2374d3da60d939a90934274c3af0dc6c1d76a6/scalikejdbc-config/src/main/scala/scalikejdbc/config/DBs.scala#L18

**Comment by roma86** [comment]
Here is it.
I am sure that I use DBs.setup('db_label) and not setupAll. 
The reason of that – icould not conclude from the documentation it affects on global settings. 
Thank you for you help.

**Comment by hartmut27** [comment]
Even this issue is closed now, I want to mention, that in my case, `scalikejdbc.global.loggingSQLAndTime` settings were not responsible for the too excessive looging output, but the configuration of the `ch.qos.logback.classic` SL4J logging implementation was. (build.sbt: `libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.2.3"`)

`LoggerFactory.getLogger("scalikejdbc").asInstanceOf[Logger].setLevel(Level.WARN)`
did the trick, to suppress those debug log entries:
`00:05:07.072 [main] DEBUG scalikejdbc.StatementExecutor - The parameter([2015-01-01,2016-01-01)) is bound as an Object.`

**Comment by seratch** [comment]
As far as I know, the global settings work for most cases even if you use logback-classic. I used to use logback as the slf4j implementation in many projects but I didn't see the problem you raised. I'm afraid that there is some additional condition to reproduce your situation rather than just using logback.

**Comment by hartmut27** [comment]
just as little additional information: The problem occured only then, when I began to use "org.postgresql.util.PGobject" object representation for a PostgreSQL daterange (date interval from...to...) comparison.  `zeitraum` on PostgreSQL DB is typed "daterange",  in Scala it is typed as "PGobject".

`... sql"""select * from mytable where zeitraum = ${zeitraum}""".map(...) ...`

This produced the logger (spam) entry `The parameter([2015-01-01,2016-01-01)) is bound as an Object` as mentioned above.
