### ISSUE TITLE
Can not find NamedReadOnlyAutoSession

### ISSUE THREAD

**Issue by luminescent** [scalikejdbc/scalikejdbc#460]
Hi 

I would like to use the NamedReadOnlyAutoSession as explained in the documentation here: http://scalikejdbc.org/documentation/auto-session.html however I can not find NamedReadOnlyAutoSession anywhere in the source code; the only hit searching for this string in the source code was in the test spec and it looks like it is outdated. 
Has it been replaced with something else? If so, what should I be using now? 

Thank you.

**Comment by luminescent** [comment]
Took a closer look at the test and this is the correct name: ReadOnlyNamedAutoSession . Perhaps you'd like to update the documentation page and the test spec with the correct name.

**Comment by seratch** [comment]
Thanks. As you suggested, it seems to be a mistake on documentation. If you have time, would you make a pull request to fix this? https://github.com/scalikejdbc/scalikejdbc.github.io

**Comment by luminescent** [comment]
Hi. I have done the pull requests for name fixes. Had to submit 2 pull requests:
*  for the documentation repository
*  for the code base, as one of the test specs was mentioning the wrong name.

**Comment by seratch** [comment]
Thanks.
