### ISSUE TITLE
java.sql.SQLException: Cannot get a connection, pool error Unable to validate object

### ISSUE THREAD

**Issue by akamaus** [scalikejdbc/scalikejdbc#461]
Following "First example" on scalikejdbc main page I encountered the following error when tried to execute sql:
``` 
java.sql.SQLException: Cannot get a connection, pool error Unable to validate object
  at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:142)
  at scalikejdbc.Commons2ConnectionPool.borrow(Commons2ConnectionPool.scala:41)
  at scalikejdbc.DB$.autoCommit(DB.scala:214)
  at scalikejdbc.SQLExecution.apply(SQL.scala:504)
```

Looks like it occurs because underlying dbcp2  pool is always created with testOnBorrow property set to true in Commons2ConnectionPool.scala but validationQuery is null in default pool settings.

**Comment by seratch** [comment]
Indeed, testOnBorrow is set as true by default. However, when validationQuery is absent, dbcp2 should work without connection validation.

I just tried to reproduce your issue but I couldn't see the same situation for now and I've never seen such a trouble. If you have time, please share us a minimum working example to show your issue.

**Comment by seratch** [comment]
Fixed. 2.3.1 will be out soon.

**Comment by seratch** [comment]
Sorry my mistake.

**Comment by stevewillcock** [comment]
I get the same issue with the following simple program:

build.sbt:

```
name := "gp-sql-loader"

version := "1.0"

scalaVersion := "2.11.7"


libraryDependencies +=  "org.scalikejdbc" %% "scalikejdbc"       % "2.3.3"
libraryDependencies +=  "ch.qos.logback"  %  "logback-classic"   % "1.1.3"

libraryDependencies += "net.sourceforge.jtds" % "jtds" % "1.3.1"

```

Main.scala

```
import scalikejdbc._

object Main {

  def main(args: Array[String]) = {

    Class.forName("net.sourceforge.jtds.jdbc.Driver")

    ConnectionPool.singleton("jdbc:jtds:sqlserver://localhost:1433/db-name-here", "sa", "password-here")

    val tableNames = DB readOnly { implicit session =>
      sql"SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES".map(rs => rs.string("TABLE_NAME")).list.apply()
    }


  }

}

```

This works as expected if I set the scalikejdbc version back to 2.2.9 in build.sbt but fails with 2.3.0 and later.

This issue does not appear when connecting to a postgres database (using "org.postgresql" % "postgresql" % "9.4.1207.jre7"). I have only seen it when connecting to MS SQL Server (using the jtds driver). I have replicated the issue using both Windows 10 and Ubuntu 14.04 to connect to MS SQL Server using the jtds driver.

**Comment by seratch** [comment]
@stevewillcock Thank you for your concise and clear explanation. I just fixed this issue by #475 and published the fixed version as 2.3.4-SNAPSHOT. Would you try it out when you have time?

```
resolvers += "sonatype snaphots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.scalikejdbc" %% "scalikejdbc" % "2.3.4-SNAPSHOT"
```

**Comment by stevewillcock** [comment]
@seratch thanks for the super quick response - I've tried that snapshot dependency and that works fine in my situation here.

**Comment by seratch** [comment]
@stevewillcock Thanks. That's great. I'll merge the change and will publish next minor version as soon as possible.

**Comment by stevewillcock** [comment]
Brilliant, thanks for that :)
