### ISSUE TITLE
Sql.batchByName throws an exception on empty parameters list

### ISSUE THREAD

**Issue by akamaus** [scalikejdbc/scalikejdbc#465]
After investigating multiple issues looking like following 
```
Exception occured:
java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:420)
        at scala.collection.immutable.Nil$.head(List.scala:417)
        at scalikejdbc.SQL.batchByName(SQL.scala:254)
```
I realized there is a head being used in Sql.batchByName which fails on empty parameter list. Is it proper behavior? I have a strong feeling that such iterating operations should do nothing then parameter is empty, not fail. After all it's just an optimization and can be rewritten as a for loop which would happily process empty lists.

**Comment by seratch** [comment]
Thank you for your feedback. Yes, I agree this behavior is so surprizing for library users. I just created a pull request to fix this issue. Take a look if you have time.

**Comment by seratch** [comment]
2.3.1 will be out soon.
