### ISSUE TITLE
SQL interpolation behaves unexpectedly when passed a Java collection

### ISSUE THREAD

**Issue by admackin** [scalikejdbc/scalikejdbc#469]
If you accidentally end up with a Java collection and forget to convert it to a Scala collection, you get very confusing behaviour. The collection is happily accepted, but not unpacked, and just used (presumably) as an opaque POJO:

    scala> import collection.JavaConverters._
    import collection.JavaConverters._

    scala> sql"""update foo set bar=1 where id in (${Set(1, 2, 3)})""".statement
    res5: String = update foo set bar=1 where id in (?, ?, ?)

    scala> sql"""update foo set bar=1 where id in (${Set(1, 2, 3).asJava})""".statement
    res6: String = update foo set bar=1 where id in (?)

Note that the Java collection (the second one) doesn't unpack the Java set instance. I presume this applies to other collection types. I'm not sure if this should accept a Java collection or throw an exception (or maybe print a warning), but the current behaviour of trying to directly interpolate the opaque Java object without iterating through it is likely to end up in confusion (we end up with Java collections by accident all the time, but usually type checking in compilation finds these. However in this case you just get painful debugging where you wonder what's wrong with your query).

**Comment by seratch** [comment]
Thank you for your feedback. Also accepting Java collection values looks better for me. This issue can be easily fixed: https://github.com/scalikejdbc/scalikejdbc/blob/2.3.2/scalikejdbc-core/src/main/scala/scalikejdbc/SQLInterpolationString.scala#L26-L39
