### ISSUE TITLE
How do I escape special symbol in SQL interpolation ?

### ISSUE THREAD

**Issue by cppexpert** [scalikejdbc/scalikejdbc#485]
How do I escape special symbol in SQL interpolation ?

I have following query

```
select * from articles where json_raw->'scopus_subjects' ? 'Veterinary';
```

I tried

```scala
    val questionmark = SQLSyntax.createUnsafely("?")
    sql"""select * from articles where json_raw->'scopus_subjects' $questionmark $subject""".map(rs => Article(rs)).list()()
```

I get following error

```
2016-01-26 13:42:53.062 +0300 ERROR SQL execution failed (Reason: No value specified for parameter 2.):

   select * from articles where json_raw->'scopus_subjects' 'Dentistry' ?

Exception in thread "main" org.postgresql.util.PSQLException: No value specified for parameter 2.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:228)

```

**Comment by seratch** [comment]
You cannot escape question marks in JDBC prepared statement. Consider using another equivalent syntax instead. FYI: http://stackoverflow.com/questions/11940401/escaping-hstore-contains-operators-in-a-jdbc-prepared-statement

**Comment by cppexpert** [comment]
Unfortunately it doesn't work for JSONB columns. Any another options ?

Why not allow double-quesitonmark to escape it ?

**Comment by seratch** [comment]
I've never tried yet but ?? looks available with latest jdbc driver.
https://jdbc.postgresql.org/documentation/head/statement.html

**Comment by cppexpert** [comment]
WOW! I thought it has to be taken care of in scalikejdbc level. Thanks!

**Comment by irhere** [comment]
I just tried ?? with pgjdbc 9.4-1208 without much success with though. Maybe someone else had more luck?
