### ISSUE TITLE
Blocking within the global ExecutionContext must be avoided

### ISSUE THREAD

**Issue by backuitist** [scalikejdbc/scalikejdbc#486]
https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-core/src/main/scala/scalikejdbc/ConnectionPool.scala#L109

See http://docs.scala-lang.org/overviews/core/futures.html#blocking

Not only you instanciate the (lazy) global ExecutionContext (it might not have been used before) but you're blocking inside the Future (with a `Thread.sleep`).

**Comment by seratch** [comment]
OK. Indeed, wasting a thread managed by global context is not good. Should be improved.

**Comment by backuitist** [comment]
Should be ~~improved~~ *fixed*.

I think many people underestimate how bad this situation is. That's why I submitted a [PR](https://github.com/scala/scala.github.com/pull/304/files) for the scala Future documentation:

> `ExecutionContext.global` is an `ExecutionContext` backed by a [ForkJoinPool](http://docs.oracle.com/javase/tutorial/essential/concurrency/forkjoin.html). 
> It should be sufficient for most situations but requires some care.
> A `ForkJoinPool` manages a limited amount of threads (the maximum amount of thread being referred to as *parallelism level*). 
> The number of concurrently blocking computations can exceed the parallelism level
> only if each blocking call is wrapped inside a `blocking` call (more on that below).
> Otherwise, there is a risk that the thread pool in the global execution context is starved,
> and no computation can proceed.

Note that the *parallelism level* is configured to the amount of cores of your computer. Meaning if you're running on a single core computer, you'll get a single thread...
In worst case scenario you could end-up deadlocking your application.

So you can easily fix this by wrapping your code in a `blocking` block. But then you'll trigger the creation of the global EC. This is a major side effect IMO. The only clean way is to parameterize your method with an EC.

**Comment by seratch** [comment]
The `abandonOldPool` method is rarely called in typical use cases. But your correction is right in general. Thanks.

Having own default EC with a small thread pool in this class and parameterizing EC too would be fine to me.
