### ISSUE TITLE
Querying for boolean field in parameterised query gives true when it should be false (from MySQL)

### ISSUE THREAD

**Issue by admackin** [scalikejdbc/scalikejdbc#493]
I'm getting incorrect results for boolean fields. I've tested against Mysql 5.7.9, using both Mysql and MariaDB JDBC drivers, with scalikejdbc version 2.3.5. When you query for a boolean field which has a value of `false`, it somehow ends up as `true`, but this only happens when there is a parameter in the query. I've traced it through in a debugger somewhat, and ended up deep in the internals of scalikejdbc before it confused me too much. It seemed that the correct result was coming from the DB, and I can't work how it ends up as the wrong value in the processing.  I've created a minimal test case below which reliably reproduces the issue for me. If you run this you should see that the test case marked as 'FAILS' doesn't work and you get the following output:

> Got: Some(true); expected: Some(false) for 'SELECT flag FROM boolcheck WHERE name = ?' with params List(B)

(Note that it works fine with a hardcoded parameter though)

This seems fairly serious though, and I would have thought it would have come up for others, so I wonder if there is something about my setup which is a contributing factor.
Here is the test code in any case. Let me know if I can provide more information.

    package com.example
    import scalikejdbc._
    import scalikejdbc.config.DBs

    object ScalikejdbcBoolsTest  {

      def run() = {
        DBs.setupAll()
        implicit val session = AutoSession

        try {
          sql"""
            CREATE TABLE boolcheck(
              name VARCHAR(1) NOT NULL,
              flag BOOLEAN NOT NULL,
              PRIMARY KEY (name)
            )
         """.update().apply()

          val insertable = Seq(("A", true), ("B", false))
          insertable foreach { case (name, flag) =>
            sql"INSERT INTO boolcheck(name, flag) VALUES ($name, $flag)".update().apply()
          }

          val a = "A"
          val b = "B"
          val c = "C"
          val testCases = Seq(
            sql"SELECT flag FROM boolcheck WHERE name = 'A'" -> Some(true),
            sql"SELECT flag FROM boolcheck WHERE name = $a" -> Some(true),
            sql"SELECT flag FROM boolcheck WHERE name = 'B'" -> Some(false),
            sql"SELECT flag FROM boolcheck WHERE name = $b" -> Some(false), #FAILS!
            sql"SELECT flag FROM boolcheck WHERE name = 'C'" -> None,
            sql"SELECT flag FROM boolcheck WHERE name = $c" -> None
          )

          testCases foreach { case (query, expected) =>
            val res = query.map(_.boolean(1)).single().apply()
            if (res != expected)
              System.err.println(s"Got: $res; expected: $expected for '${query.statement}' with params ${query.parameters}")
          }
        } finally {
          sql"DROP TABLE IF EXISTS boolcheck".update().apply()
        }

      }

      def main(args: Array[String]) {
        run()
      }

    }

**Comment by seratch** [comment]
I just tried to reproduce your issue but couldn't. 

- https://travis-ci.org/seratch/scalikejdbc/builds/108506857
- https://github.com/seratch/scalikejdbc/commit/fdbe5aa96d83f76881c5dc231566d134d5214ec5

**Comment by tkawachi** [comment]
IIRC, the same issue was reported somewhere with reproducible source code. It was an issue when connecting MySQL with MariaDB JDBC driver.

**Comment by tkawachi** [comment]
It was reported for Skinny ORM https://github.com/skinny-framework/skinny-framework/issues/305.

**Comment by seratch** [comment]
@tkawachi Thanks. I've forgotten about this issue report :sweat:

**Comment by seratch** [comment]
> using both Mysql and MariaDB JDBC drivers,

@admackin I had overlooked this part. This should be a known issue on JDBC driver side. Please ask them to fix the behavior. https://github.com/skinny-framework/skinny-framework/issues/305#issuecomment-167696517

**Comment by admackin** [comment]
Oh, I see, so it  surfaces when both mariaDB and Mysql JDBC drivers are in your classpath, even when you use the MySQL client? Very strange, although that would explain why it's occurring in my project but I can't reproduce it with your new test case on my machine. I'm not sure where the problem is with mariadb-connector-j though, so I'm not sure how to report it. As I said, the value coming from the DB seems correct most of the way through. I'm not sure if you have any idea where I could look in scalikejdbc to work out where MariaDB goes wrong. The fact that it only occurs with bound parameters is definitely a clue.

**Comment by admackin** [comment]
I agree that the boolean handling is not the fault of scalikejdbc, but as noted at #494, it seems like the `driver` setting has no effect (which is why I continued to see the problem when I simply added MySQL JDBC connector to my classpath instead of replacing MariaDB)
