### ISSUE TITLE
"driver" setting in config for DB has no effect

### ISSUE THREAD

**Issue by admackin** [scalikejdbc/scalikejdbc#494]
Inspired by the fun I've been having over at #493, I've been investigating setting the target JDBC driver class using the `driver` config item described in the documentation. As far as I can tell, this setting has no effect (apart from choking if the requested class name cannot be found when `Class.forName` is called). This is because the setting is never passed through to or used by the [DriverManagerConnectionFactory](https://commons.apache.org/proper/commons-dbcp/apidocs/org/apache/commons/dbcp2/DriverManagerConnectionFactory) -- and indeed, I think that there is no way I can see to actually do so with that particular class (or with the equivalent class in BoneCP, if you select that as your pool manager).

Instead, the JDBC implementation is selected within [DriverManager.getConnection](dmgc). Here, there are arbitrarily ordered JDBC implementations found on the classpath according to the JDBC 4 spec, and the first which thinks it can handle the URL is selected. For most users, this means that they see the correct behaviour in any case, **unless** you have two JDBC implementations in your classpath which are able to talk to the same database (eg MariaDB and MySQL JDBC connectors), when you might very well get the MariaDB implementation even when you specified `db.default.driver` as `org.mysql.jdbc.Driver` in your settings. This is probably an uncommon scenario, but is particularly confusing, especially if you're also running into a bug with the underlying JDBC implementation, as happened at #493 and  skinny-framework/skinny-framework#305. 

[dmgc]: https://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html#getConnection(java.lang.String,%20java.lang.String,%20java.lang.String)

The simplest fix IMO would be to update the documentation if the setting does indeed have no effect (although I may be wrong of course), and if it is not needed, to simply abandon it – just tell users to have a JDBC implementation which can handle that URL in their classpath. 

I think if you do want to specifically request a JDBC implementation, it seems that the [DataSourceConnectionFactory](dscf) allows this but this requires a different path specification than the JDBC driver.

[dscf]: https://commons.apache.org/proper/commons-dbcp/apidocs/org/apache/commons/dbcp2/DataSourceConnectionFactory

**Comment by seratch** [comment]
Thank you for your feedback. Indeed, it's a bit confusing although documentation tells library users to load JDBC driver by theirselves.

http://scalikejdbc.org/documentation/configuration.html

>if it is not needed, to simply abandon it – just tell users to have a JDBC implementation which can handle that URL in their classpath.

Currently the driver name is passed to DBConnection to enable to test which driver is currently used at runtime. I think enabling to automatically load JDBC drivers would be useful. Adding automaticJDBCDriverLoad flag to GlobalSettings or ConnectionPoolSettings. Now I'm actively working on ScalikeJDBC 2.5 development. I'll do some action on this issue.

**Comment by seratch** [comment]
>I think enabling to automatically load JDBC drivers would be useful.

`DBs.setup` in scalikejdbc-config library loads JDBC driver for you. Use this module. https://github.com/scalikejdbc/scalikejdbc/blob/2.3.5/scalikejdbc-config/src/main/scala/scalikejdbc/config/DBs.scala#L13

I just updated the documentation page a little. https://github.com/scalikejdbc/scalikejdbc.github.io/commit/541342a0090ebcebd010ca646a1779c7971b24e8

If there is no more additional issue, would you mind closing this issue?

**Comment by admackin** [comment]
No, what I'm saying here is that, at least for JDBC 4 drivers, class.forName has no effect, as per the (DriverManager docs)[http://docs.oracle.com/javase/6/docs/api/java/sql/DriverManager.html]:

> Applications no longer need to explictly load JDBC drivers using Class.forName()

According to the documentation above and to my debugging, all modern JDBC drivers present on your classpath will proactively load and register themselves no matter what you do (independently of ScalikeJDBC). That is, `DBs.setupAll()` is *not* loading the JDBC drivers (not the MySQL and MariaDB ones at least – maybe there some outdated drivers still in use) – they load themselves.

(Whether this is the right thing for JDBC to do is another question outside the scope of what we can control of course. It leads to potentially confusing behaviour like we saw at #493 for *any* apps using the `DriverManager` JDBC API when you have multiple JDBC implementations able to accept the same URLs).

So I still can't see what the `driver` setting actually does in practice. You said that it's passed to "DBConnection to enable to test which driver is currently used at runtime". I couldn't see where that was supposed to happen in the code. In addition, the troubles at #493 and skinny-framework/skinny-framework#305 indicate that this seems to be not happening, since I was explicitly requesting one JDBC driver (MySQL), but getting another (MariaDB).

This is all getting a bit confusing, so here's the summary of my understanding (happy to be proven wrong though, I'm sure you've worked with JDBC more than I have!):

- Modern JDBC drivers load themselves if they are present in the classpath (or possibly, in the worst case, need to be explicltly requested eg via the `jdbc.drivers` system property as noted in the (DriverManager docs)[http://docs.oracle.com/javase/6/docs/api/java/sql/DriverManager.html])
- IMO, ScalikeJDBC should embrace this, and explicitly stop worrying about loading JDBC drivers at all  (ie the opposite of what you said above), including not using the `driver` parameter. For most people this would have no effect – the URL-based driver selection works fine most of the time. For people loading MariaDB and MySQL drivers, they could still get strange bugs, but at least they won't blame ScalikeJDBC for using one driver when they explicitly requested another.

**Comment by seratch** [comment]
>Modern JDBC drivers load themselves if they are present in the classpath (or possibly, in the worst case, need to be explicltly requested eg via the jdbc.drivers system property as noted in the DriverManager docs)

No. Unfortunately, we need to load JDBC drivers in practice at least in the Scala world.

**Comment by admackin** [comment]
OK, you definitely don't need to for MySQL or MariaDB, but I'll take your word for it about other JDBC adapters.

However, this doesn't change my base assertion: **The `driver` setting does not select the JDBC driver for the DB you're configuring!** (unlike the other DB parameters such as `url`). I'm fairly sure about this, but please let me know you think this is not true. Regardless of *how* they're loaded, JDBC drivers are global to the entire JVM, AFAICT. 

Let's say you set up three different DBs in ScalikeJDBC using the config file method. Let's say they're all JDBC adapters which do not automatically load: `FooDB`, `BarDB` and `BazDB`, and you set them up in typesafe config (omiting other irrelevant parameters):

    db.default.driver: "com.example.foodb.JDBC"
    db.other1.driver: "com.example.bardb.JDBC"
    db.other2.driver: "com.example.bazdb.JDBC"

What will happen here as that all three JDBC adapters will get loaded using `Class.forName()`. Then, when each connection is established ScalikeJDBC will call `DriverManager.getConnection()` and the JDBC adapter will be selected on the basis of the supplied URL. This will usually get the expected behaviour anyway (if configured correctly), unless eg `foodb` and `bardb` can except the same URLs, in which case either could be selected arbitrarily, instead of the one the use thought they were requesting.

IMO, If you want to handle JDBC driver loading in ScalikeJDBC, it makes sense as a global parameters, reflecting the fact that it's global to the JVM (ie you can't really select a particular driver on a per-connection basis, it just looks like that because they usually handle different DB URLs)

**Comment by seratch** [comment]
Sorry for previous quick reply from mobile. 

>However, this doesn't change my base assertion: The driver setting does not select the JDBC driver for the DB you're configuring! (unlike the other DB parameters such as url). I'm fairly sure about this, but please let me know you think this is not true.

I agree on this.

>IMO, If you want to handle JDBC driver loading in ScalikeJDBC, it makes sense as a global parameters, reflecting the fact that it's global to the JVM (ie you can't really select a particular driver on a per-connection basis, it just looks like that because they usually handle different DB URLs)

I can understand your opinion but I'm not willing to force such an incompatible change to existing applications for the reason. IMO, just improving documentation is enough.

However, never forcing scalikejdbc-config users to load JDBC drivers in global is reasonable enough. it's fine for me to allow absence of the `driver` configuration, and just skip loading when it's absent. I'll work on this soon.

Pull requests from you to improve the documentation is always welcome. Thank you for your useful feedback.

**Comment by admackin** [comment]
Sounds good to me! Happy to do a PR to update the docs. Thanks
