### ISSUE TITLE
"poolConnectionTimeoutMillis" setting in config for DB has no effect 

### ISSUE THREAD

**Issue by lantian0802** [scalikejdbc/scalikejdbc#497]
I setted “poolConnectionTimeoutMillis=500”, but sql execute cost time is 20s. my program run complete and not throw a  timeout exception。 why is it?

**Comment by macobo** [comment]
You're mistaken about what this setting means.

That setting applies only for connection pooling - i.e. if your program has a connection pool of size 8 (the default, https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-core/src/main/scala/scalikejdbc/ConnectionPoolSettings.scala) and already have 8 queries executing in parallel then the next query will wait up to 500 milliseconds for a connection to open up.

The option you're looking for is here: https://github.com/scalikejdbc/scalikejdbc/blob/7585d6dae6a900cc04b47ca76ff0622296da7fa2/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala#L203

**Comment by lantian0802** [comment]
My scalikejdbc version is 2.2.9.  Which version began to support this feature?

**Comment by lantian0802** [comment]
The method "setTimeoutquery" is a function of SQL Object, I must invoke it on every sql, did it has a common approach to set the timeout parameter?

**Comment by seratch** [comment]
@lantian0802 Try socketTimeout parameter in JDBC url.

MySQL: https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
PostgreSQL: https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by seratch** [comment]
@lantian0802 Can I close this issue now?
