### ISSUE TITLE
[scalikejdbc-config] Make application.conf path changeable

### ISSUE THREAD

**Issue by Tooa** [scalikejdbc/scalikejdbc#503]
Hi,

I would like to change the lookup path for the application.conf file. Couldn't find a simple way to do this.

Best Uli

**Comment by seratch** [comment]
- https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-config/src/test/scala/scalikejdbc/config/TypesafeConfigReaderSpec.scala
- https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-config/src/main/scala/scalikejdbc/config/DBs.scala

Create your own TypesafeConfigReader or DBs:

```scala
object MyDBs extends DBs
  with TypesafeConfigReader
  with StandardTypesafeConfig
  with NoEnvPrefix {
  override lazy val config: Config = ConfigFactory.load("yet-another.conf")
}
MyDBs.setupAll()
```

**Comment by Tooa** [comment]
Thanks for this insane fast reply. Solved.
