### ISSUE TITLE
TO which repository manager are scalikejdbc jars published?

### ISSUE THREAD

**Issue by ericdf** [scalikejdbc/scalikejdbc#518]
I can find this older version on https://oss.sonatype.org/#nexus-search;quick~scalikejdbc

Are more current releases published somewhere else that Maven/SBT can reach?

<dependency>
  <groupId>org.scalikejdbc</groupId>
  <artifactId>scalikejdbc_2.9.2</artifactId>
  <version>1.7.7</version>
</dependency>

**Comment by seratch** [comment]
scalikejdbc project has dropped Scala 2.9.x support since version 2.0.0. Please consider bumping your Scala version of your projects.

https://github.com/scalikejdbc/scalikejdbc/blob/master/notes/2.0.0.markdown

If you have critical and urgent problems with Scala 2.9 jars, please let us know. We can work on it as possible as we can.

**Comment by ericdf** [comment]
I'm asking a different question;  I'm using scala 2.10 and in no way interested in holding back on old releases.  I just want to know where release jars get published.  Do you guys push them to one of the various maven repositories?

**Comment by seratch** [comment]
>Do you guys push them to one of the various maven repositories?

No, we use only the Sonatype repositories.

**Comment by seratch** [comment]
Although you may already know, Sonatype does syncing jars into Maven Central repositories as well. So ScalikeJDBC libs are available on both of sonatype and central.

**Comment by xuwei-k** [comment]
http://search.maven.org/ is more useful?

- http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.scalikejdbc%22%20AND%20a%3A%22scalikejdbc_2.10%22
- http://search.maven.org/#api
- http://search.maven.org/#advancedsearch

**Comment by ericdf** [comment]
Thank you -- this is very helpful.
