### ISSUE TITLE
autoConstruct issue in 2.4.0

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#520]
https://gitter.im/scalikejdbc/en?at=573374c275a64b453292acdb

> @seratch Hi, I update to 2.4.0 and now I have problem with `autoConstruct` 

```
Error:(25, 18) could not find implicit value for evidence parameter of type scalikejdbc.TypeBinder[java.util.UUID]
    autoConstruct(rs, rn)
                 ^
```

But I have import `import ScalikeBinders.uuidBinderFactory`
with code 

```
implicit val uuidBinderFactory: ParameterBinderFactory[java.util.UUID] = ParameterBinderFactory {
    value => (stmt, idx) => stmt.setObject(idx, value)
  }
```

cc: @gakuzzzz

**Comment by gakuzzzz** [comment]
UUID does not support JDBC.

I don't know that `stmt.setObject(idx, uuid)` is OK at all drivers.

Does it add scalikejdbc standard implicit?

I think that we should define a `Binders` in user code by ourselves.

**Comment by seratch** [comment]
I'm afraid the main point of this issue is not supporting UUID but existing code migration when bumping version to 2.4.0. But I'm not sure we actually need to take some action yet. I've asked more details about this question on the gitter channel. https://gitter.im/scalikejdbc/en

**Comment by gakuzzzz** [comment]
I think we may provide a non-implicit default `Binders[java.util.UUID]`.

**Comment by seratch** [comment]
I've not figured out what the actual issue is yet. I'd like to wait for a @greenhost87's reply.

**Comment by greenhost87** [comment]
After release `2.4.2` and when I move all code to use `Binders` like this
```
implicit val consumableKindEnumConverter: Binders[ConsumableKindEnum.ConsumableKind] = Binders.string.xmap(ConsumableKindEnum.withName, _.toString)
```
issue is gone

**Comment by greenhost87** [comment]
For the record: Finally I found work solution for mapping `java.util.UUID` datatype to PostgreSQL datatype `UUID`. Work code look like that:

```scala
  implicit val uuidBinder: Binders[UUID] = Binders.of[java.util.UUID] {
    case null => null
    case v => UUID.fromString(v.toString)
  }(v => (ps, idx) => ps.setObject(idx, v))
```

**Comment by greenhost87** [comment]
@seratch I think you need add something like this

```
val obj: Binders[Object] = Binders(_ getObject _)(_ getObject _)(v => (ps, idx) => ps.setObject(idx, v))
```

into `scalikejdbc.Binders` for case like this. That can help with binding `Array` or `jsonb` PostgreSQL datatypes or other uncommon datatypes. Do you need pool request for this?

**Comment by greenhost87** [comment]
@seratch I think need close this issue
