### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by schickling** [scalikejdbc/scalikejdbc#534]
How can you disable all logging messages such as:

`[main] DEBUG scalikejdbc.ConnectionPool$ - Registered connection pool : ConnectionPool(`

and

`DEBUG scalikejdbc.DB - A Connection is closed.`

PS: Unfortunately I didn't find the answer to that in previous issues.

**Comment by seratch** [comment]
Changing the log level would work for you. Configure your logback.xml like this: https://github.com/scalikejdbc/hello-scalikejdbc/blob/5d32218ea2f559a2ff3131bbea8b01352740ae4b/conf/logback.xml#L18

**Comment by schickling** [comment]
Thanks! How would a minimal non-XML version look like? 👍

**Comment by seratch** [comment]
Logback library also supports configuration written in Groovy. I usually use XML file but Groovy configuration may be simpler. http://logback.qos.ch/manual/groovy.html

### build.sbt

```scala
libraryDependencies ++= Seq(
  "org.scalikejdbc" %% "scalikejdbc"       % "2.4.1",
  "com.h2database"  %  "h2"                % "1.4.191",
  "ch.qos.logback"  %  "logback-classic"   % "1.1.7",
  "org.codehaus.groovy" % "groovy"         % "2.4.7"
)
scalaVersion := "2.11.8"
```

### src/main/resources/logback.groovy

```
appender("STDOUT", ConsoleAppender) {
  encoder(PatternLayoutEncoder) {
    pattern = "%level %logger - %msg%n"
  }
}
root(INFO, ["STDOUT"])
```

**Comment by hartmut27** [comment]
Non-XML config of Logback goes this way:

`LoggerFactory.getLogger("scalikejdbc").asInstanceOf[Logger].setLevel(Level.WARN)`
