### ISSUE TITLE
String "null" is interpreted as being NULL

### ISSUE THREAD

**Issue by dtboctor** [scalikejdbc/scalikejdbc#537]
I have an unusual database case where I am trying to persist the string "null" to a database, currently within an Option (basically Some("null")),

MySQL appears to be interpreting this value as being NULL?  Is that on the mysql side or something in the library?

**Comment by cppexpert** [comment]
I'd enable DEBUG level of logging to see what query ScalikeJDBC sends to DB.

**Comment by seratch** [comment]
I don't think both of scalikejdbc and MySQL JDBC driver don't behave as you described. If you have time, please share us a minimum working example which reproduces your situation. Thanks.

**Comment by dtboctor** [comment]
I think there was another issue, you are right.
