### ISSUE TITLE
How do you use SubQuery ?

### ISSUE THREAD

**Issue by cppexpert** [scalikejdbc/scalikejdbc#539]
Sorry, Kaz. Another question for you since I decided to use feature I've never used.

How do you use SubQuery ?

I tried this according to documentation

```
      val sa = SharedArticle.syntax("sa")
      val t = SubQuery.syntax("t").include(sa)
      withSQL {
        select(sa.resultAll).from {
          select(sa.result.fromUserId, sa.result.articleId, sa.result.sharedAt).from(SharedArticle as sa).where.
            eq(sa.fromUserId, userId).or.
            eq(sa.toUserId, userId).as(t)
        }.innerJoin(SharedArticle as sa).on(t.fromUserId, sa.fromUserId)
      }.map(SharedArticle(sa)).list()()
```

but it doesn't compile on `t.fromUserId` saying

```
Error:(76, 47) value fromUserId is not a member of scalikejdbc.SubQuerySQLSyntaxProvider
        }.innerJoin(SharedArticle as sa).on(t.fromUserId, sa.fromUserId)
                                              ^
```

What am I missing ?

**Comment by seratch** [comment]
`t(sa).fromUserId` instead. https://github.com/scalikejdbc/scalikejdbc/blob/508fcc207afe8e5a7588cb7dac8596ba44ba1bf6/scalikejdbc-interpolation/src/test/scala/scalikejdbc/SQLInterpolationSpec.scala#L654

BTW, this is not an issue of library but a question. Please use Google Group or gitter chat when posting questions. https://github.com/scalikejdbc/scalikejdbc/blob/master/CONTRIBUTING.md#issues

- https://gitter.im/scalikejdbc/en
- https://groups.google.com/forum/#!forum/scalikejdbc-users-group

**Comment by seratch** [comment]
@cppexpert Can I close this issue?
