### ISSUE TITLE
Transaction control is not flexible enough

### ISSUE THREAD

**Issue by scf37** [scalikejdbc/scalikejdbc#543]
Imagine I'm writing ScalaTest suite and want transaction to automatically rollback after each test.
ScalaTest provides following methods for that:
`protected def beforeEach(): Unit
 protected def afterEach(): Unit`

But existing API on DB only supports passing in closure while I need ability to create and manage DBSession by hand (create it in `beforeEach()` method and terminate in `afterEach()` method

**Comment by seratch** [comment]
ScalikeJDBC has `AutoRollback` in testing support. If you have another idea on testing, please close this issue and create a suggestion issue separatedly. http://scalikejdbc.org/documentation/testing.html
