### ISSUE TITLE
No support for nested transactions

### ISSUE THREAD

**Issue by scf37** [scalikejdbc/scalikejdbc#544]
Transaction blocks should support nesting natively because when someone uses transaction block, he expects code inside to execute atomically, even if some other code deep below uses transactions as well.

AutoSession is not an option as it sets connection.autoCommit to true.

**Comment by seratch** [comment]
You can do nesting like this.

```scala
DB.localTx { session1 =>
  // do stuff with session1
  sql"....".update.apply()(session1)
  DB.localTx { session2 =>
    // do stuff with session2
    sql"....".update.apply()(session2)
  }
  // do stuff with session1
  sql"....".update.apply()(session1)
}
```
