### ISSUE TITLE
Error Reporting Update Please

### ISSUE THREAD

**Issue by asevans48** [scalikejdbc/scalikejdbc#545]
When I go to commit a batch update I receive an error. There is likely a bug in my code. I am using the same code for many...many different programs as I am using scalikejdbc in a tool I am building with a jdbcTemplate like wrapper. 

First, would it be possible to tone down the default logging for better tuning? I am committing 10s of thousands to millions of records and am certain this issue was raised before. I am using the global parameters but in order to see anything useful have to nearly turn off all logging.

Next, would it be possible to call getNextException() when a SQLException is thrown or convert the exception array to an iterator and do something like e.iterator.map{x => x.getMessage}.mkString("\n") + "\n"+ExceptionUtils.getStackTrace(e)?

I have been trying to catch SQLExceptions when errors are thrown but they are not being picked up in my code. Your code seems to create many custom exceptions including new SQLExceptions.

This would help immensely. Thanks.

**Comment by seratch** [comment]
https://github.com/scalikejdbc/scalikejdbc/blob/master/CONTRIBUTING.md#issues

First of all, please post a question to Google Group or gitter chat instead.

- https://groups.google.com/forum/#!forum/scalikejdbc-users-group
- https://gitter.im/scalikejdbc/en

So I briefly answered but I'm not willing to continue the discussion on your questions here.

>First, would it be possible to tone down the default logging for better tuning? I am committing 10s of thousands to millions of records and am certain this issue was raised before. I am using the global parameters but in order to see anything useful have to nearly turn off all logging.

Please make sure your logback's settings (logback.xml).

>Next, would it be possible to call getNextException() when a SQLException is thrown or convert the exception array to an iterator and do something like e.iterator.map{x => x.getMessage}.mkString("\n") + "\n"+ExceptionUtils.getStackTrace(e)?
>I have been trying to catch SQLExceptions when errors are thrown but they are not being picked up in my code. Your code seems to create many custom exceptions including new SQLExceptions.

I've not figured out your problem yet. Please share us a working code example to reproduce your situation.
