### ISSUE TITLE
Generator support for SQL Server unicode string types

### ISSUE THREAD

**Issue by vpopescu** [scalikejdbc/scalikejdbc#557]
I am trying to understand if I should, and how to modify the CodeGenerator.scala to properly support SQL Server nchar, nvarchar, ntext. They seem to be generated as "Any". The mapping tables for the two JDBC drivers for SQL Server:

Microsoft JDBC driver mapping table: https://msdn.microsoft.com/en-us/library/ms378813(v=sql.110).aspx
JTDS driver mapping table: http://jtds.sourceforge.net/typemap.html

Apologies if I misunderstand the issue, I'm day-old with ScaLikeJDBC. I can certainly experiment until I get it right, but I want to make sure I'm not missing some other recommended method through which I can add type support.

**Comment by seratch** [comment]
ScalikeJDBC uses JDBC metadata APIs to determine the data type of columns. https://github.com/scalikejdbc/scalikejdbc/blob/2.4.2/scalikejdbc-core/src/main/scala/scalikejdbc/DBConnection.scala#L433-L434

Basically, as described [here](http://scalikejdbc.org/), we (= maintainers of ScalikeJDBC) don't guarantee the library works with SQL Server in any cases. However, if you have a motivation to work on this issue, it's ok to accept your code which enables to fetch proper column data types from SQL Server.

**Comment by vpopescu** [comment]
Ok, I'll send in a PR for at least the datatypes I encounter for my particular needs. They seem to correctly generate String in the generator. Feel free to refuse the PR if it causes any issues.
