### ISSUE TITLE
SQLSyntax.and and SQLSyntax.or should wrap both clauses in parentheses

### ISSUE THREAD

**Issue by bobbyi** [scalikejdbc/scalikejdbc#560]
SQLSyntax.and wraps its argument in parentheses, but does not wrap the "this" parameter. This means that

```
sqls"a or b" and sqls"c"
```

becomes the SQL

```
a or b and (c)
```

I believe it should become 

```
(a or b) and (c)
```

**Comment by tkawachi** [comment]
SQLSyntax can represent any part of SQL. Wrapping "this" with paren can break SQL. For example, `sqls"where a or b" and sqls"c"` should not become `(where a or b) and (c)`

**Comment by seratch** [comment]
As @tkawachi mentioned, doing so will break the SQL statement. If you'd prefer always wrapping with parentheses, using `withRoundBracket` or `toAndConditionOpt` should be helpful for you.

**Comment by seratch** [comment]
@bobbyi Did the replies above help you? Since we're not planning to take some actions for this so far, I'd like to close this issue after waiting for your reply for several days.
