### ISSUE TITLE
using mysql 6.0.3   connector schema is not identified

### ISSUE THREAD

**Issue by AvihayTsayeg** [scalikejdbc/scalikejdbc#562]
when using mysql-connector-java 6.0.3 the generator is using the wrong schema.
getting this error
```
java.sql.SQLSyntaxErrorException: Unknown table 'cc' in information_schema
```

similar at runtime when trying to DB.showTables getting tables from all schemas

**Comment by AvihayTsayeg** [comment]
Hi,
It is not a bug in scalikejdbc,
The behavior of the driver was changed,
nullCatalogMeansCurrent default value was changed from true to false.

I think it is better to add a remark in the documentation.

Regards, Avihay

**Comment by DWvanGeest** [comment]
This just bit me as well, there needs to be a prominent note somewhere that the 5.1 mysql driver is required.

**Comment by Saisse** [comment]
Hi, I found the same mysql-connector-java problem and tried it on several versions. The latest drivers are working and share the results.

- 5.1.47 -> OK
- 6.0.6 -> NG
- 8.0.16 -> NG
- 8.0.17 -> OK
