### ISSUE TITLE
Timezone test failure on scala/communitybuilds environment

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#565]
@ocadaruma 

[A test code you added before](https://github.com/scalikejdbc/scalikejdbc/blob/3510e5ad6ba8fa5c440f2907280a10460d1473e4/scalikejdbc-core/src/test/scala/scalikejdbc/DBSessionSpec.scala#L1090
) works fine on my local machine and on Travis builds. But, somehow, it cannot work as expected on Scala lang project's communitybuilds environment. 

see for details: https://github.com/scala/community-builds/issues/279#issuecomment-249061125

If you have time, I'd appreciated if you check the issue.

**Comment by xuwei-k** [comment]
https://github.com/xuwei-k/scalikejdbc/commit/5cd9824007bc1d0003ca2ff9e90de34b8278058f
https://travis-ci.org/xuwei-k/scalikejdbc/builds/162224085

( ◜◡‾)？

- Japan ◯
- GMT ◯
- NewYork ✕
- Hawaii ✕

<img width="385" alt="travis-result" src="https://cloud.githubusercontent.com/assets/389787/18792013/eacaab90-81ef-11e6-86df-d6e32adb2cbd.png">
