### ISSUE TITLE
when the table is a instance variable

### ISSUE THREAD

**Issue by wangxnb** [scalikejdbc/scalikejdbc#569]
```scala
val id = 1234
val mobile = sql"select mobile from custinfo where id = ${id}".map(rs => rs.string("mobile")).single().apply()
```

**the code above is no problem, but when the table name custinfo is a variable like id it will throw an error**

```scala
val tablename = "custinfo"
val mobile = sql"select mobile from ${tablename} where id = ${id}".map(rs => rs.string("mobile")).single().apply()
```

**Comment by tkawachi** [comment]
`SQLSyntax.createUnsafely()` can be used to inject an arbitrary string to SQL as is. (Take care of SQL injection. It's "unsafe".)

https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-core/src/main/scala/scalikejdbc/interpolation/SQLSyntax.scala#L229-L232

```scala
val tablename = SQLSyntax.createUnsafely("custinfo")
val mobile = sql"select mobile from ${tablename} where id = ${id}".map(rs => rs.string("mobile")).single().apply()
```

**Comment by seratch** [comment]
@angxnb If @tkawachi 's reply is helpful for you, please close this issue.

**Comment by wangxnb** [comment]
yeah, it can work success, sorry，the problem is I am not familiar the api and can't find any resource so submit the question, thanks very much
