### ISSUE TITLE
Scala 2.12.0 release

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#578]
@xuwei-k Are you interested in working on this? 

https://github.com/scala/scala/releases/tag/v2.12.0

**Comment by xuwei-k** [comment]
2.12.0-RC2 and 2.12.0 final are almost the same.
https://github.com/scala/scala/compare/v2.12.0-RC2...v2.12.0
We just wait for release of dependency libraries :)

- [ ] specs2
- [ ] scalatest

**Comment by xuwei-k** [comment]
http://repo1.maven.org/maven2/org/scalikejdbc/scalikejdbc_2.12/2.5.0-RC2/
