### ISSUE TITLE
remove ParameterBinderFactoryMacro, add some typeclass instances for java8 time classes

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#605]
https://github.com/scalikejdbc/scalikejdbc/pull/596#issuecomment-262901163

- [ ] remove ParameterBinderFactoryMacro
- [ ] add Binders instances https://github.com/scalikejdbc/scalikejdbc/blob/9bedc9859c/scalikejdbc-core/src/main/scala/scalikejdbc/Binders.scala
- [ ] use Binders instances in https://github.com/scalikejdbc/scalikejdbc/blob/9bedc9859c/scalikejdbc-core/src/main/scala/scalikejdbc/TypeBinder.scala#L99-L111
- [ ] add ParameterBinderFactory instances (use Binders)  https://github.com/scalikejdbc/scalikejdbc/blob/9bedc9859c/scalikejdbc-core/src/main/scala/scalikejdbc/ParameterBinderFactory.scala

**Comment by seratch** [comment]
@gakuzzzz Do you have time to work on this?

**Comment by seratch** [comment]
@xuwei-k @gakuzzzz Check #636 when you have time.
