### ISSUE TITLE
May connection leak when com.mysql.jdbc.PacketTooBigException 

### ISSUE THREAD

**Issue by wuranbo** [scalikejdbc/scalikejdbc#609]
looks like there is connection leak at this error.
I got a sql which run every hour, I set the poole max size to 10, then after about 8,9 hours, I got the exception ' Cannot get a connection, pool error Timeout waiting for idle object'. 

version:

> mysql 5.5.47
>   "org.scalikejdbc" %% "scalikejdbc"       % "2.3.4",
>   "org.scalikejdbc" %% "scalikejdbc-config"  % "2.3.4",
>   "org.scalikejdbc" %% "scalikejdbc-test"   % "2.3.4"   % "test",
>   "org.hsqldb" % "hsqldb" % "2.3.2",
>   "mysql" % "mysql-connector-java" % "5.1.38",
>   "com.h2database"  %  "h2"                % "1.4.190",
>   "org.apache.commons" % "commons-dbcp2" % "2.0.1",

I will try a simple example later.

this is the stack 

> com.mysql.jdbc.PacketTooBigException: Packet for query is too large (28286494 > 20971520). You can change this value on the server by setting the max_allowed_packet' variable.
>         at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3583)
>         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2460)
>         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
>         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
>         at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
>         at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
>         at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
>         at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
>         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
>         at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
>         at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
>         at scalikejdbc.StatementExecutor$$anonfun$executeUpdate$1.apply$mcI$sp(StatementExecutor.scala:329)
>         at scalikejdbc.StatementExecutor$$anonfun$executeUpdate$1.apply(StatementExecutor.scala:329)
>         at scalikejdbc.StatementExecutor$$anonfun$executeUpdate$1.apply(StatementExecutor.scala:329)
>         at scalikejdbc.StatementExecutor$NakedExecutor.apply(StatementExecutor.scala:18)
>         at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLAndTiming$$super$apply(StatementExecutor.scala:309)
>         at scalikejdbc.StatementExecutor$LoggingSQLAndTiming$class.apply(StatementExecutor.scala:253)
>         at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLIfFailed$$super$apply(StatementExecutor.scala:309)
>         at scalikejdbc.StatementExecutor$LoggingSQLIfFailed$class.apply(StatementExecutor.scala:286)
>         at scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:309)
>         at scalikejdbc.StatementExecutor.executeUpdate(StatementExecutor.scala:329)
>         at scalikejdbc.DBSession$$anonfun$updateWithFilters$1.apply(DBSession.scala:432)
>         at scalikejdbc.DBSession$$anonfun$updateWithFilters$1.apply(DBSession.scala:430)
>         at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
>         at scalikejdbc.ActiveSession.scalikejdbc$DBSession$$super$using(DBSession.scala:586)
>         at scalikejdbc.DBSession$class.using(DBSession.scala:30)
>         at scalikejdbc.ActiveSession.using(DBSession.scala:586)
>         at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:429)
>         at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:586)
>         at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:407)
>         at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:586)
>         at scalikejdbc.SQLUpdate.apply(SQL.scala:536) #608

**Comment by jeffbondlink** [comment]
what is in the packet?  are you acculuating data over the course of 8-9
hours 20M is a huge insert, the error simply tells you to increase the
max_packet_size, but i would look closer at what you're attempting to
insert and not worrying about connection leaks until you have that settled.

Best,
Jeff

**Comment by seratch** [comment]
This one doesn't look a leak issue. And I'm afraid that it's not even an issue on this library because the same situation should happen even when you directly use the JDBC driver.

If there is no action to take on this library side, would you consider closing this issue and moving to Google Group to continue the discussion? :bow: 

see also: https://github.com/scalikejdbc/scalikejdbc/blob/master/CONTRIBUTING.md#issues

**Comment by wuranbo** [comment]
@seratch  ok

**Comment by Rakshitha-BR** [comment]
What is the max pool size by default? How to increase the max size?
