### ISSUE TITLE
debugging/testing SQL injection

### ISSUE THREAD

**Issue by hasufell** [scalikejdbc/scalikejdbc#610]
I'm currently trying to penetrate-test an application using scalikejdbc for SQL injection. I can't really debug though why an injection does not work. The __debug messages__ for example show the following SQL statement was executed, abusing the data flow from the frontend to the sql statement:

```mysql
INSERT INTO foo.bar(pid,id,desc) VALUES(1,0,'lala'); DROP TABLE foo.baz; --');
```

However, that does not seem to be the case, instead `lala'); DROP TABLE foo.baz; --` is taken as a literal string (fortunately). Does sanitation/filtering/input validation happen after logging? And where exactly does it happen?

**Comment by seratch** [comment]
Unfortunately, the debug logging doesn't show the actual SQL statement.

**Comment by hasufell** [comment]
Yeah, that's what I'd like to have. What good does debugging do otherwise?

**Comment by seratch** [comment]
@hasufell How about making your own query logger by implementing QueryCompletionListener so far?
https://github.com/scalikejdbc/scalikejdbc/blob/251ed2994cc8014ffe286344eec83455eb5dcbf9/scalikejdbc-core/src/main/scala/scalikejdbc/GlobalSettings.scala#L48

**Comment by seratch** [comment]
@hasufell Did my last comment help you then? If we don't have any further topics to discuss here, I would like to close this issue.

**Comment by hasufell** [comment]
It was a long time ago I worked on a project using scalikejdbc, so I cannot comment on it anymore.

**Comment by seratch** [comment]
Thank you for your response. Let me close this issue. When you have a similar topic to discuss in the future, feel free to reopen this or create another one.
