### ISSUE TITLE
improve WrappedResultSet for java.time.* classes

### ISSUE THREAD

**Issue by vadim-shb** [scalikejdbc/scalikejdbc#611]
There are methods for easy get joda-time values from resultSet.
Like rs.jodaLocalDateTimeOpt("my_time_variable")

There must be the same bunch of methods for java.time.* values
Like rs.localDateTimeOpt("my_time_variable")

**Comment by vadim-shb** [comment]
Oh.. I see this code is already implemented. But not in 2.5.0 version (for reason).

**Comment by seratch** [comment]
@vadim-shb It's also possible to use jsr-310 in 2.x series as well. http://scalikejdbc.org/documentation/operations.html#using-java-se-8-date-time-api-jsr-310

**Comment by vadim-shb** [comment]
Great news. Thanks!
