### ISSUE TITLE
Proposal: merging scalikejdbc-streams

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#613]
https://github.com/yoskhdia/scalikejdbc-streams

I'm planning to merge @yoskhdia 's scalikejdbc-streams into scalikejdbc project or another repository in scalikejdbc organization. The reasons for that are:

- Since supporting Reactive Streams is more important than before, having an adaptor for it should be useful for many users
- Since reactive-streams dependency is independent of Scala binary version, that won't bring complexity to the project build

@yoskhdia and I already discussed it in person and he agreed to move the project to scalikejdbc org. If there is no strong objection, I'd love to add @yoskhdia to members of scalikejdbc team. The first release we have the scalikejdbc-streams will be 3.0.0. It's also possible to backport the module to 2.5.x or 2.6.x, if many users hope so.

**Comment by denisftw** [comment]
Awesome! I was hoping that this would happen.

**Comment by seratch** [comment]
@yoshkhdia so let's get started. would you please make a pull request to merge your module into this repository when you have time?

**Comment by yoskhdia** [comment]
@seratch Okay! I will send you a pull request sometime soon. 
(uh... excuse me, my username is yoskhdia ;-)

**Comment by seratch** [comment]
@yoskhdia So sorry... mistyped from mobile...

**Comment by ktoso** [comment]
Very cool, glad to see you guys exposing reactive-streams too. 
I had a look at the TCK test in the project, looks good - thanks :-)
