### ISSUE TITLE
Map Unsigned Int to Long by mapper-generator

### ISSUE THREAD

**Issue by Uxio0** [scalikejdbc/scalikejdbc#627]
Now SQL **unsigned int** is mapped to Scala **Int**, shouldn't it be mapped to Long?

Thanks for the great job,

Cheers

**Comment by xuwei-k** [comment]
Could you please tell us more informations? which database are you using? which version?

**Comment by Uxio0** [comment]
Hi,

I'm using Percona MySQL, tested with versions 5.6 and 5.7

**Comment by seratch** [comment]
@Uxio0 It depends on the JDBC driver's implementation you're using.

We convert `java.sql.Types` returned from JDBC drivers to corresponding Scala type.
- http://docs.oracle.com/javase/6/docs/api/java/sql/Types.html
- https://github.com/scalikejdbc/scalikejdbc/blob/2.5.0/scalikejdbc-mapper-generator-core/src/main/scala/scalikejdbc/mapper/CodeGenerator.scala#L57-L92

**Comment by Uxio0** [comment]
I see... I was looking on how they fixed it on Spark https://github.com/apache/spark/pull/6229/commits/608695be3ae15ea8932ca6db0bf5d5ed7a70027f

**Comment by seratch** [comment]
@Uxio0 Any updates? If we don't have any further topics to discuss here, I would like to close this issue. Feel free to open another issue anytime you need to discuss with us.

**Comment by Uxio0** [comment]
No, no updates, I'm currently not working in Scala :(

**Comment by seratch** [comment]
I see. Thanks. Anyway, let me close this issue now.
