### ISSUE TITLE
Redshift query parameters error: [Amazon][JDBC](10940) Invalid parameter index

### ISSUE THREAD

**Issue by jasonf20** [scalikejdbc/scalikejdbc#628]
When working with Amazon Redshift queries like the following will fail:`sql"select * from TABLE where id = ${id}"`  due to the error: `[Amazon][JDBC](10940) Invalid parameter index: 1`

I believe this is due using `?`s in the prepared statement. When I try the following: `session.single("select * from TABLE where id = $1", id)` it works.

Is there a way to configure the syntax for prepared statement parameters? If not I think this is a bug.

**Comment by seratch** [comment]
At the current moment, there is no way to modify placeholder parts on scalikejdbc side. 

IMO, embedding question marks is the standard JDBC driver behavior, and scalikejdbc just depends on it. I'm afraid tha the behavior that a database sever doesn't accept it is Redshift-specific.

So I don't think it's a bug on our side but if there is a reasonable way we can do to solve your problem, let us know.

**Comment by ocadaruma** [comment]
@jasonf20 I use ScalikeJDBC(2.4.2) with Redshift jdbc driver(`RedshiftJDBC41-1.1.17.1017`), and it works properly.

Which version of driver you are using ?

**Comment by jasonf20** [comment]
@ocadaruma Hi, I am using    <artifactId>redshift-jdbc42</artifactId>
   <version>1.2.1.1001</version>

**Comment by jasonf20** [comment]
@seratch I one used a library (can't remember which) which did just that - allow you to configure which syntax to use for parameter placeholders, this however was not a JDBC driver but ODBC. Perhaps the JDBC driver allows this to be configured. I will do some checkup on this if I get a chance

**Comment by seratch** [comment]
@jasonf20 

>IMO, embedding question marks is the standard JDBC driver behavior, and scalikejdbc just depends on it.

Ah, sorry for my misunderstanding. If we have another string interpolation to support `$n` instead of `?`, indeed, it's possible to support your case. If many people need it, it's ok for me to have it.

**Comment by jasonf20** [comment]
After playing around a little I got this to work, not sure what actually changed but it seems to be working for me now so I guess I had an issue somewhere. Thanks for the responses guys but there seems to be no issue :)
