### ISSUE TITLE
Support DataSource closing

### ISSUE THREAD

**Issue by smdmts** [scalikejdbc/scalikejdbc#630]
I'm trying to use ConnectionPool with HikariCP. But it could not  closed by `ConnectionPool.close()`  throwing UnsupportedOperationException  cause  javax.sql.DataSource is *NOT* closable.

Currently, I'm facing the problem in below.

- `ConnectionPool.closeAll` would not work if  `ConnecectionPool.add` use with DataSource things.
- https://github.com/scalikejdbc/scalikejdbc/blob/e6746d851733f3498ff7acf611d505419ea0e9cf/scalikejdbc-core/src/main/scala/scalikejdbc/ConnectionPool.scala#L264

Ideally, I want to close the connection using `ConnectionPool.close()` with DataSource and others. Would you mind to consider below idea? 

https://github.com/smdmts/scalikejdbc/commit/5078815300b6872e812d85270858e4f1a03b06f0

Thanks for great jobs,

- usage example
```
val pool =  new DataSourceConnectionPool(ds , closer = new DataSourceCloseSupport {
  // closing with callback method.
  override def close():Unit = ds.close()
})
// add
ConnectionPool.add(sourceName, pool)

// close
ConnectionPool.close(sourceName)
// cloase all
ConnectionPool.closeAll()
```

**Comment by seratch** [comment]
Sounds good to care your use case. But is enabling to override `DataSourceCloseSupport#close` really needed? If not so, simply having `autoClose: Boolean` and if true, automatically calling `DataSource#close` would be enough. If we should provide specifying the `closer`, I prefer `DataSourceCloser` as the name of the trait.

**Comment by smdmts** [comment]
@seratch Thanks for prompt replying. 
- About, `autoClose: Boolean` 
What I just care about DataSource is not necessarily to have named by `close`. (e.f. destroy, shutdown, or other things.).
 So if this case of specification limiting named by `close`, it could realize by structural subtyping using reflection, but is it OK?

if it not good, I will rename `DataSourceCloser` and send PRs.

**Comment by seratch** [comment]
Ah, I've forgotten it. > DataSource doesn't have `close` method:
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html

So let's have closer trait as you suggested.
