### ISSUE TITLE
mapper-generator: use java.sql.JDBCType instead of java.sql.Types ?

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#637]
- https://docs.oracle.com/javase/8/docs/api/java/sql/Types.html 😨 int 
- https://docs.oracle.com/javase/8/docs/api/java/sql/JDBCType.html 😃 enum (since Java 8)

**Comment by seratch** [comment]
Indeed, JDBCType would be easier to handle.
