### ISSUE TITLE
Postgres: How to reference objects who share the same name as protected types?

### ISSUE THREAD

**Issue by autodidacticon** [scalikejdbc/scalikejdbc#642]
Given a postgres database with a table 'public.user', how would this table be referenced by scalike instead of the "user" object that postgres provides?

**Comment by seratch** [comment]
if you go with sql interpolation, simply specifying `public.user` works. When you use QueryDSL, specifying `schemaName` is needed.

https://github.com/scalikejdbc/scalikejdbc/blob/8deaba2f3b734a343554c48fef746eed36e5d876/scalikejdbc-interpolation/src/test/scala/scalikejdbc/QueryInterfaceSpec.scala#L54

**Comment by seratch** [comment]
Let me close his.
