### ISSUE TITLE
scalikejdbc.jsr310.StatementExecutorSpec fail in Java9

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#647]
https://github.com/scalikejdbc/scalikejdbc/blob/d1428311af51ab89107d0f18b8cbed973f870700/scalikejdbc-core/src/test/scala/scalikejdbc/jsr310/StatementExecutorSpec.scala#L34

```
[info] - should work with JSR-310 APIs *** FAILED ***
[info]   14:52:30.290 did not equal 14:52:30.290250 (StatementExecutorSpec.scala:34)
```

There is a difference of `LocalTime.now` between Java8 and Java9

```
$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+149)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+149, mixed mode)
$ scala
cat: /release: No such file or directory
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 9-ea).
Type in expressions for evaluation. Or try :help.

scala> java.time.LocalTime.now
res0: java.time.LocalTime = 23:52:45.625881

scala> java.time.LocalTime.now
res1: java.time.LocalTime = 23:52:46.741559

scala> java.time.LocalTime.now
res2: java.time.LocalTime = 23:52:47.652239
```

```
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> java.time.LocalTime.now
res0: java.time.LocalTime = 23:54:08.708

scala> java.time.LocalTime.now
res1: java.time.LocalTime = 23:54:09.526

scala> java.time.LocalTime.now
res2: java.time.LocalTime = 23:54:10.446

scala> java.time.LocalTime.now
res3: java.time.LocalTime = 23:54:11.290
```

https://github.com/scalikejdbc/scalikejdbc/blob/d1428311af51ab89107d0f18b8cbed973f870700/scalikejdbc-core/src/main/scala/scalikejdbc/StatementExecutor.scala#L114-L115

```scala
      case p: java.time.LocalTime =>
        underlying.setTime(i, org.joda.time.LocalTime.parse(p.toString).toSqlTime)
```

`org.joda.time.LocalTime` can not store nano seconds but `java.time.LocalTime` store nano seconds.

- https://github.com/JodaOrg/joda-time/blob/v2.9.7/src/main/java/org/joda/time/LocalTime.java
- https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html

**Comment by xuwei-k** [comment]
fix `scalikejdbc.StatementExecutor` or `scalikejdbc.jsr310.StatementExecutorSpec` ? Can JDBC and/or SQL handle nano seconds?

**Comment by seratch** [comment]
>Can JDBC and/or SQL handle nano seconds?

I'm afraid it's not possible. Just ignoring nanosecond values would be enough for the purpose.

**Comment by yoskhdia** [comment]
java.sql.Timestamp can handle nano seconds?
`Timestamp#setNanos`
https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html
