### ISSUE TITLE
Add methods findAll/countAll/findAllBy/countBy to a specific trait

### ISSUE THREAD

**Issue by david-bouyssie** [scalikejdbc/scalikejdbc#657]
Why the methods findAll/countAll/findAllBy/countBy are generated for all entities?
I don't understand why they are not inherited from a particular trait.
But maybe there is an obvious reason I do not know.

**Comment by seratch** [comment]
The main purpose I created the generator is enabling to start with ScalikeJDBC from scratch quickly.  So, the code generator outputs source code which doesn't depend on any particular prerequisites.

If you prefer the ones inheriting common parts from a base trait, you can override the code generator or create your own generator.

**Comment by david-bouyssie** [comment]
Ok I understand.
I close this issue.

Thanks!
