### ISSUE TITLE
Iterate results in chunks

### ISSUE THREAD

**Issue by tejasmanohar** [scalikejdbc/scalikejdbc#658]
I'm trying to iterate results from ScalikeJDBC in chunks without modifying the underlying SQL query (for more complex reasons related to the data store I'm accessing). The JDBC driver I'm using actually lazy loads data under the hood so this prevents me from mapping all the data to something like a list that I hold in memory. Is this possible with ScalikeJDBC?

In pure JDBC, I can store a ResultSet, iterate as much as I want via rs.next/.scan, and then come back later so batching is easy.

**Comment by yoskhdia** [comment]
How about scalikejdbc-streams?
https://github.com/scalikejdbc/scalikejdbc/tree/master/scalikejdbc-streams
It is a Release Condition. Now, You can use this with scalikejdbc RC3.

scalikejdbc-streams provides the `Publisher` of ReactiveStreams.
So, you can subscribe(iterate) results with AkkaStream, fs2, and more libraries that support ReactiveStreams.

**Comment by vilinski** [comment]
scalikejdbc-streams uses only readonly session. It there a way to get a stream within a transaction? I am allowed to query a view only if I set some values in other filter table. To do multiple queries parallel I do it currently within localTx and getting a List. wonder whether it somehow possible with `Publisher` also.

**Comment by yoskhdia** [comment]
Unfortunately, scalikejdbc-streams does not allow transactions to be accepted from outside.
This is because MySQL and others require a READ_ONLY connection for the CURSOR feature. Also, Subscription requires to keep borrowing a connection while someone is subscribing a stream, and it is necessary to properly close this connection according to Reactive Streams specifications, such as when an exception occurs.

**Comment by seratch** [comment]
@tejasmanohar Any comments? May I close this issue?

**Comment by tejasmanohar** [comment]
@seratch No comments, haven't used Scala in almost year and don't have a lot of context here, though scalikejdbc-streams looks good.
