### ISSUE TITLE
[Question] Generate SQL from Case class 

### ISSUE THREAD

**Issue by elarib** [scalikejdbc/scalikejdbc#679]
I have list of case classes, and i want to generate SQL from it. So i check the website and found how to reverse engineer the process, which mean from SQL to case classes, and for me , i want to inverse, from the case classes to SQL .

http://scalikejdbc.org/documentation/reverse-engineering.html

How can i do it ?

Regards

**Comment by seratch** [comment]
We don't support that so far.
