### ISSUE TITLE
Pagination approach for One-To-Many relationships

### ISSUE THREAD

**Issue by bondarYehor** [scalikejdbc/scalikejdbc#686]
Hello,

I just wondering how can I apply `offset` and `limit` query parameters in case of use `one.toManies` API with several left joins?

My sample DSL is:
```
withSQL {
        select.from(CustomerTable as cust)
          .leftJoin(SocialNetworkTable as sn).on(cust.id, sn.customerId)
          .leftJoin(MailingTable as ml).on(cust.id, ml.customerId)
}.one(CustomerTable(cust)).toManies(...)
```
So I want to paginate over parent `CustomerTable`.

Do you have any best practices to doing this?

**Comment by seratch** [comment]
Skinny ORM, an O/R mapper built upon ScalikeJDBC, does that properly. Consider using Skinny ORM for such queries. Sample: https://github.com/skinny-framework/skinny-framework/blob/a2baf2a1c9daf1244d0d7b13d5cd7ece13bc0c1b/orm/src/test/scala/issue263/Issue263Spec.scala#L122

**Comment by bondarYehor** [comment]
Thank you! Will try the ORM approach too.

Also I've found some solution that works for me:
```
      val x = SubQuery.syntax("x").include(_cust)
      var sql = select.from(CustomerTable as cust)
        .innerJoin({
          if (query.size > 0) {
            select.all(_cust).from(CustomerTable as _cust).offset(query.offset).limit(query.size).as(x)
          } else {
            select.all(_cust).from(CustomerTable as _cust).offset(1).as(x)
          }
        })
        .on(cust.id, x(_cust).id)
        .leftJoin(SocialNetworkTable as sn).on(cust.id, sn.customerId)
        .leftJoin(MailingTable as ml).on(cust.id, ml.customerId).toSQLSyntax
```

**Comment by seratch** [comment]
Thanks. Do you mind closing this issue now?
