### ISSUE TITLE
Getting exception UnexpectedNullValueException

### ISSUE THREAD

**Issue by 123avi** [scalikejdbc/scalikejdbc#687]
Hi am newbie with scalalike .  I will appreciate any idea or a solution to this problem am trying to run this query from different threads (async)
```
 def createNonUniqueOrReturnExisting(name: String)(implicit session: DBSession = 
DB.autoCommitSession): Long ={
val cmd = sqls"""WITH
                         val (l_name,d_label ) AS
                           (values
                               (? , ?)
                           ),
                         ins AS
                           ( INSERT INTO
                               users (name, label)
                             SELECT l_name, d_label FROM val
                             ON CONFLICT ON CONSTRAINT user_name_unique DO NOTHING
                             RETURNING id ,name               -- only the inserted ones
                           )
                       SELECT COALESCE(ins.id, users.id) AS id
                       FROM val
                         LEFT JOIN ins ON ins.name = val.l_name
                         LEFT JOIN label ON users.name = val.l_name ;"""
SQL(cmd).bind(name, false).map ( r => r.long("id") ).single().apply().get 

```
seems to be working fine with a single call but on multiple calls I am getting this exception:

```
> 
> ERROR [2017-05-09 14:02:23,517] com.foo.Dao: Failed to retrieve value because null. If you're using SQLInterpolation, you may mistake u.id for u.resultName.id.
> ! scalikejdbc.UnexpectedNullValueException: null
> ! at scalikejdbc.Binders$.scalikejdbc$Binders$$throwExceptionIfNull(Binders.scala:63)
> ! at scalikejdbc.Binders$$anonfun$25.apply(Binders.scala:124)
> ! at scalikejdbc.Binders$$anonfun$25.apply(Binders.scala:124)
> ! at scalikejdbc.Binders$$anon$1.apply(Binders.scala:14)
> ! at scalikejdbc.WrappedResultSet$$anonfun$get$2.apply(WrappedResultSet.scala:469)
> ! at scalikejdbc.WrappedResultSet.wrapIfError(WrappedResultSet.scala:26)
> ! ... 45 common frames omitted
> --
```

**Comment by seratch** [comment]
That's an intentional behavior. `WrappedResultSet.long` can not return null value because `scala.Long` is not nullable. If the column can be null-value, use `WrappedResultSet.longOpt` or `WrappedResultSet.get[Option[Long]]` instead.

**Comment by 123avi** [comment]
@seratch thanks , but please take a look, how can it be null ? if the item already exists than we return the id of the existing one, otherwise it's the newly created id

**Comment by seratch** [comment]
I've not ensured your situation but as the error message tells you, the situation actually happened.

This is not an issue of this library. I would appreciate it if you understand our project policy.

>Questions should be posted to the ScalikeJDBC Users Group
>Please describe your issue in detail (version, situation, examples)
>We may close your issue if we have no plan to take action on it. We appreciate your understanding.

https://github.com/scalikejdbc/scalikejdbc/blob/master/CONTRIBUTING.md#issues

**Comment by 123avi** [comment]
ok , i posted it on the users group https://groups.google.com/forum/#!topic/scalikejdbc-users-group/RL8zr4uKaXc
