### ISSUE TITLE
update dbconsole libraryDependencies

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#703]
- https://github.com/scalikejdbc/scalikejdbc/blob/66b4fdbdc5afcaac11bdab90a285fb479d024992/scalikejdbc-cli/scripts/setup.sh#L141
- https://github.com/scalikejdbc/scalikejdbc/blob/66b4fdbdc5afcaac11bdab90a285fb479d024992/scalikejdbc-cli/scripts/setup.bat#L122

**Comment by seratch** [comment]
That's true. We should consider the way to continuously keep it up-to-date. 

However, just updating them to the latest so far is pretty easy. A contribution change.

**Comment by seratch** [comment]
Kenji always takes care of this. Thank you for your work on it.
