### ISSUE TITLE
Unicode arrows and SQL syntax

### ISSUE THREAD

**Issue by nrinaudo** [scalikejdbc/scalikejdbc#715]
scalikejdbc defines `->`  as special SQL syntax in `scalikejdbc.interpolation.SQLSyntax`.

The problem is that some of us like to have `→` instead, and have scalariform or scalafmt configured to replace all occurrences of `->` to `→` - the two are expected to be strictly equivalent, and replacing one with the other not to change anything.

Since scalikejdbc defines `->` but not `→`, however, the code stops compiling after replacement.

The fix is simple enough - declare `→` as an alias for `->`. I'm happy to submit a PR for this if the change is deemed interesting.

**Comment by seratch** [comment]
@nrinaudo I understand your situation. However, I myself don't prefer using `→` in Scala code. Therefore, I'd like to avoid having `→` in this library.

I would appreciate your understanding. Please have five lines of code in your applications.

```scala
import scalikejdbc._
implicit class SQLSyntaxAllow(s: SQLSyntax) {
  def → [A](value: A)(implicit ev: ParameterBinderFactory[A]): (SQLSyntax, ParameterBinder) = (s, ev(value))
  def → (value: ParameterBinder): (SQLSyntax, ParameterBinder) = (s, value)
}
```

**Comment by nrinaudo** [comment]
@seratch disappointing, of course, but I understand where you're coming from, and it's your project to do with as you please.

Thank you for taking the time to answer and providing a workaround. As far as I'm concerned, it's completely fine to close this issue and flag it as _WONTFIX_.
