### ISSUE TITLE
A question about implementing ParameterBinderFactory[UUID]

### ISSUE THREAD

**Issue by denisftw** [scalikejdbc/scalikejdbc#716]
If I understand correctly, in version 3.0, people using `UUID`s are expected to implement an instance of `ParameterBinderFactory[UUID]`, otherwise code will not compile:

```scala
  implicit val uuidFactory = ParameterBinderFactory[UUID] {
    value => (stmt, idx) => stmt.setObject(idx, value)
  }
```

After implelementing the factory as shown above, everything compiles, but I still see messages like these in log (I'm using SQL interpolation if that's important):

```text
The parameter(35589e9a-eacb-4498-9710-96e28492bb2d) is bound as an Object.
The parameter(35589e9a-eacb-4498-9710-96e28492bb2d) is bound as an Object.
```

I was wondering if it is possible to eliminate these messages somehow.
Thanks!

**Comment by xuwei-k** [comment]
scalikejdbc just use slf4j. You can disable debug log.

- https://github.com/scalikejdbc/scalikejdbc/blob/3.0.1/scalikejdbc-core/src/main/scala/scalikejdbc/StatementExecutor.scala#L118
- https://stackoverflow.com/a/2386691

**Comment by denisftw** [comment]
Oh, actually you're right!

I just looked at my configuration and realized that I had been writing SQL statements as 'debug'. After raising it to 'info' and adjusting `logback.xml` everything started working properly.

Thanks @xuwei-k

**Comment by seratch** [comment]
Let me close this.
