### ISSUE TITLE
Some column caches in SQLSyntaxSupports are always empty

### ISSUE THREAD

**Issue by tototoshi** [scalikejdbc/scalikejdbc#729]
https://github.com/scalikejdbc/scalikejdbc/blob/0677afb40c6b3c8a09c3005fe0c56f320d700ef0/scalikejdbc-interpolation/src/main/scala/scalikejdbc/SQLSyntaxSupportFeature.scala#L718-L727
https://github.com/scalikejdbc/scalikejdbc/blob/0677afb40c6b3c8a09c3005fe0c56f320d700ef0/scalikejdbc-interpolation/src/main/scala/scalikejdbc/SQLSyntaxSupportFeature.scala#L747-L753
https://github.com/scalikejdbc/scalikejdbc/blob/0677afb40c6b3c8a09c3005fe0c56f320d700ef0/scalikejdbc-interpolation/src/main/scala/scalikejdbc/SQLSyntaxSupportFeature.scala#L608-L615

Should `getOrElseUpdate` be used instead of `getOrElse` ?

**Comment by seratch** [comment]
I see. My bad.
