### ISSUE TITLE
Cannot find column name when using SQLSyntaxSupport

### ISSUE THREAD

**Issue by amogh09** [scalikejdbc/scalikejdbc#738]
I have a model as shown below. 

```scala
case class House (
    id: Int,
    name: String,
    cityId: Int,
    leaseInterval: Interval
)

case class Interval(start: ZonedDateTime, end: ZonedDateTime)
```

My table is defined as shown below.

```sql
CREATE TABLE houses(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,
  name VARCHAR(255),
  city_id INT NOT NULL,
  start_at datetime DEFAULT NULL,
  end_at datetime DEFAULT NULL,
);
```

I am trying to write a method that saves a house in MySQL database as shown below.
```scala
val c = House.column
val id = sql"insert into ${House.table} (${c.name}, ${c.cityId}, ${c.startAt}, ${c.endAt}) values (${name}, ${cityId}, ${startAt}, ${endAt})".stripMargin.updateAndReturnGeneratedKey.apply()
```

But I get the following compilation error.
```
House#startAt not found. Expected fields are #id, #name, #cityId, #leaseInterval.
```

I get the same error for `c.endAt` column too.

Am I doing something wrong? The error goes away if I use `c.column("start_at")`.

**Comment by seratch** [comment]
ScalikeJDBC offers type-safe APIs in SQLSyntaxSupport. The APIs requires defining the corresponding fields in entity classes.

If you would like to avoid having some fields corresponding to database columns in your entity classes, as you mentioned, you should use column/field method with string names.

**Comment by amogh09** [comment]
I see, thank you for your response.
