### ISSUE TITLE
`updateAndReturnGeneratedKey` returns wrong key when used with `on duplicate key update`

### ISSUE THREAD

**Issue by amogh09** [scalikejdbc/scalikejdbc#740]
Example -
```
+----+------------+
| id  | name     |
+----+------------+
|  1 | ABC       |
|  2 | DEF       |
+----+------------+
```

Performing the following query returns `3`.
```
val c = Table.column
val id = sql"""insert into ${Table.table} (${c.id}, ${c.name}) values (2, 'GHI') on duplicate key update ${c.name}='GHI'""".updateAndReturnGeneratedKey.apply()
println(id) // prints 3
```

Table after update looks like -
```
+----+------------+
| id  | name      |
+----+------------+
|  1 | ABC        |
|  2 | GHI        |
+----+------------+
```

**Comment by seratch** [comment]
ScalikeJDBC just returns the value came from the JDBC driver that you use. https://github.com/scalikejdbc/scalikejdbc/blob/3.0.2/scalikejdbc-core/src/main/scala/scalikejdbc/DBSession.scala#L531-L566

When you use MySQL JDBC driver directly, does it also return 3 for the case? If so, I'm afraid that there is nothing to do on scalikejdbc side so far.

**Comment by seratch** [comment]
@amogh09 Any updates? As a maintainer of this library, I would like to leave question issues opened without taking any actions. If we don't have any further discussions on this, let me close this issue.

**Comment by amogh09** [comment]
@seratch Sorry for not replying for so long. I didn't test jdbc directly and ended up using separate methods for create and update. I'd leave it to you whether to close the issue or not. 😇

**Comment by seratch** [comment]
Thanks.
