### ISSUE TITLE
WrappedResultSet bigDecimal functions use java version instead of scala

### ISSUE THREAD

**Issue by Cosmo439** [scalikejdbc/scalikejdbc#744]
In the WrappedResultSet, the `bigDecimal` and `bigDecimalOpt` functions return `java.math.BigDecimal` instead of `scala.math.BigDecimal` for scala 2.12.

This is using version 3.0.1 of scalikejdbc.

**Comment by seratch** [comment]
It's by design. WrappedResultSet's methods often return Java type values. Try `WrappedResultSet#get[scala.math.BigDecimal]("xxx")` instead. That should work for you.

**Comment by Cosmo439** [comment]
That seems an odd design choice for a library that is built primarily for the Scala community.  I would expect it to work with the Scala types instead of the Java types.

Using the `WrappedResultSet#get[Option[BigDecimal]]("xxx")` works for my use case though.
