### ISSUE TITLE
support new methods since Java 8

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#748]
- [x] https://github.com/scalikejdbc/scalikejdbc/pull/747
- [x] https://github.com/scalikejdbc/scalikejdbc/pull/746
- [ ] add some methods in [SQL.scala](https://github.com/scalikejdbc/scalikejdbc/blob/3.0.2/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala)
- [x] add some methods in [DBSession](https://github.com/scalikejdbc/scalikejdbc/blob/3.0.2/scalikejdbc-core/src/main/scala/scalikejdbc/DBSession.scala)  https://github.com/scalikejdbc/scalikejdbc/pull/749
 
any others?

**Comment by seratch** [comment]
@xuwei-k Do we still have some stuff to do?

**Comment by seratch** [comment]
>add some methods in SQL.scala

@xuwei-k What did you mean by this? If we already finished the tasks you initially planned, let's close this issue. If we find more things to do in the future, we can reopen this issue or create another specific issue for it.
