### ISSUE TITLE
Release 3.0.3?

### ISSUE THREAD

**Issue by BardurArantsson** [scalikejdbc/scalikejdbc#750]
I'm just curious, is the 3.0.3 release going to be out any time soon? I'm kind of waiting for my #706 to get into a released version :). No rush, obviously, but I'd like to have an approximate idea of a time line :)

**Comment by seratch** [comment]
Not decided yet. But it will work releases soon. Maybe, early in September. The version will be 3.1.0 because your changes are not bin-compatible with 3.0.x series.

**Comment by BardurArantsson** [comment]
OK.

I actually thought I was being bin-compatible, but no matter :). Thanks for the response.
