### ISSUE TITLE
Implement filter and flatMap for scalikejdbc.SQL

### ISSUE THREAD

**Issue by azymnis** [scalikejdbc/scalikejdbc#754]
Hello,

Is there a reason why `scalikejdbc.SQL` does not have `filter` and `flatMap` methods? This would make writing extractors more convenient and would allow the usage of for comprehensions.

**Comment by seratch** [comment]
In principle, using where clause in SQL statements would be straightforward. But, indeed, having `filter` or `flatMap` may be useful for some cases like testing if you can ignore a row.

**Comment by xuwei-k** [comment]
Implement `flatMap` method makes no sense to me because I think `scalikejdbc.SQL` is not Monad.

**Comment by azymnis** [comment]
Why shouldn't `SQL` be a Monad?

**Comment by seratch** [comment]
We are not planning to work on this so far. As I mentioned above, utilizing where clauses for filtering data and building data structure by utilizing SQL functionalities are recommended for ScalikeJDBC users. Allow me to close this issue now. Thanks for taking the time to make this suggestion.
