### ISSUE TITLE
Question about using strings as table and column names

### ISSUE THREAD

**Issue by apejak** [scalikejdbc/scalikejdbc#767]
I have used sql"" syntax to insert data to table like in http://scalikejdbc.org/documentation/sql-interpolation.html.

As documentation showed, I have provided table name with ${} syntax. No errors occurred but no elements were inserted into DB. Had to change the code to use SQL(query).execude.apply.

**Comment by seratch** [comment]
The documentation should be correct. Can you share a minimum working example to reproduce your problem?

**Comment by apejak** [comment]
sql"INSERT INTO ${tableName}_market (ID, MARKETID, MARKETNAME, PRICE, TIMESTAMP) VALUES "+
s"($id, $marketId, '$marketName', $price, DEFAULT) ON CONFLICT(ID, MARKETID)" +
s" DO UPDATE SET MARKETNAME = '$marketName', PRICE = $price, TIMESTAMP = DEFAULT;"

**Comment by seratch** [comment]
Embedding raw string values as parts of SQL statement is not allowed in ScalikeJDBC because doing that easily brings SQL injection vulnerabilities to your applications.

If you want to do that, use `SQLSyntax.createUnsafely` or legacy `SQL.apply(String)` with our own risk. see also: https://github.com/scalikejdbc/scalikejdbc/blob/3.1.0/scalikejdbc-core/src/test/scala/scalikejdbc/interpolation/SQLSyntaxSpec.scala#L469-L473

**Comment by apejak** [comment]
![image](https://user-images.githubusercontent.com/6825749/31588450-16a9d73a-b1f2-11e7-96fc-074293e482a2.png)

Then, what is the difference between my approach and one mentioned in the documentation?

**Comment by seratch** [comment]
Your `query` is a string value. Your example embeds the whole `query` object as a single value into SQL interpolation object.

The documentation shows you how to embed values regardless of whether they are a SQLSyntax object or any other values into SQL interpolation (`sql"...."`).

**Comment by alexanderzafirov** [comment]
It was a pure coincidence that I found this valuable conversation. I would kindly request this issue's title to be changed to something like "using strings as table and column names". Or maybe @seratch you don't want to advertise this feature at all?

**Comment by seratch** [comment]
I just updated the title. Also, if @apejak doesn't mind it, I would like to close this issue because I as a maintainer of this library don't have any action plans for this issue.

**Comment by seratch** [comment]
I didn't hear anything back from you. Let me close this issue (please understand it).
