### ISSUE TITLE
ClassCastException occurs when I use .toOptionalOne().

### ISSUE THREAD

**Issue by katainaka0503** [scalikejdbc/scalikejdbc#769]
The code below throws ClassCastException.
```scala
case class Owner(id: Long, name: String, groupId: Long)

case class Group(id: Long, name: String)

case class Pair(owner: Owner, group: Group)

val (g, o) = (Group.syntax, Owner.syntax)

val maybePair: Option[Pair] =
  withSQL {
    select.from(Group as g).leftJoin(Owner as o).on(g.id, o.groupId)
  }
    .one(Group(g))
    .toOptionalOne(Owner.opt(o))
    .map { (group, owner) => Pair(owner, group) }
    .single
    .apply()

println(maybePair.foreach(pair => println(pair.owner))) //ClassCastException occurs here.
```
`ClassCastException` is thrown not in scalikeJDBC method but when I use the value returned from scalikeJDBC. But I think it is caused by casting in scalikeJDBC implementation. When `Owner.opt(o)` returns `None`, an instance of `Group` is cast to `Pair` in the scalikeJDBC's code. 

I think it is basically caused by arguments' type.
`.one()` receives `WrappedResult => A`
,`.toOptionalOne()` receives `WrappedResult => Option[B]`
, and `.map()` receives `(A, B) => Z`.
It looks a little hard to properly get a instance of `Z` when `toOptionalOne()`'s argument returns `None`.

**Comment by seratch** [comment]
Sorry for my late response. If the runtime exception happens, we should improve the implementation.

**Comment by katainaka0503** [comment]
Because invalid cast can   [here](https://github.com/scalikejdbc/scalikejdbc/blob/2e8e85eb4607bc0b44f9d938f071d37c376d8bd6/scalikejdbc-core/src/main/scala/scalikejdbc/OneToOneSQL.scala#L29), the exception is thrown when I use return value of `apply()` later.

**Comment by seratch** [comment]
I see. I understand your point. Regarding this issue, merging your PR #768 is fine for me. Could you re-open it?

**Comment by katainaka0503** [comment]
@seratch Reopened #768.

**Comment by xuwei-k** [comment]
Can we close this?

**Comment by seratch** [comment]
Yes, we can close this. ClassCastException can still happen but #768 fixed the problem there is o way to avoid the exception when `toOptionalOne` returns `None`.
