### ISSUE TITLE
Case insensitive column names lead to NumberFormatException

### ISSUE THREAD

**Issue by INRIX-Cory-Bradshaw** [scalikejdbc/scalikejdbc#770]
Using scalikejdbc gen, with column names objectid (type Int) and OneWay(type String). (Table name is nw)

When trying to parse the findAll(), the lookup sees that they are case insensitive, and when the WrappedResultSet.scala (line 469) :
`
    wrapIfError(implicitly[TypeBinder[A]].apply(underlying, columnLabel))
`

This results in the underlying.columns to contain two entries : O_on_nw and o_on_nw. When attempting to retrieve and parse the objectid as an Int, it actually retrieves OneWay, and attempts to parse to an int, and fails, throwing a NumberFormatException. I noticed the underlying.columns had been set to case-insensative, so I assume it matched O_on_nw rather than o_on_nw, but it seems like if this was generated/configured as case insensative, the lookup values should have been O_on_nw and o2_on_nw, noticeing that we are doing case insensative column names, to avoid this wrong lookup.

When the columns listings have all uppercase, this problem goes away, but it took a few hours to figure out where the problem was coming from.

Code snippet below:

```scala
object Nw extends SQLSyntaxSupport[Nw] {

  override val tableName = "nw"

  override val columns = Seq("ONEWAY", "Objectid")

 def apply(n: SyntaxProvider[Nw])(rs: WrappedResultSet): Nw = apply(n.resultName)(rs)

  def apply(n: ResultName[Nw])(rs: WrappedResultSet): Nw = new Nw(
    oneway = rs.get(n.oneway),
    objectid = rs.get(n.objectid)
  )
val n = Nw.syntax("nw")

  override val autoSession = AutoSession

  def find(objectid: Int)(implicit session: DBSession = autoSession): Option[Nw] = {
    withSQL {
      select.from(Nw as n).where.eq(n.objectid, objectid)
    }.map(Nw(n.resultName)).single.apply()
  }

  def findAll()(implicit session: DBSession = autoSession): List[Nw] = {
    withSQL(select.from(Nw as n)).map(Nw(n.resultName)).list.apply()
  }
}
```

I am using version 2.5.0 of scalikejdbc with the 1.3.1 version of jtds connected to SQL Server.

The mapper-generator version I am using is 3.1.0 (which might be a culprit? maybe?)

**Comment by seratch** [comment]
I've not checked your situation with working code, but overriding `nameConverters` may help you resolve the problem. http://scalikejdbc.org/documentation/sql-interpolation.html#why-can-we-use-undefined-methods-such-as-m-groupid

>I am using version 2.5.0 of scalikejdbc with the 1.3.1 version of jtds connected to SQL Server.
>The mapper-generator version I am using is 3.1.0 (which might be a culprit? maybe?)

As you worried, you should use the same version.

**Comment by seratch** [comment]
I believe that I don't have any plans to take for this issue now. Do you mind closing this issue? If you won't respond within a few days, we would like to close this issue.

**Comment by INRIX-Cory-Bradshaw** [comment]
You can close this. I forgot I had it opened. Switching to the same version of plugins resolved the issue I believe, but we did not pursue using these features anyway.

**Comment by seratch** [comment]
Thanks.
