### ISSUE TITLE
JSON/JSONB support for PostgreSQL

### ISSUE THREAD

**Issue by passos** [scalikejdbc/scalikejdbc#771]
Hi,
Thanks for the great library.

I am new to scalikejdbc and wondering how to handle PostgreSQL's JSON/JSONB data type?

The following is a sample scenario.

DDL
```sql
create table post
(
	id serial not null
		constraint post_pkey
			primary key,
	entity jsonb
)
;
```

Scala
```scala
final case class Post(
    id: Long
    entity: Option[String] // suppose to be JSONB datatype
)

object Post extends SQLSyntaxSupport[Post] {
  override val tableName = "post"
  override val columns = Seq(
    "id", "entity"
  )

  def apply(rs: WrappedResultSet): Post = new Post(
    id = rs.long("id")
    entity = rs.stringOpt("entity")
  )

  def apply(s: SyntaxProvider[Post])(rs: WrappedResultSet): Post = apply(s.resultName)(rs)

  def apply(s: ResultName[Post])(rs: WrappedResultSet): Post = new Post(
    id = rs.get(s.id),
    entity = rs.get(s.entity),
  )

  def find(id: Long)(implicit session: DBSession = autoSession): Option[Post] =
    withSQL {
      select.from(Post as p).where.eq(p.id, id)
    }.map(Post(p)).single.apply()

  def create(entity: Option[String])(implicit session: DBSession = autoSession): Post = {
    val id = withSQL {
      insert.into(Post).namedValues(
        column.entity -> entity
      )
    }.updateAndReturnGeneratedKey.apply()

    Post(
      id = id,
      entity = entity
    )
  }

  def save(m: Post)(implicit session: DBSession = autoSession): Post = {
    withSQL {
      update(Post)
        .set(
          column.entity -> m.entity
        ).where.eq(column.id, m.id)
    }.update.apply()
    m
  }
}

```

The `entity` field is defined as JSONB in database. When I implement the model I don't know what data type should I use in Scala for JSONB. (it's defined as String for now and surely it doesn't work). It seems there is no related methods in WrappedResultSet.

**Comment by seratch** [comment]
For special types, try using ParameterBinder. http://scalikejdbc.org/documentation/operations.html#using-parameterbinder

**Comment by stefanbacon** [comment]
> withSQL {
>       scalikejdbc.update(CalendarVendorObject).set(
>         column.description -> description,
>         column.updated -> now,
>         {
>           val jsonObject = new PGobject()
>           jsonObject.setType("json")
>           jsonObject.setValue(settings.get)
>           (column.settings, ParameterBinder(settings.get, (ps, i) => ps.setObject(i, jsonObject)))
>         }
>       )
>     }.update.apply()

**Comment by faresbessrour** [comment]
To add on @stefanbacon answer, I had to use a Json Mapper to insert correctly my object. so something like this worked:

```scala
import com.twitter.finatra.json.FinatraObjectMapper

val mapper = FinatraObjectMapper.create()
val id = withSQL {
  QueryDSL.insert.into(Zones)
    .namedValues(
      column.floor_plan_id -> z.floor_plan_id,
      column.meta_data -> z.meta_data,
      {
        val jsonObject = new PGobject()
        jsonObject.setType("json")
        jsonObject.setValue(mapper.writeValueAsString(z.zones))
        column.zones -> ParameterBinder(z.zones, (ps, i) => ps.setObject(i, jsonObject))
      }
    )
}.updateAndReturnGeneratedKey.apply.toInt
```

Where mapper is just an object with some cool json converters.

Now I'm working on retrieving the data back to the original case class type, I will add the answer here when I figure it out.

**Comment by faresbessrour** [comment]
To fetch you can select as string and then use your mapper to get the type you need:
```scala
  def fetch(id: Int)(implicit session: DBSession): Zones = {
    val z = Zones.syntax("z")
    withSQL {
      QueryDSL.select.from(Zones as z).where.eq(z.id, id)
    }.map(
      rs =>
        new Zones(
          rs.int(columnIndex = 1),
          rs.int(columnIndex = 2),
          rs.string(columnIndex = 3),
          mapper.parse[List[Zone]](rs.string(columnIndex = 4))
        )
    ).single.apply.get
}
```

For example here I need to retrieve a List of case class Zone.

So I have a mapper that parses the column 4 of type `string` (which is in reality of type `json` in postgres) and return a type of `List[Zone]` (Zone is a `case class` here)

**Comment by alwins0n** [comment]
just fyi, if you connect to your database with `stringtype`=`unspecified` you can insert string serialized json object just as string parameter (no need to create a `PGObject`). the pg server will do the right thing.

**Comment by seratch** [comment]
Thank you guys for sharing the valuable knowledge here! 

As the ScalikeJDBC library won't have a built-in feature for this, let me close this issue. You can go with the ways mentioned in this thread. 

If someone is interested in making an additional module to more smoothly support PostgreSQL JSON/JSONB types on top of scalikejdbc-core, we are happy to have a link to the project in ScalikeJDBC document website or its README. Also, if the library is widely accepted in the community and the author would like to merge it to this project as a new optional module, I'm open to the idea, too.
