### ISSUE TITLE
Scaladoc missing several useful classes

### ISSUE THREAD

**Issue by gravelld** [scalikejdbc/scalikejdbc#772]
I can't find important traits like `SQLSyntaxSupport` or `SQLInterpolationFeature` in the core API docs at https://www.javadoc.io/doc/org.scalikejdbc/scalikejdbc-core_2.11/3.1.0 . Am I reviewing the wrong docs?

**Comment by seratch** [comment]
You can find docs for them here: https://www.javadoc.io/doc/org.scalikejdbc/scalikejdbc-interpolation_2.11/3.1.0

**Comment by gravelld** [comment]
Ah, it's not considered core API. I see, thanks, sorry for my misunderstanding.
