### ISSUE TITLE
plus method for SQLSyntax

### ISSUE THREAD

**Issue by frankbe** [scalikejdbc/scalikejdbc#774]
Hi,

could you consider to add a plus method to SQLSyntax which works like the existing append method? 
` def + (syntax: SQLSyntax): SQLSyntax = this.append(syntax)` 

than one could write 
`baseSql + whereSql`

instead of
`baseSql.append(whereSql)`

**Comment by seratch** [comment]
Sorry for my late reply. It's okay for me if you mean simply having `+` method in `SQLSyntax`.

**Comment by frankbe** [comment]
Thanks for response. The reason I asked was that I was thinking about replacing a proprietary jdbc framework in a a current project with skcalikejdbc. In the proprietary jdbc framework I used many times a + method to concat sql statements. So it would have been a bit easier to switch. But for other reasons I decided to stick with the propretary sql framework first, and extend it for my needs.
But I still think it would be a bit nicer to have a + method, just for readability, especially when you need to concat more than two sql statements together a once.
