### ISSUE TITLE
Nested One-to-X?

### ISSUE THREAD

**Issue by gravelld** [scalikejdbc/scalikejdbc#775]
The One-to-X api works nicely for joining flat tables, but what if some joins are joined to other tables?
```sql
SELECT grandparent.name, parent.name, child.name
FROM grandparent
LEFT JOIN parent on grandparent.id = parent.grandparent
LEFT JOIN child on parent.id = child.parent
```

Is it possible to use the One-to-X for all levels of the nesting?

**Comment by seratch** [comment]
Sorry for my late reply. one-to-x API doesn't support all nested cases. 

If you would like to bind result set to nested Scala objects, you need to manually handle it in `map` method (`sql"...".map(do something here).list.apply()`).

As for your example query, choosing `child` as the base object simply works.

```scala
val childrenWithParentsAndGrandParents: (String, String, String) = 
sql"""
  SELECT
    child.name c_name,
    parent.name p_name,
    grandparent.name gp_name
  FROM child
  LEFT JOIN parent on parent.id = child.parent
  LEFT JOIN grandparent on grandparent.id = parent.grandparent
"""
.map { rs => (rs.get[String]("gp_name"), rs.get[String]("p_name"), rs.get[String]("c_name")) }
.list.apply()
```

**Comment by gravelld** [comment]
Thanks.
