### ISSUE TITLE
Ill-formed SQL can be generated by SelectSQLBuilder.where

### ISSUE THREAD

**Issue by iTakeshi** [scalikejdbc/scalikejdbc#783]
Version: 3.1.0

The code shown below generates an ill-formed SQL statement:
```scala
select.from(Model as m).where(None).and(m.id = 1)
```
```sql
select m.id as i_on_m from model m and (m.id = ?)
```

This is because the method `where` of `SelectSQLBuilder` can return `ConditionSQLBuilder` without appending a SQL term `where` to the statement, when the argument is `None`. https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-interpolation/src/main/scala/scalikejdbc/QueryDSLFeature.scala#L467

**Comment by seratch** [comment]
I understand your point. At this moment, `sqls.and` is not flexible enough to do well in your cases. I recommend you using `sqls.toAndConditionOpt` for dynamic queries.

```scala
val (productId, accountId) = (Some(1), None)
val ids = withSQL {
  select(o.result.id).from(Order as o)
    .where(sqls.toAndConditionOpt(
      productId.map(id => sqls.eq(o.productId, id)),
      accountId.map(id => sqls.eq(o.accountId, id))
    ))
    .orderBy(o.id)
}.map(_.int(1)).list.apply()
```
http://scalikejdbc.org/documentation/query-dsl.html#dynamic-query-building

**Comment by iTakeshi** [comment]
Actually that's the solution I'm using to avoid this problem.
Although I understand it's difficult, I think this library should have some constraints to prevent this kind of problems from happening. I'm trying some hacks, but they don't works at this moment.

For now, I'm closing this issue. Thanks for your answer.

**Comment by seratch** [comment]
I agree that we should be able to have a safer implementation in terms of validity of generated SQLs.

When you succeed to build an alternative solution for this, share your idea with me. It may be possible to merge your code as an experimental one in the future releases.
