### ISSUE TITLE
Elimiate joda-time and joda-convert dependencies

### ISSUE THREAD

**Issue by fancywriter** [scalikejdbc/scalikejdbc#784]
Why are they used inside scalajdbc-core? Can they be moved outside, like into some sort of separate module?
I would make use of **java.time.*** instead of joda-time if possible, because it doesn't require additional dependency which satisfy project philosophy to not be bothered by depedency hell, which is in fact can be caused by joda dependency.

Or I would make the scope Provided instead of Compile, so that people actually using joda library can use it.

**Comment by seratch** [comment]
I agree with you. Carving out the dependencies and scalikejdbc's related code to a sub-module is the best way to improve the situation. As the first step, changing their scope provided is also reasonable enough.

**Comment by xuwei-k** [comment]
WIP https://github.com/xuwei-k/scalikejdbc/commit/bf5755ee1913ed02437e2fadad8d1415fbc8b429
