### ISSUE TITLE
Elegant way to setAutoCommit(false)?

### ISSUE THREAD

**Issue by gravelld** [scalikejdbc/scalikejdbc#792]
[Because the Postgresql JDBC driver requires an explicit `setAutoCommit(false)` to use `fetchSize`](https://stackoverflow.com/a/1468140/28190), I'm having to do:
```
val cp: ConnectionPool = ConnectionPool()
() => using(cp.borrow()) { conn =>
  conn.setAutoCommit(false) // 854 in psql driver, must be explicitly set
  DB(conn, cp.connectionAttributes, SettingsProvider.default).autoClose(false).readOnly( implicit session => { 
    // run query
  })
}
```
Is there a way to `setAutoCommit(false)` using the nicer `DB` API?

**Comment by seratch** [comment]
How about using `DB.localTx { implicit session => }`? The call does `conn.setAutoCommit(false)` internally.

**Comment by gravelld** [comment]
Sorry, should check the code myself, but does `localTx` have any other performance implications compared to `readOnly` (which is what I'd normally use)?

**Comment by gravelld** [comment]
I have switched to `localTx` for now.

[I also noticed my original code wasn't even setting `autoCommit` because of the check in `ActiveSession`](https://groups.google.com/forum/#!topic/scalikejdbc-users-group/Df05SLrwo9w) where the fact that `jtaDataSourceCompatible` was false meant `autoCommit` was internally overridden anyway.
