### ISSUE TITLE
Exception in thread "main" scalikejdbc.ResultSetExtractorException: Failed to retrieve value because For input string: "true". If you're using SQLInterpolation, you may mistake u.id for u.resultName.id.

### ISSUE THREAD

**Issue by jackiehff** [scalikejdbc/scalikejdbc#808]
When I query data from MySQL, there is a column which defined AS tinyint.Then I use rs.int(3) to get the column value, but I get the following exception:

> Exception in thread "main" scalikejdbc.ResultSetExtractorException: Failed to retrieve value because For input string: "true". If you're using SQLInterpolation, you may mistake u.id for u.resultName.id.
	at scalikejdbc.WrappedResultSet.wrapIfError(WrappedResultSet.scala:34)
	at scalikejdbc.WrappedResultSet.get(WrappedResultSet.scala:506)
	at scalikejdbc.WrappedResultSet.int(WrappedResultSet.scala:223)

It seems like scalikejdbc default treat tinyint as Boolean value.

**Comment by seratch** [comment]
If I understand your situation correctly, the value "true" seems to be returned from the JDBC driver you use.

**Comment by seratch** [comment]
MySQL handles tinyint as the alias for boolean type. Thereby, the MySQL JDBC driver (and maybe MariaDB driver behave in the same way) seems to return boolean values. https://stackoverflow.com/questions/16798744/why-does-tinyint1-function-as-a-boolean-but-int1-does-not

ScalikeJDBC cannnot channge the behavior. Do you mind if I close this issue? I don't have any further actions for this.

**Comment by jackiehff** [comment]
Yes，please！Really appreciate your reply！

**Comment by hagai-lvi** [comment]
@seratch Bumped into this issue as well
How do you suggest to handle this? `resultSet.boolean()` instead of `resultSet.int()`?
Or is there some more elegant way that can handle both cases?

**Comment by seratch** [comment]
@hagai-lvi 
>resultSet.boolean() instead of resultSet.int()?

Exactly.

**Comment by Sparker0i** [comment]
Hello @seratch , I have just encountered this error as well, except that my table does contain actual null values, and I want to be able to store those null values inside the list of case class objects. How do you suggest me to handle the nullable values. My code is simply performing this:

```
using(DB(ConnectionPool.borrow())) { db =>
            SQL(query)
                .map(e => LastUpdateTimes(
                    e.int("A"),
                    e.int("B"),
                    e.string("C").trim,
                    e.string("D").trim,
                    e.int("E"),                   //Nullable
                    e.timestamp("F")
                ))
                .list()
                .apply()
        }
```

**Comment by seratch** [comment]
@Sparker0i `rs.get[Option[Int]]("E")` or `rs.intOpt("E")` works for you. If you use MySQL and want to handle the int value as boolean, `rs.booleanOpt` or `rs.get[Option[Boolean]]` should work.
