### ISSUE TITLE
Utility method for loading SQL script?

### ISSUE THREAD

**Issue by annappropriate** [scalikejdbc/scalikejdbc#825]
It would be super useful to have a built-in util to load SQL dumps or other scripts (in my case, for testing purposes).
This is what I implemented (dump has no multiline comments):
```
  def runSqlDumpScript(): Boolean = {
    val stream = getClass.getResourceAsStream("/sql/sqldump_2017-12-27.sql")
    val statements = Source.fromInputStream(stream).getLines()
      .filterNot(line => line.startsWith("--") || line.startsWith("/*") || line.isEmpty)
      .mkString.split(";")
    statements.map(SQL(_).execute().apply()).forall(_ == true)
  }
```

**Comment by seratch** [comment]
Sorry, I didn't respond to this issue at that time.

Although I don't have any plans to have the feature in this library, your simple code looks useful for others who need the similar one.

Thank you for sharing this and your suggestion!

**Comment by seratch** [comment]
As I said before, I don't have any plans to work on something which is related to this proposal. In general, keeping any issues open for a while without having any plans to work on it is not appropriate. Let me close this for now. It would be appreciated if you could understand project maintainers' situation.

If you have more points to discuss here or are going to make a pull request corresponding to this issue, feel free to re-open this issue at any time.
