### ISSUE TITLE
java.lang.ClassCastException: com.zaxxer.hikari.pool.PoolEntry cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by benoit-ponsero** [scalikejdbc/scalikejdbc#827]
Hello,

Sometimes, i get this error in my app : 

> java.lang.ClassCastException: com.zaxxer.hikari.pool.PoolEntry cannot be cast to java.lang.String
        at scalikejdbc.Binders$$anon$2.apply(Binders.scala:36)
        at scalikejdbc.interpolation.SQLSyntax.eq(SQLSyntax.scala:68)
        at scalikejdbc.interpolation.SQLSyntax$.eq(SQLSyntax.scala:289)
        at net.smartbe.contract.market.Currency$.findByCode(Currency.scala:144)

The error is not reproductible and happen **randomly**

Here is the code of my model Currency : 

```
def findByCode(code:String)(implicit session: DBSession = autoSession): Option[Currency] =
    findBy(
      sqls.eq(c.code, code)
    )
```

I use : 
Play Framework 2.6.11
scalikejdbc 3.2.0
scalikejdbc-config 3.2.0
scalikejdbc-play-dbapi-adapter  2.6.0-scalikejdbc-3.2

Does someone have an idea ?

**Comment by seratch** [comment]
I am not sure what the cause of the problem. Did you figure out it?

**Comment by seratch** [comment]
Let me close this issue due to inactivity. Please feel free to reopen or create another one as necessary.
