### ISSUE TITLE
FatalError jvm crash

### ISSUE THREAD

**Issue by benoit-ponsero** [scalikejdbc/scalikejdbc#828]
Hello,

It seems that scalike is very unstable on scala 2.12. 
Something turn scalike dirty. sometimes i have classcastexception like https://github.com/scalikejdbc/scalikejdbc/issues/827 , sometimes my jvm crash.

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fb83356488a, pid=30475, tid=0x00007fb710cee700

 JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 J 12866 C1 scalikejdbc.Binders$$$Lambda$641.apply(Ljava/lang/Object;)Ljava/lang/Object; (8 bytes) @ 0x00007fb83356488a [0x00007fb833564800+0x8a]

here is the complete trace:
https://gist.github.com/benoit-ponsero/db42620fe7e54fe51c62776744392825

I need some help please.

**Comment by benoit-ponsero** [comment]
Hi, I updated my jvm from 1.8.0_101 to 1.8.161 and everything work fine since 1 week. 

which version & options do you use for publishing ?

**Comment by seratch** [comment]
This is the script used to release the libs. https://github.com/scalikejdbc/scalikejdbc/blob/master/scripts/release_all.sh
