### ISSUE TITLE
Add a clean / reload mechanism for metadata loaded from the DB

### ISSUE THREAD

**Issue by eyalroth** [scalikejdbc/scalikejdbc#907]
The "registered columns" of an entity are used in various locations to validate the correctness of a query; for instance, when using `namedValues` in the `insert` DSL. The columns are read from the DB by `SQLSyntaxSupportFeature`. Thing is, these columns are loaded only once (upon first usage), so if there's a change to them (in the DB) the framework would not be aware of this.

When does this happen? Well, consider a set of migration scripts that are executed when building the schema using one of multiple frameworks (Flyway, for instance):

1. An SQL script first creates the table / entity.
2. A code (Java / Scala) script uses the entity's DAO to read and manipulate the data.
3. An SQL script alters the table / entity (by, say, adding a column).

The second script uses scalikejdbc and hence the registered columns are loaded, but then when the third script updates the table scalikejdbc stays out-of-date, thus rendering future operations invalid.

My suggested solution here is to add a "clean metadata" API for scalikejdbc's entities. It could either be a per-entity thing or a global one. This API would be invoked right after executing the migration scripts, allowing for scalikejdbc to read the most up-to-date metadata.

**Comment by seratch** [comment]
@eyalroth Sorry for my belated reply. The library already has an API to flush cached column data. https://github.com/scalikejdbc/scalikejdbc/blob/36492f6c3c4c388168ecfcc25ecbdf1843bc9c7e/scalikejdbc-interpolation/src/test/scala/scalikejdbc/SQLInterpolationSpec.scala#L915-L916
