### ISSUE TITLE
Using value classe as Entity ID

### ISSUE THREAD

**Issue by TerryNoWay** [scalikejdbc/scalikejdbc#909]
Hi, 
I recently tried to use [Value classes](https://docs.scala-lang.org/overviews/core/value-classes.html) instead of Long as entities' ID: 
```scala
class CardId(val id: Long) extends AnyVal

case class Card(
  id: CardId,
  name: String,
// ...
```

But as you can imagine, scalikejdbc is not able to bind that type:
```
[error] (Compile / compileIncremental) Compilation failed
[info] Compiling 30 Scala sources and 1 Java source to /Users/noway/...
[error] /Users/noway/.../Card.scala:54:18: could not find implicit value for evidence parameter of type scalikejdbc.TypeBinder[models.entities.CardId]
[error] Error occurred in an application involving default arguments.
[error]     autoConstruct(rs, rn)
```

Q1.
**Is it possible to make scalikejdbc able to bind it natively ?**
I think that scalikejdbc could eventually bind customised AnyVal as basic types...

Q2.
**Until this improvement is implemented, do you know to handle it on my project ?**
I also need to keep the interpolation of `scala.collection.Traversable` and `java.lang.Iterable` like IDs list (`List[CardId]`).
http://scalikejdbc.org/documentation/sql-interpolation.html#natively-handled-types

**Comment by xuwei-k** [comment]
You can use value classes (or arbitrary classes) if define `scalikejdbc.TypeBinder` instance in companion object.

```scala
class CardId(val id: Long) extends AnyVal

object CardId {
  implicit val instance: TypeBinder[CardId] =
    implicitly[TypeBinder[Long]].map(new CardId(_))
}
```

**Comment by seratch** [comment]
@TerryNoWay 

Did @xuwei-k 's answer help you? If there is no other comment, let me close this issue (to be exact, not an issue) soon.
