### ISSUE TITLE
Case-insensitie operators

### ISSUE THREAD

**Issue by oviron** [scalikejdbc/scalikejdbc#921]
Is there any reasons scalikejdbc doesn't have case-insensitive operators i.e. `ILIKE`?
May i suggest to open a PR to solve this?

**Comment by seratch** [comment]
The keyword `ILIKE` is only available with PostgreSQL. It is not in the ANSI standard SQL. That's the reason why ScalikeJDBC doesn't have a DSL corresponding to it.

**Comment by oviron** [comment]
@seratch Oh, i see. Thanks for the explanation, i'll close the issue.

**Comment by KevinAtSesam** [comment]
For anybody finding this issue two years later, there is a ScalikeJDBC extension that supports Postgres specific statements:

https://github.com/roundrop/scalikejdbc-sqlsyntax-ext
