### ISSUE TITLE
JDK >= 9 date precision problem

### ISSUE THREAD

**Issue by gytisgreitai** [scalikejdbc/scalikejdbc#945]
Excerpt taken from https://bugs.openjdk.java.net/browse/JDK-8068730:

> This RFE propose to enhance the implementation of the system clocks returned by java.time.Clock, so that they offer at least the same precision than the underlying clock available on the system.

So basically this adds greater time precision in JDK >= 9 on platforms where this is available.

Let's take a basic scenario:
```

case class Account(
    id: UUID,
    createdOn: LocalDateTime = LocalDateTime.now()
  )

<.....>

class AccountRepository {

  def save(account: Account)(implicit session: DBSession): Unit = {
    sql"""insert into account (id, created_on) values(${account.id}, ${account.createdOn})"""
        .execute()
        .apply()
  }

   def findOne(id: UUID)(implicit session: DBSession = ReadOnlyAutoSession): Option[Account] = {

    sql"""select * from account where id = $id"""
        .map { rs =>
          Account(
            id = UUID.fromString(rs.string("id")),
            createdOn = rs.localDateTime("created_on")
          )
        }
        .single()
        .apply()
  }

<.....>

test("date formats should match") {

    val account = createAccount()
    accountRepository.save(account)

    val accountOption = accountRepository.findOne(account.id)
    accountOption.get.createdOn should be(account.createdOn)
  }

```
Which would give us

`org.scalatest.exceptions.TestFailedException: 2018-10-03T11:03:29.658 was not equal to 2018-10-03T11:03:29.658573`

Though actual date in Postgres is OK:  `11:03:29.658573`

So while this works OK on JDK 8, everything that involves date manipulation suddenly starts failing on JDK9

**Comment by gytisgreitai** [comment]
@xuwei-k IMO this is a BUG, not a Question

**Comment by gytisgreitai** [comment]
@seratch why do you think so? IMO it does not depend on JDBC at all. Though I'm not a scala/java expert,  but the problem to me seems to be in Binders.scala:

```
val javaTimeLocalDateTime: Binders[java.time.LocalDateTime] = utilDate.xmap(nullThrough(_.toLocalDateTime), v => java.util.Date.from(v.atZone(java.time.ZoneId.systemDefault()).toInstant))
```

And if we look at Date.from implementation in JDK:
```
    public static Date from(Instant instant) {
        try {
            return new Date(instant.toEpochMilli());
        } catch (ArithmeticException ex) {
            throw new IllegalArgumentException(ex);
        }
    }
```

And `toEpochMilli()` suggests that ` Converts this instant to the number of milliseconds from the epoch of 1970-01-01T00:00:00Z.`

So am I missing something obvious that I should blame JDBC (note that time in postgres is stored in microseconds, and same code worked with JDK 8)?

**Comment by seratch** [comment]
Thanks. I understand your point.

> {@code Instant} uses a precision of nanoseconds, whereas {@code Date} uses a precision of milliseconds. The conversion will truncate any excess precision information as though the amount in nanoseconds was subject to integer division by one million.

https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/jdk-11%2B28/src/java.base/share/classes/java/util/Date.java#L1341-L1344

Indeed, `Date.from(Instant)` seems to truncate the micro/nano second parts.

I've not checked other possible factors that can be related to this issue yet, we need to update scalikejdbc code at least.

**Comment by xuwei-k** [comment]
scalikejdbc use `Timestamp.from` or `Timestamp.valueOf`

- https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/jdk-11%2B28/src/java.sql/share/classes/java/sql/Timestamp.java#L546
- https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/jdk-11%2B28/src/java.sql/share/classes/java/sql/Timestamp.java#L504
- https://github.com/scalikejdbc/scalikejdbc/blob/3.3.1/scalikejdbc-core/src/main/scala/scalikejdbc/StatementExecutor.scala#L199-L208

**Comment by gytisgreitai** [comment]
@xuwei-k I think you are talking about saving data to the database - there is no problem there. 
The problem arises retrieving data.

@seratch I was a bit wrong actually, the problem lies in `UnixTimeInMillisConverter` and `UnixTimeInMillisConverterImplicits` 

so:
`implicit def convertJavaUtilDateToConverter(t: utilDate): UnixTimeInMillisConverter = new UnixTimeInMillisConverter(t.getTime)` 

could be replaced with something like 
`implicit def convertJavaUtilDateToConverter(t: utilDate): UnixTimeInMillisConverter = new UnixTimeInMillisConverter(t.toInstant)`

**Comment by xuwei-k** [comment]
Thank you for explain the problem. I understood the problem. I'm going to fix this bug.

**Comment by seratch** [comment]
This issue has been fixed by #949 . Thank you very much, @xuwei-k .

**Comment by gytisgreitai** [comment]
thank you both !

**Comment by gytisgreitai** [comment]
@xuwei-k  I do think there is another issue, this time with `LocalTime` -it gets saved with milliseconds and not microseconds. So this time saving works incorrectly
