### ISSUE TITLE
Support to query with composites in sql interpolation.

### ISSUE THREAD

**Issue by ndomar** [scalikejdbc/scalikejdbc#948]
Hi,

I am currently trying to filter a table using a composite field, the query looks something like this.

        sql"""SELECT p_config_sku, p_country, min(p_discount_rate), max(p_discount_rate)
             |FROM ${Product.table}
             |WHERE concat(p_config_sku, p_country) IN (${list}) AND p_is_deleted IS FALSE
             |GROUP BY p_config_sku, p_country
            """.stripMargin
          .map(rs => (rs.string(1), rs.string(2), BigDecimal(rs.string(3)), BigDecimal(rs.string(4))))
          .list
          .apply
    

Where the input list is a List[scala.Tuple2] This is failing, throwing error "PSQLException: Can't infer the SQL type to use for an instance scala.Tuple2".

Is there anyway to get around this, is there any plan to include native support soon?

**Comment by seratch** [comment]
Let me close this issue due to its inactivity.
