### ISSUE TITLE
deprecate implicit def convertJavaSqlTimestampToConverter?

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#950]
lose nanoseconds

- https://github.com/scalikejdbc/scalikejdbc/blob/e36319086f05d667fc50434220abbf1514a9697f/scalikejdbc-core/src/main/scala/scalikejdbc/UnixTimeInMillisConverterImplicits.scala#L18
- https://github.com/scalikejdbc/scalikejdbc/issues/945

**Comment by seratch** [comment]
Thanks. It's about time to mark it as deprecated. If there is no concern with removing it in the future releases, we'll be able to remove it later. Maybe, marking it as deprecated in 3.4, and then, removing it in 3.5 or 4.0 would be a reasonable migration plan for it.

**Comment by xuwei-k** [comment]
Which is better? or another? 🤔 

- https://github.com/xuwei-k/scalikejdbc/commit/724c0cc3437e46df107dd23b73fdea9a03607be9?w=1
- https://github.com/xuwei-k/scalikejdbc/commit/6f8b1190cf9206f1f623ec0f9e4e9feb3a3a9764?w=1

**Comment by seratch** [comment]
If you rename https://github.com/xuwei-k/scalikejdbc/commit/724c0cc3437e46df107dd23b73fdea9a03607be9?w=1 to JavaUtilDateConverter, I prefer this way.
