### ISSUE TITLE
PostgreSQL "expr = {null-value-variable}" condition should generate "expr is null", even in SQL-Interpolation mode

### ISSUE THREAD

**Issue by hartmut27** [scalikejdbc/scalikejdbc#960]
Given a **PostgreSQL** table and a scalikejdbc statement as:

> sql"""select * from mytable where
>             column1 = ${myvariable}"""
> .map(rs => ... )

When `myvariable` gets null the SQL gets `... column1 = null ...`
which in PostgreSQL is _not_ working, as long as `transform_null_equals` configuration parameter is not set in the database (which would only be an half-cooked work-around).

It should automatically rewrite this (in case of `myvariable` is null) as `... column1 is null...` for getting the right query result.

Reason for this: "Do not write expression = NULL because NULL is not “equal to” NULL. (The null value represents an unknown value, and it is not known whether two unknown values are equal.)"
Source [https://www.postgresql.org/docs/11/static/functions-comparison.html](url)

"The correct SQL-spec-compliant behavior of expr = NULL is to always return null (unknown)"
Source [https://www.postgresql.org/docs/11/static/runtime-config-compatible.html](url)

If I've overseen an option to get this in scalikejdbc + postgresql working, please forgive me ;) I've searched but not yet found an answer to this!

**Comment by hartmut27** [comment]
In `scalikejdbc-core/src/main/scala/scalikejdbc/interpolation/SQLSyntax.scala` I've found a thing related to this, but this seems to handle `is null` only in combination with SqlSyntax, not in SQL-Interpolation mode, as in mentioned the example above. Is it possible, to have this in SQL-Interpolation mode also? 

>   def eq[A](column: SQLSyntax, value: A)(implicit ev: ParameterBinderFactory[A]): SQLSyntax = {
>     value match {
>       case null | None => sqls"${this} ${column} is null"
>       case _ => sqls"${this} ${column} = ${ev(value)}"
>     }
>   }
>   def ne[A](column: SQLSyntax, value: A)(implicit ev: ParameterBinderFactory[A]): SQLSyntax = {
>     value match {
>       case null | None => sqls"${this} ${column} is not null"
>       case _ => sqls"${this} ${column} <> ${ev(value)}"
>     }
>   }

**Comment by seratch** [comment]
>Is it possible, to have this in SQL-Interpolation mode also?

No, it isn't. I agree that it's very helpful if we could enable converting the part in SQL interpolation in some ways. But, I don't come up with any plausible idea to implement the magic yet.

**Comment by hartmut27** [comment]
Thanks a lot for your for your quick feedback! I'll close this issue, but if anybody has in idea how to solve in SQL-Interpolation mode, this is kept as reference.

As a workaround I will switch over to the `SQLSyntaxSupport` / `withSQL {...}` mode, where this PostgreSQL (and others) `xyz is null` logic is already implemented and working.
