### ISSUE TITLE
Embedded quotes in SQL statements are removed in debug logging

### ISSUE THREAD

**Issue by pnorman4** [scalikejdbc/scalikejdbc#968]
The new `PrintableQueryBuilder` trait removed quotes around fixed strings. Parameterized string are handled correctly.

Examples: 
1. Query `insert into books (title) values ('Scala')` is logged like `insert into books (title) values (Scala)`
2. Query `insert into books (title) values (?)` is logged like `insert into books (title) values ('Scala')`

I think the bug is in `StatementExecutor` row 97 -112.

It works in 3.1.0,

**Comment by seratch** [comment]
Thank you. You're right. I will fix it.
