### ISSUE TITLE
PrintableQueryBuilder date converter

### ISSUE THREAD

**Issue by pedorich-n** [scalikejdbc/scalikejdbc#986]
There is a code in `PrintableQueryBuilder` that formats Date values for SQL logging and looks like it doesn't include all possible values for `java.util`. I mean there is a converter for `java.util.Date` but not for `java.util.LocalDateTime`, for example. But at the same time there is a converter for `org.joda.time.LocalDateTime`. 
So `java.util.LocalDateTime` matches only last pattern and just ends up using `toString`. See the reference: https://github.com/scalikejdbc/scalikejdbc/blob/1518c1a54bfe2182843208bec38e0438b3010a68/scalikejdbc-core/src/main/scala/scalikejdbc/StatementExecutor.scala#L56-L68

https://github.com/scalikejdbc/scalikejdbc/blob/1518c1a54bfe2182843208bec38e0438b3010a68/scalikejdbc-core/src/main/scala/scalikejdbc/StatementExecutor.scala#L82

Also proposal: maybe there is a way to use binder for log printing? Because for example if I have code like this:
```scala
    case class CustomKey(value: String) extends AnyVal

    implicit val keyBinder = Binders.string.xmap(CustomKey.apply, _.value)
```

In the logs it'll looks like `CustomKey("something")` even though in DB will be inserted only `something`.

**Comment by seratch** [comment]
Indeed, `java.time.*` values should be supported.

**Comment by seratch** [comment]
ParameterBinder works also for the query logging. But in this case, just having more patterns here https://github.com/scalikejdbc/scalikejdbc/blob/1518c1a54bfe2182843208bec38e0438b3010a68/scalikejdbc-core/src/main/scala/scalikejdbc/StatementExecutor.scala#L50-L70 would be enough.

**Comment by pedorich-n** [comment]
Ok, I checked more code and I see that ParameterBinder really should work for logging but then why I see in logs not what I expected? 
I'm talking about this
```scala
    case class CustomKey(value: String) extends AnyVal

    implicit val keyBinder = Binders.string.xmap(CustomKey.apply, _.value)
```

> In the logs it'll looks like `CustomKey("something")` even though in DB will be inserted only `something`.

**Comment by seratch** [comment]
Ah, I see. `Binders` can be a `ParameterBinderFactory`. But it's not a `ParameterBinder`. Thus, in this case, the logging doesn't work with it properly. You're right. And unfortunately, I don't have any good idea to fix this so far.

**Comment by pedorich-n** [comment]
I'm cleaning issues/PRs opened by me and closing this.
Feel free to reopen if it's still relevant, but I don't need this anymore.
