### ISSUE TITLE
Integration with Framework Transactions

### ISSUE THREAD

**Issue by alwins0n** [scalikejdbc/scalikejdbc#988]
hey, this might be a wild one, but hear me out!

I am currently playing around using Java's Spring Framework with Scala and would like scalikejdbc as database library.

The way to integrate 3rd party libraries into the transaction management of spring framework is revolving around `TransactionAwareDataSourceProxy` which is a Datasource itself. The way this works is roughly:

call to a `@Transactional` annotated method -> interception by spring -> creation of a transaction with underlying connection -> this connection is served when the datasource is queried for a connection (as long as within that transacitonal method 

I noticed that scalike jdbc `DBConnection` does not allow anything other than `localTx/autoCommit/...` to write to the database - which all manipulate `autoCommit` property of the underlying connection.

I was wondering if I was missing something, or if its feasable to add a method like `use...` oder `with...` which basically gets the connection from the datasource, does something with it and closes it again (where the close is handled by the datasource accordingly) - but does NOT tamper with autoCommit itself

Its probably a big thing to ask adding anything to the API. so I am really hoping I missed something..

Thank you for your help and I am offering my help for PR!

**Comment by seratch** [comment]
ScalikeJDBC's way to handle connections has consideration for JTA compatibilities: https://github.com/scalikejdbc/scalikejdbc/issues/324
But we don't have any special consideration on the compatibilities with Spring Framework. I don't have any plan to work on it in the future, too.

One idea I come up with is as below. I understand it is not ideal but if your Spring app allows exposing `java.sql.Connection` inside the `@Transactional` wired methods, you can rely on the data source managed by Spring.

```scala
@Transcational
def findOrCerate(id: Long): Option[Something] = {
  DB(dataSource.getConnection).withinTx { implicit s =>
    // do something here
  }
}
```

Personally, I don't recommend you to use Spring Framework with Scala. A few years ago, some developers at Pivotal were working on Scala integration, but those are no longer maintained. You will encounter a lot of obstacles as long as you use it in Scala. If you are keen to use Spring, I recommend choosing Java or Kotlin instead.

That being said, I understand that playing with tech stack most people don't choose is fun! If you'll go with it, good luck :)

**Comment by alwins0n** [comment]
Thank you for your fast answer. The code you provided is valuable, since this is how the transaction system works. a call to getConnection would be returning to the thread-bound transactinonal connection.

But I will have to play around how it will behave if we are not in a transactional context. 

My question/issue could be seen broader: **couldn't there be any use case where you "dont't care" about how/if the connection handles transactions on updates?**

But yeah, spring with scala is an experiment for me. it hast its limitations, but as I tend to use only a small subset of framework features anyway, to not get "locked-in" too much. I am confident that it will be fun :) 
With that being said, I will consider not using declarative transaction management at all, which might be the "cleanest" solution

**Comment by seratch** [comment]
Do you mean that you're looking for some ways to bypass any additional modifications/operations to connections by ScalikeJDBC? If so, it could be done by doing like this:

```scala
def findOrCerate(id: Long): Something = {
  implicit val session = DBSession(dataSource.getConnection)
  // do something here
}
```
https://github.com/scalikejdbc/scalikejdbc/blob/3.3.2/scalikejdbc-core/src/main/scala/scalikejdbc/DBSession.scala#L809-L816

**Comment by alwins0n** [comment]
I failed to see the obvious. Thank you for the hint. I think I have an idea now on how to use it within my project. I will close the issue.

**Comment by alwins0n** [comment]
hey @seratch , sorry to bother you, but I really value your opinion here.

I implemented the integration like you suggested by creating a `DBSession` directly from the datasource. Unfortunately the `apply` factory method checks if there is an active transaction `Some(tx)` and if not sets the datasource to autocommit.

This is sane behaviour but does not allow me to used the Session as you suggested. The only solution I could come up with is to roll my own implementation of the `DBSession` trait which does not perform the checks mentioned before.

What do you think about that? Could I do better or did I miss something? Are there any caveats with that, I do not see (yet)?

Thank you a lot!

**Comment by seratch** [comment]
Having the following global setting should work for you.

```scala
GlobalSettings.jtaDataSourceCompatible = true
```
