### ISSUE TITLE
idle connections are not closed after a while

### ISSUE THREAD

**Issue by linehrr** [scalikejdbc/scalikejdbc#993]
after configure the ConnectionPool and using the default settings, we found out that the used idle connections are not close even after quite a while. 

> tcp        0      0 10.65.17.170:41596      10.65.17.182:3306       ESTABLISHED 3972/java

as shown above, this persistent connection sticks for a long time, even tho we know it's not used by the process. reading through the document, not found anything related to idle connection timeout setting and maxIdelConnection settings. 
so just wondering if there is any feature supporting auto close idle settings and it's just not reflected in the docs.

**Comment by seratch** [comment]
The default settings are like this: https://github.com/scalikejdbc/scalikejdbc/blob/3.3.2/scalikejdbc-core/src/main/scala/scalikejdbc/Commons2ConnectionPool.scala#L30-L34

If you would like connections to be closed after a while, you can set `minEvictableIdleTimeMillis` in your connection pool. https://commons.apache.org/proper/commons-dbcp/configuration.html

At this moment, I'm not willing to add such a setting to `Commons2ConnectionPool`. Please feel free to copy the implementation and modify it as you like.

**Comment by linehrr** [comment]
ok fair enough. 
close ticket.
