### ISSUE TITLE
How to do select or insert query?

### ISSUE THREAD

**Issue by z4f1r0v** [scalikejdbc/scalikejdbc#996]
I have the following SQL code I would to execute against a Postgresql db:
```
    sql"""WITH s AS (
             SELECT id
             FROM $tableName
             WHERE $columnName = $value
         ), i AS (
             INSERT INTO $tableName ($columnName)
         	SELECT $value
         	WHERE NOT EXISTS (
         		SELECT id
         		FROM $tableName
         		WHERE $columnName = $value
         	)
         	RETURNING id
         )
         SELECT id
         FROM i
         UNION ALL
         SELECT id
         FROM s
      """
```
If I use `update` or `updateAndRetrieveGeneratedKey` within a `localTx` I get `org.postgresql.util.PSQLException: A result was returned when none was expected.`. If I use `single` within `readOnly` I get something like `... cannot perform an insert in a read only query`.
What is the proper way to go about this?

**Comment by seratch** [comment]
I've never tried yet but what happens if you run the query as blow?
```scala
// or DB.autoCommit {
DB.localTx { implicit s =>
  selectOrInsertQuery.map(toObject).list.apply()
}
```

**Comment by akaivola** [comment]
The problem is in SQL.scala:814 which always assumes AutoSession is using DB.readonly irregardless what the AutoSession.isReadOnly flag is saying.

This complicates things a lot when using AutoSession- that is, they can't be used at all if at any point in the transaction there happens to be an insert.

**Comment by seratch** [comment]
@akaivola Thanks. The line 814 you mentioned is this line: https://github.com/scalikejdbc/scalikejdbc/blob/3.3.5/scalikejdbc-core/src/main/scala/scalikejdbc/SQL.scala#L814

I understand your point. But, on the other hand, I don't have any ideas to eliminate your problems here except for removing `AutoSesison` from the default param for methods or not to use  AutoSession as much as possible.

**Comment by seratch** [comment]
As I mentioned above, there is no other suggestion apart from using the right session type (read-only, auto-commit, read-only) for each query in this scenario. Let me lose this issue now.
